// This file is auto-generated by @codewithagents/openapi-gen — do not edit

import type { ApiResponse, Order, Pet, User } from './models.js'
import { getConfig, type ClientConfig } from './client-config.js'

export class ApiError<Status extends number = number, Body = unknown> extends Error {
  constructor(
    public readonly status: Status,
    public readonly body: Body
  ) {
    super(`API error ${status}`)
    this.name = 'ApiError'
  }
}

type _FetchResponse = Awaited<ReturnType<typeof fetch>>

function _buildSignal(
  signal: AbortSignal | undefined,
  timeout: number | undefined
): AbortSignal | undefined {
  if (timeout === undefined) return signal
  const _ts = AbortSignal.timeout(timeout)
  if (signal === undefined) return _ts
  if (typeof AbortSignal.any === 'function') return AbortSignal.any([signal, _ts])
  const _ctrl = new AbortController()
  const _abort = (s: AbortSignal) => () => {
    if (!_ctrl.signal.aborted) _ctrl.abort(s.reason)
  }
  signal.addEventListener('abort', _abort(signal), { once: true })
  _ts.addEventListener('abort', _abort(_ts), { once: true })
  return _ctrl.signal
}

async function _request(
  method: string,
  path: string,
  opts: {
    searchParams?: URLSearchParams
    body?: unknown
    extraHeaders?: Record<string, string>
    signal?: AbortSignal
  },
  config?: Partial<ClientConfig>
): Promise<_FetchResponse> {
  const {
    baseUrl,
    token,
    apiKey,
    headers,
    onError,
    signal: _cfgSignal,
    timeout,
    onRequest,
    fetch: _configFetch,
  } = { ...getConfig(), ...config }
  const resolvedToken = typeof token === 'function' ? await token() : token
  const resolvedApiKey = typeof apiKey === 'function' ? await apiKey() : apiKey
  const base = baseUrl ? baseUrl.replace(/\/$/, '') : ''
  const qs = opts.searchParams?.toString() ?? ''
  const url = qs ? `${base}${path}?${qs}` : `${base}${path}`
  const fetch = _configFetch ?? globalThis.fetch
  let _url = url
  let _init: RequestInit = {
    method,
    headers: {
      ...(opts.body !== undefined ? { 'Content-Type': 'application/json' } : {}),
      ...headers,
      ...(resolvedToken ? { Authorization: `Bearer ${resolvedToken}` } : {}),
      ...(resolvedApiKey ? { api_key: resolvedApiKey } : {}),
      ...opts.extraHeaders,
    },
    ...(opts.body !== undefined ? { body: JSON.stringify(opts.body) } : {}),
  }
  if (onRequest) {
    const _or = await onRequest({ url: _url, init: _init })
    if (_or) {
      if (_or.url !== undefined) _url = _or.url
      if (_or.init !== undefined) _init = { ..._init, ..._or.init }
    }
  }
  const _rawSignal = opts.signal ?? _cfgSignal
  const _resolvedSignal = _buildSignal(_rawSignal, timeout)
  if (_resolvedSignal !== undefined) _init = { ..._init, signal: _resolvedSignal }
  const res = await fetch(_url, _init)
  if (!res.ok) {
    const err = new ApiError(res.status, await res.json().catch(() => null))
    onError?.(err)
    throw err
  }
  return res
}

export async function addPet(body: Pet, config?: Partial<ClientConfig>): Promise<Pet> {
  const res = await _request('POST', '/pet', { body }, config)
  return res.json()
}

export async function updatePet(body: Pet, config?: Partial<ClientConfig>): Promise<Pet> {
  const res = await _request('PUT', '/pet', { body }, config)
  return res.json()
}

export async function findPetsByStatus(
  params: {
    status: 'available' | 'pending' | 'sold'
  },
  config?: Partial<ClientConfig>
): Promise<Pet[]> {
  const searchParams = new URLSearchParams()
  if (params?.status != null) searchParams.set('status', String(params.status))
  const res = await _request('GET', '/pet/findByStatus', { searchParams }, config)
  return res.json()
}

export async function findPetsByTags(
  params: {
    tags: string[]
  },
  config?: Partial<ClientConfig>
): Promise<Pet[]> {
  const searchParams = new URLSearchParams()
  if (params?.tags != null) {
    for (const v of params.tags) searchParams.append('tags', String(v))
  }
  const res = await _request('GET', '/pet/findByTags', { searchParams }, config)
  return res.json()
}

export async function getPetById(petId: string, config?: Partial<ClientConfig>): Promise<Pet> {
  const res = await _request('GET', `/pet/${encodeURIComponent(petId)}`, {}, config)
  return res.json()
}

export async function updatePetWithForm(
  petId: string,
  params?: {
    name?: string
    status?: string
  },
  config?: Partial<ClientConfig>
): Promise<Pet> {
  const searchParams = new URLSearchParams()
  if (params?.name != null) searchParams.set('name', String(params.name))
  if (params?.status != null) searchParams.set('status', String(params.status))
  const res = await _request('POST', `/pet/${encodeURIComponent(petId)}`, { searchParams }, config)
  return res.json()
}

export async function deletePet(
  petId: string,
  params?: {
    api_key?: string
  },
  config?: Partial<ClientConfig>
): Promise<void> {
  const extraHeaders: Record<string, string> = {
    ...(params?.api_key != null ? { api_key: String(params.api_key) } : {}),
  }
  await _request('DELETE', `/pet/${encodeURIComponent(petId)}`, { extraHeaders }, config)
}

export async function uploadFile(
  petId: string,
  params?: {
    additionalMetadata?: string
  },
  config?: Partial<ClientConfig>
): Promise<ApiResponse> {
  const searchParams = new URLSearchParams()
  if (params?.additionalMetadata != null)
    searchParams.set('additionalMetadata', String(params.additionalMetadata))
  const res = await _request(
    'POST',
    `/pet/${encodeURIComponent(petId)}/uploadImage`,
    { searchParams },
    config
  )
  return res.json()
}

export async function getInventory(
  config?: Partial<ClientConfig>
): Promise<Record<string, unknown>> {
  const res = await _request('GET', '/store/inventory', {}, config)
  return res.json()
}

export async function placeOrder(body: Order, config?: Partial<ClientConfig>): Promise<Order> {
  const res = await _request('POST', '/store/order', { body }, config)
  return res.json()
}

export async function getOrderById(
  orderId: string,
  config?: Partial<ClientConfig>
): Promise<Order> {
  const res = await _request('GET', `/store/order/${encodeURIComponent(orderId)}`, {}, config)
  return res.json()
}

export async function deleteOrder(orderId: string, config?: Partial<ClientConfig>): Promise<void> {
  await _request('DELETE', `/store/order/${encodeURIComponent(orderId)}`, {}, config)
}

export async function createUser(body: User, config?: Partial<ClientConfig>): Promise<User> {
  const res = await _request('POST', '/user', { body }, config)
  return res.json()
}

export async function createUsersWithListInput(
  body: User[],
  config?: Partial<ClientConfig>
): Promise<User> {
  const res = await _request('POST', '/user/createWithList', { body }, config)
  return res.json()
}

export async function loginUser(
  params?: {
    username?: string
    password?: string
  },
  config?: Partial<ClientConfig>
): Promise<string> {
  const searchParams = new URLSearchParams()
  if (params?.username != null) searchParams.set('username', String(params.username))
  if (params?.password != null) searchParams.set('password', String(params.password))
  const res = await _request('GET', '/user/login', { searchParams }, config)
  return res.json()
}

export async function logoutUser(config?: Partial<ClientConfig>): Promise<void> {
  await _request('GET', '/user/logout', {}, config)
}

export async function getUserByName(
  username: string,
  config?: Partial<ClientConfig>
): Promise<User> {
  const res = await _request('GET', `/user/${encodeURIComponent(username)}`, {}, config)
  return res.json()
}

export async function updateUser(
  username: string,
  body: User,
  config?: Partial<ClientConfig>
): Promise<void> {
  await _request('PUT', `/user/${encodeURIComponent(username)}`, { body }, config)
}

export async function deleteUser(username: string, config?: Partial<ClientConfig>): Promise<void> {
  await _request('DELETE', `/user/${encodeURIComponent(username)}`, {}, config)
}
