// This file is auto-generated by @codewithagents/openapi-react-query — do not edit

import {
  queryOptions,
  useQuery,
  type UseQueryOptions,
  useMutation,
  type UseMutationOptions,
} from '@tanstack/react-query'
import {
  addPet,
  createUser,
  createUsersWithListInput,
  deleteOrder,
  deletePet,
  deleteUser,
  findPetsByStatus,
  findPetsByTags,
  getInventory,
  getOrderById,
  getPetById,
  getUserByName,
  loginUser,
  logoutUser,
  placeOrder,
  updatePet,
  updatePetWithForm,
  updateUser,
  uploadFile,
  type ApiError,
} from './client.js'

// ── Query key factories ──────────────────────────────────────

export const petKeys = {
  all: () => ['pet'] as const,
  findPetsByStatus: (params: Parameters<typeof findPetsByStatus>[0]) =>
    ['pet', 'findPetsByStatus', params] as const,
  findPetsByTags: (params: Parameters<typeof findPetsByTags>[0]) =>
    ['pet', 'findPetsByTags', params] as const,
  detail: (petId: string) => ['pet', petId] as const,
}

export const storeKeys = {
  all: () => ['store'] as const,
  list: () => ['store', 'list'] as const,
  detail: (orderId: string) => ['store', orderId] as const,
}

export const userKeys = {
  all: () => ['user'] as const,
  loginUser: (params?: Parameters<typeof loginUser>[0]) => ['user', 'loginUser', params] as const,
  logoutUser: () => ['user', 'logoutUser'] as const,
  detail: (username: string) => ['user', username] as const,
}

// ── Query options factories ──────────────────────────────────

export function findPetsByStatusQueryOptions(
  params: Parameters<typeof findPetsByStatus>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findPetsByStatus>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findPetsByStatus>>, ApiError>({
    queryKey: petKeys.findPetsByStatus(params),
    queryFn: () => findPetsByStatus(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findPetsByTagsQueryOptions(
  params: Parameters<typeof findPetsByTags>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findPetsByTags>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findPetsByTags>>, ApiError>({
    queryKey: petKeys.findPetsByTags(params),
    queryFn: () => findPetsByTags(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getPetByIdQueryOptions(
  petId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getPetById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getPetById>>, ApiError>({
    queryKey: petKeys.detail(petId),
    queryFn: () => getPetById(petId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getInventoryQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getInventory>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getInventory>>, ApiError>({
    queryKey: storeKeys.list(),
    queryFn: () => getInventory(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getOrderByIdQueryOptions(
  orderId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getOrderById>>, ApiError>({
    queryKey: storeKeys.detail(orderId),
    queryFn: () => getOrderById(orderId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function loginUserQueryOptions(
  params?: Parameters<typeof loginUser>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof loginUser>>, ApiError>({
    queryKey: userKeys.loginUser(params),
    queryFn: () => loginUser(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function logoutUserQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof logoutUser>>, ApiError>({
    queryKey: userKeys.logoutUser(),
    queryFn: () => logoutUser(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getUserByNameQueryOptions(
  username: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getUserByName>>, ApiError>({
    queryKey: userKeys.detail(username),
    queryFn: () => getUserByName(username),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Queries ──────────────────────────────────────────────────

export function useFindPetsByStatus(
  params: Parameters<typeof findPetsByStatus>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findPetsByStatus>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findPetsByStatus>>, ApiError>({
    queryKey: petKeys.findPetsByStatus(params),
    queryFn: () => findPetsByStatus(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindPetsByTags(
  params: Parameters<typeof findPetsByTags>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findPetsByTags>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findPetsByTags>>, ApiError>({
    queryKey: petKeys.findPetsByTags(params),
    queryFn: () => findPetsByTags(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetPetById(
  petId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getPetById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getPetById>>, ApiError>({
    queryKey: petKeys.detail(petId!),
    queryFn: () => getPetById(petId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: petId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetInventory(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getInventory>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getInventory>>, ApiError>({
    queryKey: storeKeys.list(),
    queryFn: () => getInventory(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetOrderById(
  orderId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getOrderById>>, ApiError>({
    queryKey: storeKeys.detail(orderId!),
    queryFn: () => getOrderById(orderId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: orderId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useLoginUser(
  params?: Parameters<typeof loginUser>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof loginUser>>, ApiError>({
    queryKey: userKeys.loginUser(params),
    queryFn: () => loginUser(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useLogoutUser(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof logoutUser>>, ApiError>({
    queryKey: userKeys.logoutUser(),
    queryFn: () => logoutUser(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetUserByName(
  username: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getUserByName>>, ApiError>({
    queryKey: userKeys.detail(username!),
    queryFn: () => getUserByName(username!),
    staleTime: 0,
    gcTime: 300000,
    enabled: username != null && (options?.enabled ?? true),
    ...options,
  })
}

// ── Mutations ────────────────────────────────────────────────

export function useAddPet(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof addPet>>, ApiError, Parameters<typeof addPet>[0]>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof addPet>>, ApiError, Parameters<typeof addPet>[0]>({
    mutationFn: (vars) => addPet(vars),
    ...options,
  })
}

export function useUpdatePet(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof updatePet>>,
      ApiError,
      Parameters<typeof updatePet>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof updatePet>>,
    ApiError,
    Parameters<typeof updatePet>[0]
  >({
    mutationFn: (vars) => updatePet(vars),
    ...options,
  })
}

export function useUpdatePetWithForm(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof updatePetWithForm>>,
      ApiError,
      { petId: string; params: Parameters<typeof updatePetWithForm>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof updatePetWithForm>>,
    ApiError,
    { petId: string; params: Parameters<typeof updatePetWithForm>[1] }
  >({
    mutationFn: ({ petId, params }) => updatePetWithForm(petId, params),
    ...options,
  })
}

export function useDeletePet(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deletePet>>,
      ApiError,
      { petId: string; params: Parameters<typeof deletePet>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deletePet>>,
    ApiError,
    { petId: string; params: Parameters<typeof deletePet>[1] }
  >({
    mutationFn: ({ petId, params }) => deletePet(petId, params),
    ...options,
  })
}

export function useUploadFile(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof uploadFile>>,
      ApiError,
      {
        petId: string
        body: Parameters<typeof uploadFile>[1]
        params: Parameters<typeof uploadFile>[2]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof uploadFile>>,
    ApiError,
    {
      petId: string
      body: Parameters<typeof uploadFile>[1]
      params: Parameters<typeof uploadFile>[2]
    }
  >({
    mutationFn: ({ petId, body, params }) => uploadFile(petId, body, params),
    ...options,
  })
}

export function usePlaceOrder(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof placeOrder>>,
      ApiError,
      Parameters<typeof placeOrder>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof placeOrder>>,
    ApiError,
    Parameters<typeof placeOrder>[0]
  >({
    mutationFn: (vars) => placeOrder(vars),
    ...options,
  })
}

export function useDeleteOrder(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteOrder>>, ApiError, string>({
    mutationFn: (orderId) => deleteOrder(orderId),
    ...options,
  })
}

export function useCreateUser(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createUser>>,
      ApiError,
      Parameters<typeof createUser>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createUser>>,
    ApiError,
    Parameters<typeof createUser>[0]
  >({
    mutationFn: (vars) => createUser(vars),
    ...options,
  })
}

export function useCreateUsersWithListInput(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createUsersWithListInput>>,
      ApiError,
      Parameters<typeof createUsersWithListInput>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createUsersWithListInput>>,
    ApiError,
    Parameters<typeof createUsersWithListInput>[0]
  >({
    mutationFn: (vars) => createUsersWithListInput(vars),
    ...options,
  })
}

export function useUpdateUser(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      ApiError,
      { username: string; body: Parameters<typeof updateUser>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof updateUser>>,
    ApiError,
    { username: string; body: Parameters<typeof updateUser>[1] }
  >({
    mutationFn: ({ username, body }) => updateUser(username, body),
    ...options,
  })
}

export function useDeleteUser(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteUser>>, ApiError, string>({
    mutationFn: (username) => deleteUser(username),
    ...options,
  })
}
