// This file is auto-generated by openapi-zod-ts - do not edit

export interface Order {
  id?: number /* int64, precision limited to 2^53-1 */
  petId?: number /* int64, precision limited to 2^53-1 */
  quantity?: number
  shipDate?: string /* date-time */
  status?: 'placed' | 'approved' | 'delivered'
  complete?: boolean
}

export interface Category {
  id?: number /* int64, precision limited to 2^53-1 */
  name?: string
}

export interface User {
  id?: number /* int64, precision limited to 2^53-1 */
  username?: string
  firstName?: string
  lastName?: string
  email?: string
  password?: string
  phone?: string
  userStatus?: number
}

export interface Tag {
  id?: number /* int64, precision limited to 2^53-1 */
  name?: string
}

export interface Pet {
  id?: number /* int64, precision limited to 2^53-1 */
  name: string
  category?: Category
  photoUrls: string[]
  tags?: Tag[]
  status?: 'available' | 'pending' | 'sold'
}

export interface ApiResponse {
  code?: number
  type?: string
  message?: string
}
