// This file is auto-generated by @codewithagents/openapi-react-query — do not edit

import {
  queryOptions,
  useQuery,
  type UseQueryOptions,
  useInfiniteQuery,
  type UseInfiniteQueryOptions,
  type InfiniteData,
  type QueryKey,
  useMutation,
  type UseMutationOptions,
} from '@tanstack/react-query'
import {
  createVaultItem,
  deleteVaultItem,
  downloadFileByID,
  getApiActivity,
  getDetailsOfFileById,
  getHeartbeat,
  getItemFiles,
  getPrometheusMetrics,
  getServerHealth,
  getVaultById,
  getVaultItemById,
  getVaultItems,
  getVaults,
  patchVaultItem,
  updateVaultItem,
  type ApiError,
} from './client.js'

// ── Query key factories ──────────────────────────────────────

export const activityKeys = {
  all: () => ['activity'] as const,
  list: (params?: Parameters<typeof getApiActivity>[0]) => ['activity', 'list', params] as const,
}

export const vaultKeys = {
  all: () => ['vaults'] as const,
  list: (params?: Parameters<typeof getVaults>[0]) => ['vaults', 'list', params] as const,
  getVaultById: (vaultUuid: string) => ['vaults', 'getVaultById', vaultUuid] as const,
  getVaultItems: (vaultUuid: string, params?: Parameters<typeof getVaultItems>[1]) =>
    ['vaults', 'getVaultItems', vaultUuid, params] as const,
  getVaultItemById: (vaultUuid: string, itemUuid: string) =>
    ['vaults', 'getVaultItemById', vaultUuid, itemUuid] as const,
  getItemFiles: (
    vaultUuid: string,
    itemUuid: string,
    params?: Parameters<typeof getItemFiles>[2]
  ) => ['vaults', 'getItemFiles', vaultUuid, itemUuid, params] as const,
  getDetailsOfFileById: (
    vaultUuid: string,
    itemUuid: string,
    fileUuid: string,
    params?: Parameters<typeof getDetailsOfFileById>[3]
  ) => ['vaults', 'getDetailsOfFileById', vaultUuid, itemUuid, fileUuid, params] as const,
  downloadFileByID: (vaultUuid: string, itemUuid: string, fileUuid: string) =>
    ['vaults', 'downloadFileByID', vaultUuid, itemUuid, fileUuid] as const,
}

export const heartbeatKeys = {
  all: () => ['heartbeat'] as const,
  list: () => ['heartbeat', 'list'] as const,
}

export const healthKeys = {
  all: () => ['health'] as const,
  list: () => ['health', 'list'] as const,
}

export const metricKeys = {
  all: () => ['metrics'] as const,
  list: () => ['metrics', 'list'] as const,
}

// ── Query options factories ──────────────────────────────────

export function getApiActivityQueryOptions(
  params?: Parameters<typeof getApiActivity>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getApiActivity>>, ApiError>({
    queryKey: activityKeys.list(params),
    queryFn: () => getApiActivity(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getVaultsQueryOptions(
  params?: Parameters<typeof getVaults>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getVaults>>, ApiError>({
    queryKey: vaultKeys.list(params),
    queryFn: () => getVaults(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getVaultByIdQueryOptions(
  vaultUuid: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getVaultById>>, ApiError>({
    queryKey: vaultKeys.getVaultById(vaultUuid),
    queryFn: () => getVaultById(vaultUuid),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getVaultItemsQueryOptions(
  vaultUuid: string,
  params?: Parameters<typeof getVaultItems>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultItems>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getVaultItems>>, ApiError>({
    queryKey: vaultKeys.getVaultItems(vaultUuid, params),
    queryFn: () => getVaultItems(vaultUuid, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getVaultItemByIdQueryOptions(
  vaultUuid: string,
  itemUuid: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultItemById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getVaultItemById>>, ApiError>({
    queryKey: vaultKeys.getVaultItemById(vaultUuid, itemUuid),
    queryFn: () => getVaultItemById(vaultUuid, itemUuid),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getItemFilesQueryOptions(
  vaultUuid: string,
  itemUuid: string,
  params?: Parameters<typeof getItemFiles>[2],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getItemFiles>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getItemFiles>>, ApiError>({
    queryKey: vaultKeys.getItemFiles(vaultUuid, itemUuid, params),
    queryFn: () => getItemFiles(vaultUuid, itemUuid, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDetailsOfFileByIdQueryOptions(
  vaultUuid: string,
  itemUuid: string,
  fileUuid: string,
  params?: Parameters<typeof getDetailsOfFileById>[3],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDetailsOfFileById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDetailsOfFileById>>, ApiError>({
    queryKey: vaultKeys.getDetailsOfFileById(vaultUuid, itemUuid, fileUuid, params),
    queryFn: () => getDetailsOfFileById(vaultUuid, itemUuid, fileUuid, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function downloadFileByIDQueryOptions(
  vaultUuid: string,
  itemUuid: string,
  fileUuid: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof downloadFileByID>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof downloadFileByID>>, ApiError>({
    queryKey: vaultKeys.downloadFileByID(vaultUuid, itemUuid, fileUuid),
    queryFn: () => downloadFileByID(vaultUuid, itemUuid, fileUuid),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getHeartbeatQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getHeartbeat>>, ApiError>({
    queryKey: heartbeatKeys.list(),
    queryFn: () => getHeartbeat(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getServerHealthQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getServerHealth>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getServerHealth>>, ApiError>({
    queryKey: healthKeys.list(),
    queryFn: () => getServerHealth(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getPrometheusMetricsQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getPrometheusMetrics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getPrometheusMetrics>>, ApiError>({
    queryKey: metricKeys.list(),
    queryFn: () => getPrometheusMetrics(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Queries ──────────────────────────────────────────────────

export function useGetApiActivity(
  params?: Parameters<typeof getApiActivity>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getApiActivity>>, ApiError>({
    queryKey: activityKeys.list(params),
    queryFn: () => getApiActivity(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetApiActivityInfinite(
  params?: Parameters<typeof getApiActivity>[0],
  options?: Omit<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getApiActivity>>,
      ApiError,
      InfiniteData<Awaited<ReturnType<typeof getApiActivity>>>,
      QueryKey,
      unknown
    >,
    'queryKey' | 'queryFn' | 'getNextPageParam' | 'initialPageParam'
  >
) {
  return useInfiniteQuery<
    Awaited<ReturnType<typeof getApiActivity>>,
    ApiError,
    InfiniteData<Awaited<ReturnType<typeof getApiActivity>>>,
    QueryKey,
    unknown
  >({
    queryKey: [...activityKeys.list(params), 'infinite'],
    queryFn: ({ pageParam }) => getApiActivity({ ...params, offset: pageParam as never }),
    initialPageParam: undefined,
    // Override getNextPageParam in options to enable actual pagination.
    getNextPageParam: () => undefined,
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetVaults(
  params?: Parameters<typeof getVaults>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getVaults>>, ApiError>({
    queryKey: vaultKeys.list(params),
    queryFn: () => getVaults(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetVaultById(
  vaultUuid: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getVaultById>>, ApiError>({
    queryKey: vaultKeys.getVaultById(vaultUuid!),
    queryFn: () => getVaultById(vaultUuid!),
    staleTime: 0,
    gcTime: 300000,
    enabled: vaultUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetVaultItems(
  vaultUuid: string | undefined | null,
  params?: Parameters<typeof getVaultItems>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultItems>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getVaultItems>>, ApiError>({
    queryKey: vaultKeys.getVaultItems(vaultUuid!, params),
    queryFn: () => getVaultItems(vaultUuid!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: vaultUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetVaultItemById(
  vaultUuid: string | undefined | null,
  itemUuid: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getVaultItemById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getVaultItemById>>, ApiError>({
    queryKey: vaultKeys.getVaultItemById(vaultUuid!, itemUuid!),
    queryFn: () => getVaultItemById(vaultUuid!, itemUuid!),
    staleTime: 0,
    gcTime: 300000,
    enabled: vaultUuid != null && itemUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetItemFiles(
  vaultUuid: string | undefined | null,
  itemUuid: string | undefined | null,
  params?: Parameters<typeof getItemFiles>[2],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getItemFiles>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getItemFiles>>, ApiError>({
    queryKey: vaultKeys.getItemFiles(vaultUuid!, itemUuid!, params),
    queryFn: () => getItemFiles(vaultUuid!, itemUuid!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: vaultUuid != null && itemUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDetailsOfFileById(
  vaultUuid: string | undefined | null,
  itemUuid: string | undefined | null,
  fileUuid: string | undefined | null,
  params?: Parameters<typeof getDetailsOfFileById>[3],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDetailsOfFileById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDetailsOfFileById>>, ApiError>({
    queryKey: vaultKeys.getDetailsOfFileById(vaultUuid!, itemUuid!, fileUuid!, params),
    queryFn: () => getDetailsOfFileById(vaultUuid!, itemUuid!, fileUuid!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled:
      vaultUuid != null && itemUuid != null && fileUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useDownloadFileByID(
  vaultUuid: string | undefined | null,
  itemUuid: string | undefined | null,
  fileUuid: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof downloadFileByID>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof downloadFileByID>>, ApiError>({
    queryKey: vaultKeys.downloadFileByID(vaultUuid!, itemUuid!, fileUuid!),
    queryFn: () => downloadFileByID(vaultUuid!, itemUuid!, fileUuid!),
    staleTime: 0,
    gcTime: 300000,
    enabled:
      vaultUuid != null && itemUuid != null && fileUuid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetHeartbeat(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getHeartbeat>>, ApiError>({
    queryKey: heartbeatKeys.list(),
    queryFn: () => getHeartbeat(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetServerHealth(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getServerHealth>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getServerHealth>>, ApiError>({
    queryKey: healthKeys.list(),
    queryFn: () => getServerHealth(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetPrometheusMetrics(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getPrometheusMetrics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getPrometheusMetrics>>, ApiError>({
    queryKey: metricKeys.list(),
    queryFn: () => getPrometheusMetrics(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Mutations ────────────────────────────────────────────────

export function useCreateVaultItem(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createVaultItem>>,
      ApiError,
      { vaultUuid: string; body: Parameters<typeof createVaultItem>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createVaultItem>>,
    ApiError,
    { vaultUuid: string; body: Parameters<typeof createVaultItem>[1] }
  >({
    mutationFn: ({ vaultUuid, body }) => createVaultItem(vaultUuid, body),
    ...options,
  })
}

export function useUpdateVaultItem(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof updateVaultItem>>,
      ApiError,
      { vaultUuid: string; itemUuid: string; body: Parameters<typeof updateVaultItem>[2] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof updateVaultItem>>,
    ApiError,
    { vaultUuid: string; itemUuid: string; body: Parameters<typeof updateVaultItem>[2] }
  >({
    mutationFn: ({ vaultUuid, itemUuid, body }) => updateVaultItem(vaultUuid, itemUuid, body),
    ...options,
  })
}

export function usePatchVaultItem(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchVaultItem>>,
      ApiError,
      { vaultUuid: string; itemUuid: string; body: Parameters<typeof patchVaultItem>[2] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchVaultItem>>,
    ApiError,
    { vaultUuid: string; itemUuid: string; body: Parameters<typeof patchVaultItem>[2] }
  >({
    mutationFn: ({ vaultUuid, itemUuid, body }) => patchVaultItem(vaultUuid, itemUuid, body),
    ...options,
  })
}

export function useDeleteVaultItem(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteVaultItem>>,
      ApiError,
      { vaultUuid: string; itemUuid: string }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteVaultItem>>,
    ApiError,
    { vaultUuid: string; itemUuid: string }
  >({
    mutationFn: ({ vaultUuid, itemUuid }) => deleteVaultItem(vaultUuid, itemUuid),
    ...options,
  })
}
