// This file is auto-generated by openapi-zod-ts - do not edit

export interface ArticleFlareTag {
  name?: string
  bg_color_hex?: string | null
  text_color_hex?: string | null
}

export interface ArticleIndex {
  type_of: string
  id: number
  title: string
  description: string
  cover_image: string | null
  readable_publish_date: string
  social_image: string
  tag_list: string[]
  tags: string
  slug: string
  path: string
  url: string
  canonical_url: string
  positive_reactions_count: number
  public_reactions_count: number
  created_at: string /* date-time */
  edited_at: string | null
  crossposted_at: string | null
  published_at: string /* date-time */
  last_comment_at: string /* date-time */
  published_timestamp: string /* date-time */
  reading_time_minutes: number
  user: SharedUser
  flare_tag?: ArticleFlareTag
  organization?: SharedOrganization
}

export interface VideoArticle {
  type_of?: string
  id?: number /* int64, precision limited to 2^53-1 */
  path?: string
  cloudinary_video_url?: string
  title?: string
  user_id?: number /* int64, precision limited to 2^53-1 */
  video_duration_in_minutes?: string
  video_source_url?: string
  user?: {
    name?: string
  }
}

export interface Article {
  article?: {
    title?: string
    body_markdown?: string
    published?: boolean
    series?: string | null
    main_image?: string | null
    canonical_url?: string | null
    description?: string
    tags?: string
    organization_id?: number | null
  }
}

export interface Organization {
  type_of?: string
  username?: string
  name?: string
  summary?: string
  twitter_username?: string
  github_username?: string
  url?: string
  location?: string
  joined_at?: string
  tech_stack?: string
  tag_line?: string | null
  story?: string | null
}

export interface FollowedTag {
  id: number /* int64, precision limited to 2^53-1 */
  name: string
  points: number
}

export interface Tag {
  id?: number /* int64, precision limited to 2^53-1 */
  name?: string
  bg_color_hex?: string | null
  text_color_hex?: string | null
}

export interface Page {
  title: string
  slug: string
  description: string
  body_markdown?: string | null
  body_json?: string | null
  is_top_level_path?: boolean
  social_image?: Record<string, unknown> | null
  template: 'contained' | 'full_within_layout' | 'nav_bar_included' | 'json' | 'css' | 'txt'
}

export interface PodcastEpisodeIndex {
  type_of: string
  id: number
  class_name: string
  path: string
  title: string
  image_url: string
  podcast: SharedPodcast
}

export interface ProfileImage {
  type_of?: string
  image_of?: string
  profile_image?: string
  profile_image_90?: string
}

export interface SharedUser {
  name?: string
  username?: string
  twitter_username?: string | null
  github_username?: string | null
  website_url?: string | null
  profile_image?: string
  profile_image_90?: string
}

export interface SharedOrganization {
  name?: string
  username?: string
  slug?: string
  profile_image?: string
  profile_image_90?: string
}

export interface User {
  type_of?: string
  id?: number /* int64, precision limited to 2^53-1 */
  username?: string
  name?: string
  summary?: string | null
  twitter_username?: string
  github_username?: string
  website_url?: string | null
  location?: string | null
  joined_at?: string
  profile_image?: string
}

export interface ExtendedUser {
  type_of?: string
  id?: number /* int64, precision limited to 2^53-1 */
  username?: string
  name?: string
  summary?: string | null
  twitter_username?: string
  github_username?: string
  email?: string | null
  website_url?: string | null
  location?: string | null
  joined_at?: string
  profile_image?: string
  badge_ids?: number[]
}

export interface MyUser {
  type_of?: string
  id?: number /* int64, precision limited to 2^53-1 */
  username?: string
  name?: string
  summary?: string | null
  twitter_username?: string
  github_username?: string
  email?: string | null
  website_url?: string | null
  location?: string | null
  joined_at?: string
  profile_image?: string
  badge_ids?: number[]
  followers_count?: number
}

export interface SharedPodcast {
  title?: string
  slug?: string
  image_url?: string
}

export interface Comment {
  type_of?: string
  id_code?: string
  created_at?: string /* date-time */
  image_url?: string
}

export interface UserInviteParam {
  email?: string
  name?: string | null
}

export interface Billboard {
  id?: number
  name: string
  body_markdown: string
  approved?: boolean
  published?: boolean
  expires_at?: string | null
  organization_id?: number | null
  creator_id?: number | null
  placement_area:
    | 'sidebar_left'
    | 'sidebar_left_2'
    | 'sidebar_right'
    | 'sidebar_right_second'
    | 'sidebar_right_third'
    | 'feed_first'
    | 'feed_second'
    | 'feed_third'
    | 'home_hero'
    | 'footer'
    | 'page_fixed_bottom'
    | 'post_fixed_bottom'
    | 'post_body_bottom'
    | 'post_sidebar'
    | 'post_comments'
    | 'post_comments_mid'
    | 'digest_first'
    | 'digest_second'
  tag_list?: string
  exclude_article_ids?: string | null
  audience_segment_id?: number
  audience_segment_type?:
    | 'manual'
    | 'trusted'
    | 'posted'
    | 'no_posts_yet'
    | 'dark_theme'
    | 'light_theme'
    | 'no_experience'
    | 'experience1'
    | 'experience2'
    | 'experience3'
    | 'experience4'
    | 'experience5'
  target_geolocations?: string[]
  display_to?: 'all' | 'logged_in' | 'logged_out'
  type_of?: 'in_house' | 'community' | 'external'
}

export interface Segment {
  id?: number
  type_of?: 'manual'
  user_count?: number
}

export interface SegmentUserIds {
  user_ids?: number[]
}

export interface AgentSessionIndex {
  id: number /* int64, precision limited to 2^53-1 */
  slug: string
  title: string
  tool_name: string
  total_messages: number
  published: boolean
  created_at: string /* date-time */
  updated_at?: string /* date-time */
  url: string
}

export interface AgentSessionShow {
  id: number /* int64, precision limited to 2^53-1 */
  slug: string
  title: string
  tool_name: string
  total_messages: number
  curated_count: number
  published: boolean
  metadata?: Record<string, unknown> | null
  messages: Record<string, unknown>[]
  slices: Record<string, unknown>[]
  created_at: string /* date-time */
  updated_at: string /* date-time */
  url: string
}

export interface PollOption {
  type_of: 'poll_option'
  id: number /* int64, precision limited to 2^53-1 */
  markdown: string | null
  processed_html: string | null
  position: number
  poll_votes_count: number
  supplementary_text?: string | null
}

export interface Poll {
  type_of: 'poll'
  id: number /* int64, precision limited to 2^53-1 */
  prompt_markdown: string | null
  prompt_html: string | null
  poll_type_of: 'single_choice' | 'multiple_choice' | 'scale' | 'text_input'
  position: number
  poll_votes_count: number
  poll_skips_count: number
  poll_options_count: number
  scale_min?: number | null
  scale_max?: number | null
  created_at: string /* date-time */
  updated_at: string /* date-time */
  poll_options: PollOption[]
}

export interface Survey {
  type_of: 'survey'
  id: number /* int64, precision limited to 2^53-1 */
  title: string
  slug: string
  survey_type_of: 'community_pulse' | 'industry' | 'fun'
  active?: boolean | null
  display_title: boolean
  allow_resubmission: boolean
  created_at: string /* date-time */
  updated_at: string /* date-time */
}

export type SurveyWithPolls = Survey & {
  polls: Poll[]
}

export interface PollVote {
  type_of: 'poll_vote'
  id: number /* int64, precision limited to 2^53-1 */
  poll_id: number /* int64, precision limited to 2^53-1 */
  poll_option_id: number /* int64, precision limited to 2^53-1 */
  user_id: number /* int64, precision limited to 2^53-1 */
  user_email: string
  session_start: number
  created_at: string /* date-time */
}

export interface PollTextResponse {
  type_of: 'poll_text_response'
  id: number /* int64, precision limited to 2^53-1 */
  poll_id: number /* int64, precision limited to 2^53-1 */
  user_id: number /* int64, precision limited to 2^53-1 */
  user_email: string
  text_content: string
  session_start: number
  created_at: string /* date-time */
}
