// This file is auto-generated by @codewithagents/openapi-react-query — do not edit

import {
  queryOptions,
  useQuery,
  type UseQueryOptions,
  useMutation,
  type UseMutationOptions,
} from '@tanstack/react-query'
import {
  createApiKeys,
  createAudiences,
  createAutomations,
  createAutomationsByAutomationIdStop,
  createBroadcasts,
  createBroadcastsByIdSend,
  createContactProperties,
  createContacts,
  createContactsByContactIdSegmentsBySegmentId,
  createDomains,
  createDomainsByDomainIdVerify,
  createEmails,
  createEmailsBatch,
  createEmailsByEmailIdCancel,
  createEvents,
  createEventsSend,
  createSegments,
  createTemplates,
  createTemplatesByIdDuplicate,
  createTemplatesByIdPublish,
  createTopics,
  createWebhooks,
  deleteApiKeysByApiKeyId,
  deleteAudiencesById,
  deleteAutomationsByAutomationId,
  deleteBroadcastsById,
  deleteContactPropertiesById,
  deleteContactsByContactIdSegmentsBySegmentId,
  deleteContactsById,
  deleteDomainsByDomainId,
  deleteEventsByIdentifier,
  deleteSegmentsById,
  deleteTemplatesById,
  deleteTopicsById,
  deleteWebhooksByWebhookId,
  getApiKeys,
  getAudiences,
  getAudiencesById,
  getAutomations,
  getAutomationsByAutomationId,
  getAutomationsByAutomationIdRuns,
  getAutomationsByAutomationIdRunsByRunId,
  getBroadcasts,
  getBroadcastsById,
  getContactProperties,
  getContactPropertiesById,
  getContacts,
  getContactsByContactIdSegments,
  getContactsByContactIdTopics,
  getContactsById,
  getDomains,
  getDomainsByDomainId,
  getEmails,
  getEmailsByEmailId,
  getEmailsByEmailIdAttachments,
  getEmailsByEmailIdAttachmentsByAttachmentId,
  getEmailsReceiving,
  getEmailsReceivingByEmailId,
  getEmailsReceivingByEmailIdAttachments,
  getEmailsReceivingByEmailIdAttachmentsByAttachmentId,
  getEvents,
  getEventsByIdentifier,
  getLogs,
  getLogsByLogId,
  getSegments,
  getSegmentsById,
  getTemplates,
  getTemplatesById,
  getTopics,
  getTopicsById,
  getWebhooks,
  getWebhooksByWebhookId,
  patchAutomationsByAutomationId,
  patchBroadcastsById,
  patchContactPropertiesById,
  patchContactsByContactIdTopics,
  patchContactsById,
  patchDomainsByDomainId,
  patchEmailsByEmailId,
  patchEventsByIdentifier,
  patchTemplatesById,
  patchTopicsById,
  patchWebhooksByWebhookId,
  type ApiError,
} from './client.js'

// ── Query key factories ──────────────────────────────────────

export const emailKeys = {
  all: () => ['emails'] as const,
  getEmails: (params?: Parameters<typeof getEmails>[0]) => ['emails', 'getEmails', params] as const,
  getEmailsReceiving: (params?: Parameters<typeof getEmailsReceiving>[0]) =>
    ['emails', 'getEmailsReceiving', params] as const,
  getEmailsByEmailId: (emailId: string) => ['emails', 'getEmailsByEmailId', emailId] as const,
  getEmailsByEmailIdAttachments: (
    emailId: string,
    params?: Parameters<typeof getEmailsByEmailIdAttachments>[1]
  ) => ['emails', 'getEmailsByEmailIdAttachments', emailId, params] as const,
  getEmailsByEmailIdAttachmentsByAttachmentId: (emailId: string, attachmentId: string) =>
    ['emails', 'getEmailsByEmailIdAttachmentsByAttachmentId', emailId, attachmentId] as const,
  getEmailsReceivingByEmailId: (emailId: string) =>
    ['emails', 'getEmailsReceivingByEmailId', emailId] as const,
  getEmailsReceivingByEmailIdAttachments: (
    emailId: string,
    params?: Parameters<typeof getEmailsReceivingByEmailIdAttachments>[1]
  ) => ['emails', 'getEmailsReceivingByEmailIdAttachments', emailId, params] as const,
  getEmailsReceivingByEmailIdAttachmentsByAttachmentId: (emailId: string, attachmentId: string) =>
    [
      'emails',
      'getEmailsReceivingByEmailIdAttachmentsByAttachmentId',
      emailId,
      attachmentId,
    ] as const,
}

export const domainKeys = {
  all: () => ['domains'] as const,
  list: (params?: Parameters<typeof getDomains>[0]) => ['domains', 'list', params] as const,
  detail: (domainId: string) => ['domains', domainId] as const,
}

export const apiKeyKeys = {
  all: () => ['api-keys'] as const,
  list: (params?: Parameters<typeof getApiKeys>[0]) => ['api-keys', 'list', params] as const,
}

export const templateKeys = {
  all: () => ['templates'] as const,
  list: (params?: Parameters<typeof getTemplates>[0]) => ['templates', 'list', params] as const,
  detail: (id: string) => ['templates', id] as const,
}

export const audienceKeys = {
  all: () => ['audiences'] as const,
  list: () => ['audiences', 'list'] as const,
  detail: (id: string) => ['audiences', id] as const,
}

export const contactKeys = {
  all: () => ['contacts'] as const,
  list: (params?: Parameters<typeof getContacts>[0]) => ['contacts', 'list', params] as const,
  getContactsById: (id: string) => ['contacts', 'getContactsById', id] as const,
  getContactsByContactIdSegments: (
    contactId: string,
    params?: Parameters<typeof getContactsByContactIdSegments>[1]
  ) => ['contacts', 'getContactsByContactIdSegments', contactId, params] as const,
  getContactsByContactIdTopics: (
    contactId: string,
    params?: Parameters<typeof getContactsByContactIdTopics>[1]
  ) => ['contacts', 'getContactsByContactIdTopics', contactId, params] as const,
}

export const broadcastKeys = {
  all: () => ['broadcasts'] as const,
  list: (params?: Parameters<typeof getBroadcasts>[0]) => ['broadcasts', 'list', params] as const,
  detail: (id: string) => ['broadcasts', id] as const,
}

export const webhookKeys = {
  all: () => ['webhooks'] as const,
  list: (params?: Parameters<typeof getWebhooks>[0]) => ['webhooks', 'list', params] as const,
  detail: (webhookId: string) => ['webhooks', webhookId] as const,
}

export const segmentKeys = {
  all: () => ['segments'] as const,
  list: (params?: Parameters<typeof getSegments>[0]) => ['segments', 'list', params] as const,
  detail: (id: string) => ['segments', id] as const,
}

export const topicKeys = {
  all: () => ['topics'] as const,
  list: (params?: Parameters<typeof getTopics>[0]) => ['topics', 'list', params] as const,
  detail: (id: string) => ['topics', id] as const,
}

export const contactPropertieKeys = {
  all: () => ['contact-properties'] as const,
  list: (params?: Parameters<typeof getContactProperties>[0]) =>
    ['contact-properties', 'list', params] as const,
  detail: (id: string) => ['contact-properties', id] as const,
}

export const logKeys = {
  all: () => ['logs'] as const,
  list: (params?: Parameters<typeof getLogs>[0]) => ['logs', 'list', params] as const,
  detail: (logId: string) => ['logs', logId] as const,
}

export const automationKeys = {
  all: () => ['automations'] as const,
  list: (params?: Parameters<typeof getAutomations>[0]) => ['automations', 'list', params] as const,
  getAutomationsByAutomationId: (automationId: string) =>
    ['automations', 'getAutomationsByAutomationId', automationId] as const,
  getAutomationsByAutomationIdRuns: (
    automationId: string,
    params?: Parameters<typeof getAutomationsByAutomationIdRuns>[1]
  ) => ['automations', 'getAutomationsByAutomationIdRuns', automationId, params] as const,
  getAutomationsByAutomationIdRunsByRunId: (automationId: string, runId: string) =>
    ['automations', 'getAutomationsByAutomationIdRunsByRunId', automationId, runId] as const,
}

export const eventKeys = {
  all: () => ['events'] as const,
  list: (params?: Parameters<typeof getEvents>[0]) => ['events', 'list', params] as const,
  detail: (identifier: string) => ['events', identifier] as const,
}

// ── Query options factories ──────────────────────────────────

export function getEmailsQueryOptions(
  params?: Parameters<typeof getEmails>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmails>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmails>>, ApiError>({
    queryKey: emailKeys.getEmails(params),
    queryFn: () => getEmails(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsByEmailIdQueryOptions(
  emailId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsByEmailId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmailsByEmailId>>, ApiError>({
    queryKey: emailKeys.getEmailsByEmailId(emailId),
    queryFn: () => getEmailsByEmailId(emailId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsByEmailIdAttachmentsQueryOptions(
  emailId: string,
  params?: Parameters<typeof getEmailsByEmailIdAttachments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsByEmailIdAttachments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmailsByEmailIdAttachments>>, ApiError>({
    queryKey: emailKeys.getEmailsByEmailIdAttachments(emailId, params),
    queryFn: () => getEmailsByEmailIdAttachments(emailId, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsByEmailIdAttachmentsByAttachmentIdQueryOptions(
  emailId: string,
  attachmentId: string,
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEmailsByEmailIdAttachmentsByAttachmentId>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getEmailsByEmailIdAttachmentsByAttachmentId>>,
    ApiError
  >({
    queryKey: emailKeys.getEmailsByEmailIdAttachmentsByAttachmentId(emailId, attachmentId),
    queryFn: () => getEmailsByEmailIdAttachmentsByAttachmentId(emailId, attachmentId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsReceivingQueryOptions(
  params?: Parameters<typeof getEmailsReceiving>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceiving>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmailsReceiving>>, ApiError>({
    queryKey: emailKeys.getEmailsReceiving(params),
    queryFn: () => getEmailsReceiving(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsReceivingByEmailIdQueryOptions(
  emailId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailId>>, ApiError>({
    queryKey: emailKeys.getEmailsReceivingByEmailId(emailId),
    queryFn: () => getEmailsReceivingByEmailId(emailId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEmailsReceivingByEmailIdAttachmentsQueryOptions(
  emailId: string,
  params?: Parameters<typeof getEmailsReceivingByEmailIdAttachments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachments>>, ApiError>(
    {
      queryKey: emailKeys.getEmailsReceivingByEmailIdAttachments(emailId, params),
      queryFn: () => getEmailsReceivingByEmailIdAttachments(emailId, params),
      staleTime: 0,
      gcTime: 300000,
      ...options,
    }
  )
}

export function getEmailsReceivingByEmailIdAttachmentsByAttachmentIdQueryOptions(
  emailId: string,
  attachmentId: string,
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachmentsByAttachmentId>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachmentsByAttachmentId>>,
    ApiError
  >({
    queryKey: emailKeys.getEmailsReceivingByEmailIdAttachmentsByAttachmentId(emailId, attachmentId),
    queryFn: () => getEmailsReceivingByEmailIdAttachmentsByAttachmentId(emailId, attachmentId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDomainsQueryOptions(
  params?: Parameters<typeof getDomains>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDomains>>, ApiError>({
    queryKey: domainKeys.list(params),
    queryFn: () => getDomains(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDomainsByDomainIdQueryOptions(
  domainId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDomainsByDomainId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDomainsByDomainId>>, ApiError>({
    queryKey: domainKeys.detail(domainId),
    queryFn: () => getDomainsByDomainId(domainId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getApiKeysQueryOptions(
  params?: Parameters<typeof getApiKeys>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getApiKeys>>, ApiError>({
    queryKey: apiKeyKeys.list(params),
    queryFn: () => getApiKeys(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTemplatesQueryOptions(
  params?: Parameters<typeof getTemplates>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTemplates>>, ApiError>({
    queryKey: templateKeys.list(params),
    queryFn: () => getTemplates(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTemplatesByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTemplatesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTemplatesById>>, ApiError>({
    queryKey: templateKeys.detail(id),
    queryFn: () => getTemplatesById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

/** @deprecated */
export function getAudiencesQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAudiences>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getAudiences>>, ApiError>({
    queryKey: audienceKeys.list(),
    queryFn: () => getAudiences(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

/** @deprecated */
export function getAudiencesByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAudiencesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getAudiencesById>>, ApiError>({
    queryKey: audienceKeys.detail(id),
    queryFn: () => getAudiencesById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactsQueryOptions(
  params?: Parameters<typeof getContacts>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContacts>>, ApiError>({
    queryKey: contactKeys.list(params),
    queryFn: () => getContacts(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactsByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContactsById>>, ApiError>({
    queryKey: contactKeys.getContactsById(id),
    queryFn: () => getContactsById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getBroadcastsQueryOptions(
  params?: Parameters<typeof getBroadcasts>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBroadcasts>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getBroadcasts>>, ApiError>({
    queryKey: broadcastKeys.list(params),
    queryFn: () => getBroadcasts(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getBroadcastsByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBroadcastsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getBroadcastsById>>, ApiError>({
    queryKey: broadcastKeys.detail(id),
    queryFn: () => getBroadcastsById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getWebhooksQueryOptions(
  params?: Parameters<typeof getWebhooks>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getWebhooks>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getWebhooks>>, ApiError>({
    queryKey: webhookKeys.list(params),
    queryFn: () => getWebhooks(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getWebhooksByWebhookIdQueryOptions(
  webhookId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getWebhooksByWebhookId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getWebhooksByWebhookId>>, ApiError>({
    queryKey: webhookKeys.detail(webhookId),
    queryFn: () => getWebhooksByWebhookId(webhookId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getSegmentsQueryOptions(
  params?: Parameters<typeof getSegments>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getSegments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getSegments>>, ApiError>({
    queryKey: segmentKeys.list(params),
    queryFn: () => getSegments(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getSegmentsByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getSegmentsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getSegmentsById>>, ApiError>({
    queryKey: segmentKeys.detail(id),
    queryFn: () => getSegmentsById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTopicsQueryOptions(
  params?: Parameters<typeof getTopics>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTopics>>, ApiError>({
    queryKey: topicKeys.list(params),
    queryFn: () => getTopics(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTopicsByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTopicsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTopicsById>>, ApiError>({
    queryKey: topicKeys.detail(id),
    queryFn: () => getTopicsById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactPropertiesQueryOptions(
  params?: Parameters<typeof getContactProperties>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactProperties>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContactProperties>>, ApiError>({
    queryKey: contactPropertieKeys.list(params),
    queryFn: () => getContactProperties(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactPropertiesByIdQueryOptions(
  id: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactPropertiesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContactPropertiesById>>, ApiError>({
    queryKey: contactPropertieKeys.detail(id),
    queryFn: () => getContactPropertiesById(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactsByContactIdSegmentsQueryOptions(
  contactId: string,
  params?: Parameters<typeof getContactsByContactIdSegments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsByContactIdSegments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContactsByContactIdSegments>>, ApiError>({
    queryKey: contactKeys.getContactsByContactIdSegments(contactId, params),
    queryFn: () => getContactsByContactIdSegments(contactId, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getContactsByContactIdTopicsQueryOptions(
  contactId: string,
  params?: Parameters<typeof getContactsByContactIdTopics>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsByContactIdTopics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getContactsByContactIdTopics>>, ApiError>({
    queryKey: contactKeys.getContactsByContactIdTopics(contactId, params),
    queryFn: () => getContactsByContactIdTopics(contactId, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLogsQueryOptions(
  params?: Parameters<typeof getLogs>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLogs>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLogs>>, ApiError>({
    queryKey: logKeys.list(params),
    queryFn: () => getLogs(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLogsByLogIdQueryOptions(
  logId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLogsByLogId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLogsByLogId>>, ApiError>({
    queryKey: logKeys.detail(logId),
    queryFn: () => getLogsByLogId(logId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getAutomationsQueryOptions(
  params?: Parameters<typeof getAutomations>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomations>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getAutomations>>, ApiError>({
    queryKey: automationKeys.list(params),
    queryFn: () => getAutomations(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getAutomationsByAutomationIdQueryOptions(
  automationId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationId>>, ApiError>({
    queryKey: automationKeys.getAutomationsByAutomationId(automationId),
    queryFn: () => getAutomationsByAutomationId(automationId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getAutomationsByAutomationIdRunsQueryOptions(
  automationId: string,
  params?: Parameters<typeof getAutomationsByAutomationIdRuns>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationIdRuns>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationIdRuns>>, ApiError>({
    queryKey: automationKeys.getAutomationsByAutomationIdRuns(automationId, params),
    queryFn: () => getAutomationsByAutomationIdRuns(automationId, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getAutomationsByAutomationIdRunsByRunIdQueryOptions(
  automationId: string,
  runId: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationIdRunsByRunId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getAutomationsByAutomationIdRunsByRunId>>,
    ApiError
  >({
    queryKey: automationKeys.getAutomationsByAutomationIdRunsByRunId(automationId, runId),
    queryFn: () => getAutomationsByAutomationIdRunsByRunId(automationId, runId),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEventsQueryOptions(
  params?: Parameters<typeof getEvents>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEvents>>, ApiError>({
    queryKey: eventKeys.list(params),
    queryFn: () => getEvents(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getEventsByIdentifierQueryOptions(
  identifier: string,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEventsByIdentifier>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getEventsByIdentifier>>, ApiError>({
    queryKey: eventKeys.detail(identifier),
    queryFn: () => getEventsByIdentifier(identifier),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Queries ──────────────────────────────────────────────────

export function useGetEmails(
  params?: Parameters<typeof getEmails>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmails>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmails>>, ApiError>({
    queryKey: emailKeys.getEmails(params),
    queryFn: () => getEmails(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetEmailsByEmailId(
  emailId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsByEmailId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmailsByEmailId>>, ApiError>({
    queryKey: emailKeys.getEmailsByEmailId(emailId!),
    queryFn: () => getEmailsByEmailId(emailId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEmailsByEmailIdAttachments(
  emailId: string | undefined | null,
  params?: Parameters<typeof getEmailsByEmailIdAttachments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsByEmailIdAttachments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmailsByEmailIdAttachments>>, ApiError>({
    queryKey: emailKeys.getEmailsByEmailIdAttachments(emailId!, params),
    queryFn: () => getEmailsByEmailIdAttachments(emailId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEmailsByEmailIdAttachmentsByAttachmentId(
  emailId: string | undefined | null,
  attachmentId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEmailsByEmailIdAttachmentsByAttachmentId>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<
    Awaited<ReturnType<typeof getEmailsByEmailIdAttachmentsByAttachmentId>>,
    ApiError
  >({
    queryKey: emailKeys.getEmailsByEmailIdAttachmentsByAttachmentId(emailId!, attachmentId!),
    queryFn: () => getEmailsByEmailIdAttachmentsByAttachmentId(emailId!, attachmentId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && attachmentId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEmailsReceiving(
  params?: Parameters<typeof getEmailsReceiving>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceiving>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmailsReceiving>>, ApiError>({
    queryKey: emailKeys.getEmailsReceiving(params),
    queryFn: () => getEmailsReceiving(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetEmailsReceivingByEmailId(
  emailId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmailsReceivingByEmailId>>, ApiError>({
    queryKey: emailKeys.getEmailsReceivingByEmailId(emailId!),
    queryFn: () => getEmailsReceivingByEmailId(emailId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEmailsReceivingByEmailIdAttachments(
  emailId: string | undefined | null,
  params?: Parameters<typeof getEmailsReceivingByEmailIdAttachments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachments>>, ApiError>({
    queryKey: emailKeys.getEmailsReceivingByEmailIdAttachments(emailId!, params),
    queryFn: () => getEmailsReceivingByEmailIdAttachments(emailId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEmailsReceivingByEmailIdAttachmentsByAttachmentId(
  emailId: string | undefined | null,
  attachmentId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachmentsByAttachmentId>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<
    Awaited<ReturnType<typeof getEmailsReceivingByEmailIdAttachmentsByAttachmentId>>,
    ApiError
  >({
    queryKey: emailKeys.getEmailsReceivingByEmailIdAttachmentsByAttachmentId(
      emailId!,
      attachmentId!
    ),
    queryFn: () => getEmailsReceivingByEmailIdAttachmentsByAttachmentId(emailId!, attachmentId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: emailId != null && attachmentId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDomains(
  params?: Parameters<typeof getDomains>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDomains>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDomains>>, ApiError>({
    queryKey: domainKeys.list(params),
    queryFn: () => getDomains(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetDomainsByDomainId(
  domainId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDomainsByDomainId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDomainsByDomainId>>, ApiError>({
    queryKey: domainKeys.detail(domainId!),
    queryFn: () => getDomainsByDomainId(domainId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: domainId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetApiKeys(
  params?: Parameters<typeof getApiKeys>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getApiKeys>>, ApiError>({
    queryKey: apiKeyKeys.list(params),
    queryFn: () => getApiKeys(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTemplates(
  params?: Parameters<typeof getTemplates>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTemplates>>, ApiError>({
    queryKey: templateKeys.list(params),
    queryFn: () => getTemplates(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTemplatesById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTemplatesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTemplatesById>>, ApiError>({
    queryKey: templateKeys.detail(id!),
    queryFn: () => getTemplatesById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

/** @deprecated */
export function useGetAudiences(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAudiences>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAudiences>>, ApiError>({
    queryKey: audienceKeys.list(),
    queryFn: () => getAudiences(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

/** @deprecated */
export function useGetAudiencesById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAudiencesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAudiencesById>>, ApiError>({
    queryKey: audienceKeys.detail(id!),
    queryFn: () => getAudiencesById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetContacts(
  params?: Parameters<typeof getContacts>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContacts>>, ApiError>({
    queryKey: contactKeys.list(params),
    queryFn: () => getContacts(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetContactsById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContactsById>>, ApiError>({
    queryKey: contactKeys.getContactsById(id!),
    queryFn: () => getContactsById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetBroadcasts(
  params?: Parameters<typeof getBroadcasts>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBroadcasts>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getBroadcasts>>, ApiError>({
    queryKey: broadcastKeys.list(params),
    queryFn: () => getBroadcasts(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetBroadcastsById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBroadcastsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getBroadcastsById>>, ApiError>({
    queryKey: broadcastKeys.detail(id!),
    queryFn: () => getBroadcastsById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetWebhooks(
  params?: Parameters<typeof getWebhooks>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getWebhooks>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getWebhooks>>, ApiError>({
    queryKey: webhookKeys.list(params),
    queryFn: () => getWebhooks(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetWebhooksByWebhookId(
  webhookId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getWebhooksByWebhookId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getWebhooksByWebhookId>>, ApiError>({
    queryKey: webhookKeys.detail(webhookId!),
    queryFn: () => getWebhooksByWebhookId(webhookId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: webhookId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetSegments(
  params?: Parameters<typeof getSegments>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getSegments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getSegments>>, ApiError>({
    queryKey: segmentKeys.list(params),
    queryFn: () => getSegments(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetSegmentsById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getSegmentsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getSegmentsById>>, ApiError>({
    queryKey: segmentKeys.detail(id!),
    queryFn: () => getSegmentsById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetTopics(
  params?: Parameters<typeof getTopics>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTopics>>, ApiError>({
    queryKey: topicKeys.list(params),
    queryFn: () => getTopics(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTopicsById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTopicsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTopicsById>>, ApiError>({
    queryKey: topicKeys.detail(id!),
    queryFn: () => getTopicsById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetContactProperties(
  params?: Parameters<typeof getContactProperties>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactProperties>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContactProperties>>, ApiError>({
    queryKey: contactPropertieKeys.list(params),
    queryFn: () => getContactProperties(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetContactPropertiesById(
  id: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactPropertiesById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContactPropertiesById>>, ApiError>({
    queryKey: contactPropertieKeys.detail(id!),
    queryFn: () => getContactPropertiesById(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetContactsByContactIdSegments(
  contactId: string | undefined | null,
  params?: Parameters<typeof getContactsByContactIdSegments>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsByContactIdSegments>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContactsByContactIdSegments>>, ApiError>({
    queryKey: contactKeys.getContactsByContactIdSegments(contactId!, params),
    queryFn: () => getContactsByContactIdSegments(contactId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: contactId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetContactsByContactIdTopics(
  contactId: string | undefined | null,
  params?: Parameters<typeof getContactsByContactIdTopics>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getContactsByContactIdTopics>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getContactsByContactIdTopics>>, ApiError>({
    queryKey: contactKeys.getContactsByContactIdTopics(contactId!, params),
    queryFn: () => getContactsByContactIdTopics(contactId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: contactId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLogs(
  params?: Parameters<typeof getLogs>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLogs>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLogs>>, ApiError>({
    queryKey: logKeys.list(params),
    queryFn: () => getLogs(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetLogsByLogId(
  logId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLogsByLogId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLogsByLogId>>, ApiError>({
    queryKey: logKeys.detail(logId!),
    queryFn: () => getLogsByLogId(logId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: logId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetAutomations(
  params?: Parameters<typeof getAutomations>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomations>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAutomations>>, ApiError>({
    queryKey: automationKeys.list(params),
    queryFn: () => getAutomations(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetAutomationsByAutomationId(
  automationId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAutomationsByAutomationId>>, ApiError>({
    queryKey: automationKeys.getAutomationsByAutomationId(automationId!),
    queryFn: () => getAutomationsByAutomationId(automationId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: automationId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetAutomationsByAutomationIdRuns(
  automationId: string | undefined | null,
  params?: Parameters<typeof getAutomationsByAutomationIdRuns>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationIdRuns>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAutomationsByAutomationIdRuns>>, ApiError>({
    queryKey: automationKeys.getAutomationsByAutomationIdRuns(automationId!, params),
    queryFn: () => getAutomationsByAutomationIdRuns(automationId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: automationId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetAutomationsByAutomationIdRunsByRunId(
  automationId: string | undefined | null,
  runId: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getAutomationsByAutomationIdRunsByRunId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getAutomationsByAutomationIdRunsByRunId>>, ApiError>({
    queryKey: automationKeys.getAutomationsByAutomationIdRunsByRunId(automationId!, runId!),
    queryFn: () => getAutomationsByAutomationIdRunsByRunId(automationId!, runId!),
    staleTime: 0,
    gcTime: 300000,
    enabled: automationId != null && runId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetEvents(
  params?: Parameters<typeof getEvents>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEvents>>, ApiError>({
    queryKey: eventKeys.list(params),
    queryFn: () => getEvents(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetEventsByIdentifier(
  identifier: string | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getEventsByIdentifier>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getEventsByIdentifier>>, ApiError>({
    queryKey: eventKeys.detail(identifier!),
    queryFn: () => getEventsByIdentifier(identifier!),
    staleTime: 0,
    gcTime: 300000,
    enabled: identifier != null && (options?.enabled ?? true),
    ...options,
  })
}

// ── Mutations ────────────────────────────────────────────────

export function useCreateEmails(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createEmails>>,
      ApiError,
      { body: Parameters<typeof createEmails>[0]; params: Parameters<typeof createEmails>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createEmails>>,
    ApiError,
    { body: Parameters<typeof createEmails>[0]; params: Parameters<typeof createEmails>[1] }
  >({
    mutationFn: ({ body, params }) => createEmails(body, params),
    ...options,
  })
}

export function usePatchEmailsByEmailId(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof patchEmailsByEmailId>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof patchEmailsByEmailId>>, ApiError, string>({
    mutationFn: (emailId) => patchEmailsByEmailId(emailId),
    ...options,
  })
}

export function useCreateEmailsByEmailIdCancel(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof createEmailsByEmailIdCancel>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof createEmailsByEmailIdCancel>>, ApiError, string>({
    mutationFn: (emailId) => createEmailsByEmailIdCancel(emailId),
    ...options,
  })
}

export function useCreateEmailsBatch(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createEmailsBatch>>,
      ApiError,
      {
        body: Parameters<typeof createEmailsBatch>[0]
        params: Parameters<typeof createEmailsBatch>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createEmailsBatch>>,
    ApiError,
    {
      body: Parameters<typeof createEmailsBatch>[0]
      params: Parameters<typeof createEmailsBatch>[1]
    }
  >({
    mutationFn: ({ body, params }) => createEmailsBatch(body, params),
    ...options,
  })
}

export function useCreateDomains(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createDomains>>,
      ApiError,
      Parameters<typeof createDomains>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createDomains>>,
    ApiError,
    Parameters<typeof createDomains>[0]
  >({
    mutationFn: (vars) => createDomains(vars),
    ...options,
  })
}

export function usePatchDomainsByDomainId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchDomainsByDomainId>>,
      ApiError,
      { domainId: string; body: Parameters<typeof patchDomainsByDomainId>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchDomainsByDomainId>>,
    ApiError,
    { domainId: string; body: Parameters<typeof patchDomainsByDomainId>[1] }
  >({
    mutationFn: ({ domainId, body }) => patchDomainsByDomainId(domainId, body),
    ...options,
  })
}

export function useDeleteDomainsByDomainId(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteDomainsByDomainId>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteDomainsByDomainId>>, ApiError, string>({
    mutationFn: (domainId) => deleteDomainsByDomainId(domainId),
    ...options,
  })
}

export function useCreateDomainsByDomainIdVerify(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof createDomainsByDomainIdVerify>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof createDomainsByDomainIdVerify>>, ApiError, string>({
    mutationFn: (domainId) => createDomainsByDomainIdVerify(domainId),
    ...options,
  })
}

export function useCreateApiKeys(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createApiKeys>>,
      ApiError,
      Parameters<typeof createApiKeys>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createApiKeys>>,
    ApiError,
    Parameters<typeof createApiKeys>[0]
  >({
    mutationFn: (vars) => createApiKeys(vars),
    ...options,
  })
}

export function useDeleteApiKeysByApiKeyId(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysByApiKeyId>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteApiKeysByApiKeyId>>, ApiError, string>({
    mutationFn: (apiKeyId) => deleteApiKeysByApiKeyId(apiKeyId),
    ...options,
  })
}

export function useCreateTemplates(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createTemplates>>,
      ApiError,
      Parameters<typeof createTemplates>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createTemplates>>,
    ApiError,
    Parameters<typeof createTemplates>[0]
  >({
    mutationFn: (vars) => createTemplates(vars),
    ...options,
  })
}

export function usePatchTemplatesById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchTemplatesById>>,
      ApiError,
      { id: string; body: Parameters<typeof patchTemplatesById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchTemplatesById>>,
    ApiError,
    { id: string; body: Parameters<typeof patchTemplatesById>[1] }
  >({
    mutationFn: ({ id, body }) => patchTemplatesById(id, body),
    ...options,
  })
}

export function useDeleteTemplatesById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteTemplatesById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteTemplatesById>>, ApiError, string>({
    mutationFn: (id) => deleteTemplatesById(id),
    ...options,
  })
}

export function useCreateTemplatesByIdPublish(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof createTemplatesByIdPublish>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof createTemplatesByIdPublish>>, ApiError, string>({
    mutationFn: (id) => createTemplatesByIdPublish(id),
    ...options,
  })
}

export function useCreateTemplatesByIdDuplicate(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof createTemplatesByIdDuplicate>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof createTemplatesByIdDuplicate>>, ApiError, string>({
    mutationFn: (id) => createTemplatesByIdDuplicate(id),
    ...options,
  })
}

/** @deprecated */
export function useCreateAudiences(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createAudiences>>,
      ApiError,
      Parameters<typeof createAudiences>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createAudiences>>,
    ApiError,
    Parameters<typeof createAudiences>[0]
  >({
    mutationFn: (vars) => createAudiences(vars),
    ...options,
  })
}

/** @deprecated */
export function useDeleteAudiencesById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteAudiencesById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteAudiencesById>>, ApiError, string>({
    mutationFn: (id) => deleteAudiencesById(id),
    ...options,
  })
}

export function useCreateContacts(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createContacts>>,
      ApiError,
      Parameters<typeof createContacts>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createContacts>>,
    ApiError,
    Parameters<typeof createContacts>[0]
  >({
    mutationFn: (vars) => createContacts(vars),
    ...options,
  })
}

export function usePatchContactsById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchContactsById>>,
      ApiError,
      { id: string; body: Parameters<typeof patchContactsById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchContactsById>>,
    ApiError,
    { id: string; body: Parameters<typeof patchContactsById>[1] }
  >({
    mutationFn: ({ id, body }) => patchContactsById(id, body),
    ...options,
  })
}

export function useDeleteContactsById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteContactsById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteContactsById>>, ApiError, string>({
    mutationFn: (id) => deleteContactsById(id),
    ...options,
  })
}

export function useCreateBroadcasts(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createBroadcasts>>,
      ApiError,
      Parameters<typeof createBroadcasts>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createBroadcasts>>,
    ApiError,
    Parameters<typeof createBroadcasts>[0]
  >({
    mutationFn: (vars) => createBroadcasts(vars),
    ...options,
  })
}

export function usePatchBroadcastsById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchBroadcastsById>>,
      ApiError,
      { id: string; body: Parameters<typeof patchBroadcastsById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchBroadcastsById>>,
    ApiError,
    { id: string; body: Parameters<typeof patchBroadcastsById>[1] }
  >({
    mutationFn: ({ id, body }) => patchBroadcastsById(id, body),
    ...options,
  })
}

export function useDeleteBroadcastsById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteBroadcastsById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteBroadcastsById>>, ApiError, string>({
    mutationFn: (id) => deleteBroadcastsById(id),
    ...options,
  })
}

export function useCreateBroadcastsByIdSend(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createBroadcastsByIdSend>>,
      ApiError,
      { id: string; body: Parameters<typeof createBroadcastsByIdSend>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createBroadcastsByIdSend>>,
    ApiError,
    { id: string; body: Parameters<typeof createBroadcastsByIdSend>[1] }
  >({
    mutationFn: ({ id, body }) => createBroadcastsByIdSend(id, body),
    ...options,
  })
}

export function useCreateWebhooks(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createWebhooks>>,
      ApiError,
      Parameters<typeof createWebhooks>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createWebhooks>>,
    ApiError,
    Parameters<typeof createWebhooks>[0]
  >({
    mutationFn: (vars) => createWebhooks(vars),
    ...options,
  })
}

export function usePatchWebhooksByWebhookId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchWebhooksByWebhookId>>,
      ApiError,
      { webhookId: string; body: Parameters<typeof patchWebhooksByWebhookId>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchWebhooksByWebhookId>>,
    ApiError,
    { webhookId: string; body: Parameters<typeof patchWebhooksByWebhookId>[1] }
  >({
    mutationFn: ({ webhookId, body }) => patchWebhooksByWebhookId(webhookId, body),
    ...options,
  })
}

export function useDeleteWebhooksByWebhookId(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteWebhooksByWebhookId>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteWebhooksByWebhookId>>, ApiError, string>({
    mutationFn: (webhookId) => deleteWebhooksByWebhookId(webhookId),
    ...options,
  })
}

export function useCreateSegments(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createSegments>>,
      ApiError,
      Parameters<typeof createSegments>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createSegments>>,
    ApiError,
    Parameters<typeof createSegments>[0]
  >({
    mutationFn: (vars) => createSegments(vars),
    ...options,
  })
}

export function useDeleteSegmentsById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteSegmentsById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteSegmentsById>>, ApiError, string>({
    mutationFn: (id) => deleteSegmentsById(id),
    ...options,
  })
}

export function useCreateTopics(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createTopics>>,
      ApiError,
      Parameters<typeof createTopics>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createTopics>>,
    ApiError,
    Parameters<typeof createTopics>[0]
  >({
    mutationFn: (vars) => createTopics(vars),
    ...options,
  })
}

export function usePatchTopicsById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchTopicsById>>,
      ApiError,
      { id: string; body: Parameters<typeof patchTopicsById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchTopicsById>>,
    ApiError,
    { id: string; body: Parameters<typeof patchTopicsById>[1] }
  >({
    mutationFn: ({ id, body }) => patchTopicsById(id, body),
    ...options,
  })
}

export function useDeleteTopicsById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteTopicsById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteTopicsById>>, ApiError, string>({
    mutationFn: (id) => deleteTopicsById(id),
    ...options,
  })
}

export function useCreateContactProperties(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createContactProperties>>,
      ApiError,
      Parameters<typeof createContactProperties>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createContactProperties>>,
    ApiError,
    Parameters<typeof createContactProperties>[0]
  >({
    mutationFn: (vars) => createContactProperties(vars),
    ...options,
  })
}

export function usePatchContactPropertiesById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchContactPropertiesById>>,
      ApiError,
      { id: string; body: Parameters<typeof patchContactPropertiesById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchContactPropertiesById>>,
    ApiError,
    { id: string; body: Parameters<typeof patchContactPropertiesById>[1] }
  >({
    mutationFn: ({ id, body }) => patchContactPropertiesById(id, body),
    ...options,
  })
}

export function useDeleteContactPropertiesById(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteContactPropertiesById>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteContactPropertiesById>>, ApiError, string>({
    mutationFn: (id) => deleteContactPropertiesById(id),
    ...options,
  })
}

export function useCreateContactsByContactIdSegmentsBySegmentId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createContactsByContactIdSegmentsBySegmentId>>,
      ApiError,
      { contactId: string; segmentId: string }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createContactsByContactIdSegmentsBySegmentId>>,
    ApiError,
    { contactId: string; segmentId: string }
  >({
    mutationFn: ({ contactId, segmentId }) =>
      createContactsByContactIdSegmentsBySegmentId(contactId, segmentId),
    ...options,
  })
}

export function useDeleteContactsByContactIdSegmentsBySegmentId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteContactsByContactIdSegmentsBySegmentId>>,
      ApiError,
      { contactId: string; segmentId: string }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteContactsByContactIdSegmentsBySegmentId>>,
    ApiError,
    { contactId: string; segmentId: string }
  >({
    mutationFn: ({ contactId, segmentId }) =>
      deleteContactsByContactIdSegmentsBySegmentId(contactId, segmentId),
    ...options,
  })
}

export function usePatchContactsByContactIdTopics(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchContactsByContactIdTopics>>,
      ApiError,
      { contactId: string; body: Parameters<typeof patchContactsByContactIdTopics>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchContactsByContactIdTopics>>,
    ApiError,
    { contactId: string; body: Parameters<typeof patchContactsByContactIdTopics>[1] }
  >({
    mutationFn: ({ contactId, body }) => patchContactsByContactIdTopics(contactId, body),
    ...options,
  })
}

export function useCreateAutomations(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createAutomations>>,
      ApiError,
      Parameters<typeof createAutomations>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createAutomations>>,
    ApiError,
    Parameters<typeof createAutomations>[0]
  >({
    mutationFn: (vars) => createAutomations(vars),
    ...options,
  })
}

export function usePatchAutomationsByAutomationId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchAutomationsByAutomationId>>,
      ApiError,
      { automationId: string; body: Parameters<typeof patchAutomationsByAutomationId>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchAutomationsByAutomationId>>,
    ApiError,
    { automationId: string; body: Parameters<typeof patchAutomationsByAutomationId>[1] }
  >({
    mutationFn: ({ automationId, body }) => patchAutomationsByAutomationId(automationId, body),
    ...options,
  })
}

export function useDeleteAutomationsByAutomationId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteAutomationsByAutomationId>>,
      ApiError,
      string
    >,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteAutomationsByAutomationId>>, ApiError, string>(
    {
      mutationFn: (automationId) => deleteAutomationsByAutomationId(automationId),
      ...options,
    }
  )
}

export function useCreateAutomationsByAutomationIdStop(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createAutomationsByAutomationIdStop>>,
      ApiError,
      string
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createAutomationsByAutomationIdStop>>,
    ApiError,
    string
  >({
    mutationFn: (automationId) => createAutomationsByAutomationIdStop(automationId),
    ...options,
  })
}

export function useCreateEvents(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createEvents>>,
      ApiError,
      Parameters<typeof createEvents>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createEvents>>,
    ApiError,
    Parameters<typeof createEvents>[0]
  >({
    mutationFn: (vars) => createEvents(vars),
    ...options,
  })
}

export function useCreateEventsSend(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createEventsSend>>,
      ApiError,
      Parameters<typeof createEventsSend>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createEventsSend>>,
    ApiError,
    Parameters<typeof createEventsSend>[0]
  >({
    mutationFn: (vars) => createEventsSend(vars),
    ...options,
  })
}

export function usePatchEventsByIdentifier(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchEventsByIdentifier>>,
      ApiError,
      { identifier: string; body: Parameters<typeof patchEventsByIdentifier>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchEventsByIdentifier>>,
    ApiError,
    { identifier: string; body: Parameters<typeof patchEventsByIdentifier>[1] }
  >({
    mutationFn: ({ identifier, body }) => patchEventsByIdentifier(identifier, body),
    ...options,
  })
}

export function useDeleteEventsByIdentifier(
  options?: Omit<
    UseMutationOptions<Awaited<ReturnType<typeof deleteEventsByIdentifier>>, ApiError, string>,
    'mutationFn'
  >
) {
  return useMutation<Awaited<ReturnType<typeof deleteEventsByIdentifier>>, ApiError, string>({
    mutationFn: (identifier) => deleteEventsByIdentifier(identifier),
    ...options,
  })
}
