// This file is auto-generated by openapi-zod-ts - do not edit

export interface SendEmailRequest {
  from: string
  to: string | string[]
  subject: string
  bcc?: string | string[]
  cc?: string | string[]
  reply_to?: string | string[]
  html?: string
  text?: string
  template?: EmailTemplateInput & unknown
  headers?: Record<string, unknown>
  scheduled_at?: string
  attachments?: Attachment[]
  tags?: Tag[]
  topic_id?: string
}

export interface Attachment {
  content?: string
  filename?: string
  path?: string
  content_type?: string
  content_id?: string
}

export interface Tag {
  name?: string
  value?: string
}

export interface EmailTemplateInput {
  id: string
  variables?: Record<string, string | number>
}

export interface SendEmailResponse {
  id?: string
}

export interface UpdateEmailOptions {
  scheduled_at?: string
}

export interface Email {
  object?: string
  id?: string
  to?: string[]
  from?: string
  created_at?: string /* date-time */
  subject?: string
  html?: string
  text?: string
  bcc?: string[]
  cc?: string[]
  reply_to?: string[]
  last_event?:
    | 'bounced'
    | 'canceled'
    | 'clicked'
    | 'complained'
    | 'delivered'
    | 'delivery_delayed'
    | 'failed'
    | 'opened'
    | 'queued'
    | 'scheduled'
    | 'sent'
    | 'suppressed'
}

export interface ListEmailsResponse {
  object?: string
  has_more?: boolean
  data?: Email[]
}

export interface CreateBatchEmailsResponse {
  data?: {
    id?: string
  }[]
}

export interface DomainCapabilities {
  sending?: 'enabled' | 'disabled'
  receiving?: 'enabled' | 'disabled'
}

export interface CreateDomainRequest {
  name: string
  region?: 'us-east-1' | 'eu-west-1' | 'sa-east-1' | 'ap-northeast-1'
  custom_return_path?: string
  open_tracking?: boolean
  click_tracking?: boolean
  tls?: 'opportunistic' | 'enforced'
  capabilities?: DomainCapabilities
  tracking_subdomain?: string
}

export interface CreateDomainResponse {
  id?: string
  name?: string
  created_at?: string /* date-time */
  status?:
    | 'pending'
    | 'verified'
    | 'failed'
    | 'not_started'
    | 'partially_verified'
    | 'partially_failed'
  capabilities?: DomainCapabilities
  records?: DomainRecord[]
  region?: string
  open_tracking?: boolean
  click_tracking?: boolean
  tracking_subdomain?: string
}

export interface UpdateDomainOptions {
  open_tracking?: boolean
  click_tracking?: boolean
  tls?: string
  capabilities?: DomainCapabilities
  tracking_subdomain?: string
}

export interface DomainRecord {
  record?: 'SPF' | 'DKIM' | 'Receiving' | 'Tracking' | 'TrackingCAA'
  name?: string
  type?: 'MX' | 'TXT' | 'CNAME' | 'CAA'
  ttl?: string
  status?: 'pending' | 'verified' | 'failed' | 'temporary_failure' | 'not_started'
  value?: string
  priority?: number
}

export interface Domain {
  object?: string
  id?: string
  name?: string
  status?:
    | 'pending'
    | 'verified'
    | 'failed'
    | 'not_started'
    | 'partially_verified'
    | 'partially_failed'
  created_at?: string /* date-time */
  region?: string
  open_tracking?: boolean
  click_tracking?: boolean
  tracking_subdomain?: string
  capabilities?: DomainCapabilities
  records?: DomainRecord[]
}

export interface VerifyDomainResponse {
  object?: string
  id?: string
}

export interface ListDomainsResponse {
  object?: string
  has_more?: boolean
  data?: ListDomainsItem[]
}

export interface ListDomainsItem {
  id?: string
  name?: string
  status?:
    | 'pending'
    | 'verified'
    | 'failed'
    | 'not_started'
    | 'partially_verified'
    | 'partially_failed'
  created_at?: string /* date-time */
  region?: string
  capabilities?: DomainCapabilities
}

export interface UpdateDomainResponseSuccess {
  id?: string
  object?: string
}

export interface DeleteDomainResponse {
  object?: string
  id?: string
  deleted?: boolean
}

export interface CreateApiKeyRequest {
  name: string
  permission?: 'full_access' | 'sending_access'
  domain_id?: string
}

export interface CreateApiKeyResponse {
  id?: string
  token?: string
}

export interface ListApiKeysResponse {
  object?: string
  has_more?: boolean
  data?: ApiKey[]
}

export interface ApiKey {
  id?: string
  name?: string
  created_at?: string /* date-time */
  last_used_at?: string | null
}

export interface DeleteApiKeyResponse {
  object?: string
  id?: string
  deleted?: boolean
}

export interface CreateAudienceOptions {
  name: string
}

export interface CreateAudienceResponseSuccess {
  id?: string
  object?: string
  name?: string
}

export interface GetAudienceResponseSuccess {
  id?: string
  object?: string
  name?: string
  created_at?: string
}

export interface RemoveAudienceResponseSuccess {
  id?: string
  object?: string
  deleted?: boolean
}

export interface ListAudiencesResponseSuccess {
  object?: string
  data?: {
    id?: string
    name?: string
    created_at?: string /* date-time */
  }[]
}

export interface CreateContactOptions {
  email: string
  first_name?: string
  last_name?: string
  unsubscribed?: boolean
  properties?: Record<string, unknown>
  segments?: string[]
  topics?: {
    id?: string
    subscription?: 'opt_in' | 'opt_out'
  }[]
  audience_id?: string
}

export interface CreateContactResponseSuccess {
  object?: string
  id?: string
}

export interface GetContactResponseSuccess {
  object?: string
  id?: string
  email?: string
  first_name?: string
  last_name?: string
  created_at?: string /* date-time */
  unsubscribed?: boolean
  properties?: Record<string, unknown>
}

export interface UpdateContactOptions {
  email?: string
  first_name?: string
  last_name?: string
  unsubscribed?: boolean
  properties?: Record<string, unknown>
}

export interface UpdateContactResponseSuccess {
  object?: string
  id?: string
}

export interface RemoveContactResponseSuccess {
  object?: string
  id?: string
  deleted?: boolean
}

export interface ListContactsResponseSuccess {
  object?: string
  data?: {
    id?: string
    email?: string
    first_name?: string
    last_name?: string
    created_at?: string /* date-time */
    unsubscribed?: boolean
  }[]
}

export interface CreateBroadcastOptions {
  name?: string
  segment_id: string
  audience_id?: string
  from: string
  subject: string
  reply_to?: string[]
  preview_text?: string
  html?: string
  text?: string
  topic_id?: string
  send?: boolean
  scheduled_at?: string
}

export interface CreateBroadcastResponseSuccess {
  id?: string
  object?: string
}

export interface ListBroadcastsResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    name?: string
    audience_id?: string
    segment_id?: string
    status?: string
    created_at?: string /* date-time */
    scheduled_at?: string /* date-time */
    sent_at?: string /* date-time */
    topic_id?: string
  }[]
}

export interface GetBroadcastResponseSuccess {
  id?: string
  name?: string
  audience_id?: string | null
  segment_id?: string | null
  from?: string
  subject?: string
  reply_to?: string[]
  preview_text?: string
  status?: string
  created_at?: string /* date-time */
  scheduled_at?: string /* date-time */
  sent_at?: string /* date-time */
  text?: string | null
  html?: string | null
  topic_id?: string | null
}

export interface UpdateBroadcastOptions {
  name?: string
  audience_id?: string
  segment_id?: string
  from?: string
  subject?: string
  reply_to?: string[]
  preview_text?: string
  html?: string
  text?: string
  topic_id?: string
}

export interface UpdateBroadcastResponseSuccess {
  id?: string
  object?: string
}

export interface RemoveBroadcastResponseSuccess {
  id?: string
  object?: string
  deleted?: boolean
}

export interface SendBroadcastOptions {
  scheduled_at?: string
}

export interface SendBroadcastResponseSuccess {
  id?: string
}

export interface RetrievedAttachment {
  object?: string
  id?: string
  filename?: string
  content_type?: string
  content_id?: string
  content_disposition?: 'inline' | 'attachment'
  download_url?: string
  expires_at?: string /* date-time */
  size?: number
}

export interface ListAttachmentsResponse {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    filename?: string
    content_type?: string
    content_id?: string
    content_disposition?: 'inline' | 'attachment'
    download_url?: string
    expires_at?: string /* date-time */
    size?: number
  }[]
}

export interface GetReceivedEmailResponse {
  object?: string
  id?: string
  to?: string[]
  from?: string
  subject?: string
  message_id?: string
  bcc?: string[] | null
  cc?: string[] | null
  reply_to?: string[] | null
  html?: string | null
  text?: string | null
  headers?: Record<string, unknown> | null
  created_at?: string /* date-time */
  attachments?: {
    id?: string
    filename?: string
    content_type?: string
    content_id?: string
    content_disposition?: 'inline' | 'attachment'
    size?: number
  }[]
}

export interface ListReceivedEmailsResponse {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    to?: string[]
    from?: string
    subject?: string | null
    message_id?: string
    bcc?: string[] | null
    cc?: string[] | null
    reply_to?: string[] | null
    created_at?: string /* date-time */
    attachments?: {
      id?: string
      filename?: string
      content_type?: string
      content_id?: string
      content_disposition?: 'inline' | 'attachment'
      size?: number
    }[]
  }[]
}

export interface CreateWebhookRequest {
  endpoint: string
  events: string[]
}

export interface CreateWebhookResponse {
  object?: string
  id?: string
  signing_secret?: string
}

export interface GetWebhookResponse {
  object?: string
  id?: string
  endpoint?: string
  events?: string[] | null
  status?: string
  created_at?: string /* date-time */
  signing_secret?: string
}

export interface ListWebhooksResponse {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    endpoint?: string
    events?: string[] | null
    status?: string
    created_at?: string /* date-time */
  }[]
}

export interface UpdateWebhookRequest {
  endpoint?: string
  events?: string[]
  status?: 'enabled' | 'disabled'
}

export interface UpdateWebhookResponse {
  object?: string
  id?: string
}

export interface DeleteWebhookResponse {
  object?: string
  id?: string
  deleted?: boolean
}

export interface TemplateVariable {
  id?: string
  key: string
  type: 'string' | 'number' | 'boolean' | 'object' | 'list'
  fallback_value?: string | number | boolean | Record<string, unknown> | unknown[]
  created_at?: string /* date-time */
  updated_at?: string /* date-time */
}

export interface TemplateVariableInput {
  key: string
  type: 'string' | 'number' | 'boolean' | 'object' | 'list'
  fallback_value?: string | number | boolean | Record<string, unknown> | unknown[]
}

export interface Template {
  object?: string
  id?: string
  current_version_id?: string
  name?: string
  alias?: string
  from?: string
  subject?: string
  reply_to?: string[] | null
  html?: string
  text?: string
  variables?: TemplateVariable[]
  created_at?: string /* date-time */
  updated_at?: string /* date-time */
  status?: 'draft' | 'published'
  published_at?: string | null
  has_unpublished_versions?: boolean
}

export interface TemplateListItem {
  id?: string
  name?: string
  status?: 'draft' | 'published'
  published_at?: string | null
  created_at?: string /* date-time */
  updated_at?: string /* date-time */
  alias?: string
}

export interface CreateTemplateRequest {
  name: string
  alias?: string
  from?: string
  subject?: string
  reply_to?: string[]
  html: string
  text?: string
  variables?: TemplateVariableInput[]
}

export interface CreateTemplateResponseSuccess {
  id?: string
  object?: string
}

export interface ListTemplatesResponseSuccess {
  object?: string
  data?: TemplateListItem[]
  has_more?: boolean
}

export interface UpdateTemplateOptions {
  name?: string
  alias?: string
  from?: string
  subject?: string
  reply_to?: string[]
  html?: string
  text?: string
  variables?: TemplateVariableInput[]
}

export interface UpdateTemplateResponseSuccess {
  id?: string
  object?: string
}

export interface RemoveTemplateResponseSuccess {
  object?: string
  id?: string
  deleted?: boolean
}

export interface PublishTemplateResponseSuccess {
  id?: string
  object?: string
}

export interface DuplicateTemplateResponseSuccess {
  id?: string
  object?: string
}

export interface CreateSegmentOptions {
  name: string
  audience_id?: string
  filter?: Record<string, unknown>
}

export interface CreateSegmentResponseSuccess {
  id?: string
  object?: string
}

export interface GetSegmentResponseSuccess {
  id?: string
  object?: string
  name?: string
  audience_id?: string
  filter?: Record<string, unknown>
  created_at?: string /* date-time */
}

export interface ListSegmentsResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    name?: string
    audience_id?: string
    created_at?: string /* date-time */
  }[]
}

export interface RemoveSegmentResponseSuccess {
  id?: string
  object?: string
  deleted?: boolean
}

export interface CreateTopicOptions {
  name: string
  default_subscription: 'opt_in' | 'opt_out'
  description?: string
  visibility?: 'public' | 'private'
}

export interface CreateTopicResponseSuccess {
  id?: string
  object?: string
}

export interface GetTopicResponseSuccess {
  id?: string
  object?: string
  name?: string
  description?: string
  default_subscription?: 'opt_in' | 'opt_out'
  visibility?: 'public' | 'private'
  created_at?: string /* date-time */
}

export interface ListTopicsResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    name?: string
    description?: string
    default_subscription?: 'opt_in' | 'opt_out'
    visibility?: 'public' | 'private'
    created_at?: string /* date-time */
  }[]
}

export interface UpdateTopicOptions {
  name?: string
  description?: string
  visibility?: 'public' | 'private'
}

export interface UpdateTopicResponseSuccess {
  id?: string
  object?: string
}

export interface RemoveTopicResponseSuccess {
  id?: string
  object?: string
  deleted?: boolean
}

export interface CreateContactPropertyOptions {
  key: string
  type: 'string' | 'number'
  fallback_value?: string | number
}

export interface CreateContactPropertyResponseSuccess {
  id?: string
  object?: string
}

export interface GetContactPropertyResponseSuccess {
  object?: string
  id?: string
  key?: string
  type?: string
  fallback_value?: string | number
  created_at?: string /* date-time */
}

export interface ListContactPropertiesResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    key?: string
    type?: string
    fallback_value?: string | number
    created_at?: string /* date-time */
  }[]
}

export interface UpdateContactPropertyOptions {
  fallback_value?: string | number
}

export interface UpdateContactPropertyResponseSuccess {
  id?: string
  object?: string
}

export interface RemoveContactPropertyResponseSuccess {
  id?: string
  object?: string
  deleted?: boolean
}

export interface AddContactToSegmentResponseSuccess {
  object?: string
  contact_id?: string
  segment_id?: string
}

export interface ListContactSegmentsResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    name?: string
    created_at?: string /* date-time */
  }[]
}

export interface RemoveContactFromSegmentResponseSuccess {
  object?: string
  contact_id?: string
  segment_id?: string
  deleted?: boolean
}

export interface GetContactTopicsResponseSuccess {
  object?: string
  has_more?: boolean
  data?: {
    id?: string
    name?: string
    description?: string
    subscription?: 'opt_in' | 'opt_out'
  }[]
}

export interface UpdateContactTopicsOptions {
  topics: {
    id?: string
    subscription?: 'opt_in' | 'opt_out'
  }[]
}

export interface UpdateContactTopicsResponseSuccess {
  object?: string
  contact_id?: string
  topics?: {
    id?: string
    subscription?: 'opt_in' | 'opt_out'
  }[]
}

export interface LogSummary {
  id?: string
  created_at?: string /* date-time */
  endpoint?: string
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS'
  response_status?: number
  user_agent?: string | null
}

export interface Log {
  object?: string
  id?: string
  created_at?: string /* date-time */
  endpoint?: string
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS'
  response_status?: number
  user_agent?: string | null
  request_body?: Record<string, unknown> | null
  response_body?: Record<string, unknown> | null
}

export interface ListLogsResponse {
  object?: string
  has_more?: boolean
  data?: LogSummary[]
}

export interface AutomationStep {
  key: string
  type:
    | 'trigger'
    | 'send_email'
    | 'delay'
    | 'wait_for_event'
    | 'condition'
    | 'contact_update'
    | 'contact_delete'
    | 'add_to_segment'
  config: Record<string, unknown>
}

export interface AutomationStepResponse {
  key?: string
  type?:
    | 'trigger'
    | 'send_email'
    | 'delay'
    | 'wait_for_event'
    | 'condition'
    | 'contact_update'
    | 'contact_delete'
    | 'add_to_segment'
  config?: Record<string, unknown>
}

export interface AutomationConnection {
  from: string
  to: string
  type?: 'default' | 'condition_met' | 'condition_not_met' | 'timeout' | 'event_received'
}

export interface CreateAutomationRequest {
  name: string
  status?: 'enabled' | 'disabled'
  steps: AutomationStep[]
  connections: AutomationConnection[]
}

export interface CreateAutomationResponse {
  object?: string
  id?: string
}

export interface Automation {
  object?: string
  id?: string
  name?: string
  status?: 'enabled' | 'disabled'
  created_at?: string
  updated_at?: string
  steps?: AutomationStepResponse[]
  connections?: AutomationConnection[]
}

export interface AutomationListItem {
  id?: string
  name?: string
  status?: 'enabled' | 'disabled'
  created_at?: string
  updated_at?: string
}

export interface ListAutomationsResponse {
  object?: string
  has_more?: boolean
  data?: AutomationListItem[]
}

export interface PatchAutomationRequest {
  name?: string
  status?: 'enabled' | 'disabled'
  steps?: AutomationStep[]
  connections?: AutomationConnection[]
}

export interface PatchAutomationResponse {
  object?: string
  id?: string
}

export interface DeleteAutomationResponse {
  object?: string
  id?: string
  deleted?: boolean
}

export interface StopAutomationResponse {
  object?: string
  id?: string
  status?: string
}

export interface AutomationRunStep {
  key?: string
  type?:
    | 'trigger'
    | 'send_email'
    | 'delay'
    | 'wait_for_event'
    | 'condition'
    | 'contact_update'
    | 'contact_delete'
    | 'add_to_segment'
  status?: string
  started_at?: string | null
  completed_at?: string | null
  output?: Record<string, unknown> | null
  error?: Record<string, unknown> | null
  created_at?: string
}

export interface AutomationRun {
  object?: string
  id?: string
  status?: 'running' | 'completed' | 'failed' | 'cancelled'
  started_at?: string | null
  completed_at?: string | null
  created_at?: string
  steps?: AutomationRunStep[]
}

export interface AutomationRunListItem {
  id?: string
  status?: 'running' | 'completed' | 'failed' | 'cancelled'
  started_at?: string | null
  completed_at?: string | null
  created_at?: string
}

export interface ListAutomationRunsResponse {
  object?: string
  has_more?: boolean
  data?: AutomationRunListItem[]
}

export interface Event {
  object?: string
  id?: string
  name?: string
  schema?: Record<string, unknown> | null
  created_at?: string
  updated_at?: string | null
}

export interface EventSummary {
  id?: string
  name?: string
  schema?: Record<string, unknown> | null
  created_at?: string
  updated_at?: string | null
}

export interface CreateEventRequest {
  name: string
  schema?: Record<string, unknown> | null
}

export interface CreateEventResponse {
  object?: string
  id?: string
}

export interface ListEventsResponse {
  object?: string
  has_more?: boolean
  data?: EventSummary[]
}

export interface UpdateEventRequest {
  schema: Record<string, unknown> | null
}

export interface UpdateEventResponse {
  object?: string
  id?: string
}

export interface RemoveEventResponse {
  object?: string
  id?: string
  deleted?: boolean
}

export interface SendEventRequest {
  event: string
  contact_id?: string
  email?: string
  payload?: Record<string, unknown>
}

export interface SendEventResponse {
  object?: string
  event?: string
}
