// This file is auto-generated by openapi-zod-ts — do not edit

import type {
  MxAllOfRefs,
  MxAllOfWithSiblingProps,
  MxAllPrimitivesContainer,
  MxAnyOfRefs,
  MxAnyOfWithNull,
  MxArraysContainer,
  MxCompositionContainer,
  MxCycleCompA,
  MxCycleCompB,
  MxCyclicContainer,
  MxEnumConstContainer,
  MxFormatsContainer,
  MxIntegerEnum,
  MxMultiTypeContainer,
  MxMutualA,
  MxMutualB,
  MxNullableContainer,
  MxObjectsContainer,
  MxOneOfDiscriminator,
  MxOneOfRefs,
  MxRecord,
  MxString,
  MxTreeNode,
  MxTuple,
  MxTupleWithRest,
} from './models.js'
import { getConfig, type ClientConfig } from './client-config.js'

export class ApiError<Status extends number = number, Body = unknown> extends Error {
  constructor(
    public readonly status: Status,
    public readonly body: Body
  ) {
    super(`API error ${status}`)
    this.name = 'ApiError'
  }
}

type _FetchResponse = Awaited<ReturnType<typeof fetch>>

function _buildSignal(
  signal: AbortSignal | undefined,
  timeout: number | undefined
): AbortSignal | undefined {
  if (timeout === undefined) return signal
  const _ts = AbortSignal.timeout(timeout)
  if (signal === undefined) return _ts
  if (typeof AbortSignal.any === 'function') return AbortSignal.any([signal, _ts])
  const _ctrl = new AbortController()
  const _abort = (s: AbortSignal) => () => {
    if (!_ctrl.signal.aborted) _ctrl.abort(s.reason)
  }
  signal.addEventListener('abort', _abort(signal), { once: true })
  _ts.addEventListener('abort', _abort(_ts), { once: true })
  return _ctrl.signal
}

async function _request(
  method: string,
  path: string,
  opts: {
    searchParams?: URLSearchParams
    body?: unknown
    signal?: AbortSignal
  },
  config?: Partial<ClientConfig>
): Promise<_FetchResponse> {
  const {
    baseUrl,
    headers,
    onError,
    signal: _cfgSignal,
    timeout,
    onRequest,
    fetch: _configFetch,
  } = { ...getConfig(), ...config }
  const base = baseUrl ? baseUrl.replace(/\/$/, '') : ''
  const qs = opts.searchParams?.toString() ?? ''
  const url = qs ? `${base}${path}?${qs}` : `${base}${path}`
  const fetch = _configFetch ?? globalThis.fetch
  let _url = url
  let _init: RequestInit = {
    method,
    headers: {
      Accept: 'application/json',
      ...(opts.body !== undefined ? { 'Content-Type': 'application/json' } : {}),
      ...headers,
    },
    ...(opts.body !== undefined ? { body: JSON.stringify(opts.body) } : {}),
  }
  if (onRequest) {
    const _or = await onRequest({ url: _url, init: _init })
    if (_or) {
      if (_or.url !== undefined) _url = _or.url
      if (_or.init !== undefined) _init = { ..._init, ..._or.init }
    }
  }
  const _rawSignal = opts.signal ?? _cfgSignal
  const _resolvedSignal = _buildSignal(_rawSignal, timeout)
  if (_resolvedSignal !== undefined) _init = { ..._init, signal: _resolvedSignal }
  const res = await fetch(_url, _init)
  if (!res.ok) {
    const err = new ApiError(res.status, await res.json().catch(() => null))
    onError?.(err)
    throw err
  }
  return res
}

export async function getPrimitiveEcho(
  params?: {
    strParam?: string
    emailParam?: string
    uuidParam?: string
    dateParam?: string
    intParam?: number
    int32Param?: number
    numParam?: number
    boolParam?: boolean
  },
  config?: Partial<ClientConfig>
): Promise<MxAllPrimitivesContainer> {
  const searchParams = new URLSearchParams()
  if (params?.strParam != null) searchParams.set('strParam', String(params.strParam))
  if (params?.emailParam != null) searchParams.set('emailParam', String(params.emailParam))
  if (params?.uuidParam != null) searchParams.set('uuidParam', String(params.uuidParam))
  if (params?.dateParam != null) searchParams.set('dateParam', String(params.dateParam))
  if (params?.intParam != null) searchParams.set('intParam', String(params.intParam))
  if (params?.int32Param != null) searchParams.set('int32Param', String(params.int32Param))
  if (params?.numParam != null) searchParams.set('numParam', String(params.numParam))
  if (params?.boolParam != null) searchParams.set('boolParam', String(params.boolParam))
  const res = await _request('GET', '/matrix/primitives', { searchParams }, config)
  return res.json()
}

export async function getPrimitiveByPath(
  id: string,
  code: number,
  config?: Partial<ClientConfig>
): Promise<MxFormatsContainer> {
  const res = await _request(
    'GET',
    `/matrix/primitives/${encodeURIComponent(id)}/${encodeURIComponent(code)}`,
    {},
    config
  )
  return res.json()
}

export async function getEnumEcho(
  params?: {
    strEnum?: string
    intEnum?: string
  },
  config?: Partial<ClientConfig>
): Promise<MxEnumConstContainer> {
  const searchParams = new URLSearchParams()
  if (params?.strEnum != null) searchParams.set('strEnum', String(params.strEnum))
  if (params?.intEnum != null) searchParams.set('intEnum', String(params.intEnum))
  const res = await _request('GET', '/matrix/enums', { searchParams }, config)
  return res.json()
}

export async function getEnumByPath(
  pathEnum: string,
  config?: Partial<ClientConfig>
): Promise<MxIntegerEnum> {
  const res = await _request('GET', `/matrix/enums/${encodeURIComponent(pathEnum)}`, {}, config)
  return res.json()
}

export async function postArrays(
  body: MxArraysContainer,
  config?: Partial<ClientConfig>
): Promise<MxArraysContainer> {
  const res = await _request('POST', '/matrix/arrays', { body }, config)
  return res.json()
}

export async function postObjects(
  body: MxObjectsContainer,
  config?: Partial<ClientConfig>
): Promise<MxObjectsContainer> {
  const res = await _request('POST', '/matrix/objects', { body }, config)
  return res.json()
}

export async function postNullable(
  body: MxNullableContainer,
  config?: Partial<ClientConfig>
): Promise<MxNullableContainer> {
  const res = await _request('POST', '/matrix/nullable', { body }, config)
  return res.json()
}

export async function postComposition(
  body: MxCompositionContainer,
  config?: Partial<ClientConfig>
): Promise<MxCompositionContainer> {
  const res = await _request('POST', '/matrix/composition', { body }, config)
  return res.json()
}

export async function postCyclic(
  body: MxCyclicContainer,
  config?: Partial<ClientConfig>
): Promise<MxCyclicContainer> {
  const res = await _request('POST', '/matrix/cyclic', { body }, config)
  return res.json()
}

export async function postMultiTypes(
  body: MxMultiTypeContainer,
  config?: Partial<ClientConfig>
): Promise<MxMultiTypeContainer> {
  const res = await _request('POST', '/matrix/multitypes', { body }, config)
  return res.json()
}

export async function getPrimitiveDirect(config?: Partial<ClientConfig>): Promise<MxString> {
  const res = await _request('GET', '/matrix/primitives-direct', {}, config)
  return res.json()
}

export async function postRecordDirect(
  body: MxRecord,
  config?: Partial<ClientConfig>
): Promise<MxRecord> {
  const res = await _request('POST', '/matrix/record-direct', { body }, config)
  return res.json()
}

export async function postAllOfDirect(
  body: MxAllOfRefs,
  config?: Partial<ClientConfig>
): Promise<MxAllOfWithSiblingProps> {
  const res = await _request('POST', '/matrix/allof-direct', { body }, config)
  return res.json()
}

export async function postAnyOfDirect(
  body: MxAnyOfRefs,
  config?: Partial<ClientConfig>
): Promise<MxAnyOfWithNull> {
  const res = await _request('POST', '/matrix/anyof-direct', { body }, config)
  return res.json()
}

export async function postOneOfDirect(
  body: MxOneOfRefs,
  config?: Partial<ClientConfig>
): Promise<MxOneOfDiscriminator> {
  const res = await _request('POST', '/matrix/oneof-direct', { body }, config)
  return res.json()
}

export async function postSelfRecursive(
  body: MxTreeNode,
  config?: Partial<ClientConfig>
): Promise<MxTreeNode> {
  const res = await _request('POST', '/matrix/self-recursive', { body }, config)
  return res.json()
}

export async function postMutualCycle(
  body: MxMutualA,
  config?: Partial<ClientConfig>
): Promise<MxMutualB> {
  const res = await _request('POST', '/matrix/mutual-cycle', { body }, config)
  return res.json()
}

export async function postCycleComposition(
  body: MxCycleCompA,
  config?: Partial<ClientConfig>
): Promise<MxCycleCompB> {
  const res = await _request('POST', '/matrix/cycle-composition', { body }, config)
  return res.json()
}

export async function postTupleDirect(
  body: MxTuple,
  config?: Partial<ClientConfig>
): Promise<MxTupleWithRest> {
  const res = await _request('POST', '/matrix/tuple-direct', { body }, config)
  return res.json()
}
