// This file is auto-generated by openapi-zod-ts - do not edit

export interface Error {
  message?: string
  status?: number
  timestamp?: string /* date-time */
}

export interface Holiday {
  date: string /* date */
  federal: 1 | 0
  id: number
  nameEn: string
  nameFr: string
  observedDate: string /* date */
  optional?: 1
  provinces?: Province[]
}

export interface Province {
  id: 'AB' | 'BC' | 'MB' | 'NB' | 'NL' | 'NS' | 'NT' | 'NU' | 'ON' | 'PE' | 'QC' | 'SK' | 'YT'
  nameEn: string
  nameFr: string
  nextHoliday?: Holiday
  optional?: 1
  provinces?: Holiday[]
  sourceEn: string
  sourceLink: string
}
