import type { OpenAPIV3_1 } from 'openapi-types'

export interface GeneratedFile {
  filename: string
  content: string
}

/**
 * Generate `test-utils.ts` — a set of testing helpers for the generated hooks.
 *
 * Zero new dependencies: everything imported here is already a peer dependency
 * that any consumer of `@codewithagents/openapi-react-query` must have:
 *   - `@tanstack/react-query` — QueryClient, QueryClientProvider
 *   - `react`                — ReactNode, createElement
 *
 * Consumers bring their own test runner / MSW / @testing-library/react.
 * This file just eliminates the boilerplate they'd write in every test suite.
 */

export function generateTestUtils(_spec: OpenAPIV3_1.Document): GeneratedFile {
  const lines: string[] = []

  lines.push('// This file is auto-generated by @codewithagents/openapi-react-query — do not edit')
  lines.push('')
  lines.push("import { QueryClient, QueryClientProvider } from '@tanstack/react-query'")
  lines.push("import { createElement, type ReactNode } from 'react'")
  lines.push('')

  // createTestQueryClient
  lines.push('/**')
  lines.push(' * Creates a QueryClient pre-configured for testing.')
  lines.push(' *')
  lines.push(' * Differences from the production default:')
  lines.push(' * - `retry: false`  — tests should not retry on failure')
  lines.push(' * - `gcTime: 0`     — no garbage-collection delay between tests')
  lines.push(' */')
  lines.push('export function createTestQueryClient(): QueryClient {')
  lines.push('  return new QueryClient({')
  lines.push('    defaultOptions: {')
  lines.push('      queries: {')
  lines.push('        retry: false,')
  lines.push('        gcTime: 0,')
  lines.push('      },')
  lines.push('      mutations: {')
  lines.push('        retry: false,')
  lines.push('      },')
  lines.push('    },')
  lines.push('  })')
  lines.push('}')
  lines.push('')

  // createWrapper
  lines.push('/**')
  lines.push(' * Returns a wrapper component that provides a `QueryClientProvider`.')
  lines.push(' * Pass it as the `wrapper` option to `renderHook` from `@testing-library/react`.')
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * ```ts')
  lines.push(' * const queryClient = createTestQueryClient()')
  lines.push(' * const wrapper = createWrapper(queryClient)')
  lines.push(' * const { result } = renderHook(() => useListTasks(), { wrapper })')
  lines.push(' * ```')
  lines.push(' */')
  lines.push('export function createWrapper(')
  lines.push('  queryClient: QueryClient,')
  lines.push('): ({ children }: { children: ReactNode }) => ReactNode {')
  lines.push('  return function Wrapper({ children }: { children: ReactNode }): ReactNode {')
  lines.push('    return createElement(QueryClientProvider, { client: queryClient }, children)')
  lines.push('  }')
  lines.push('}')
  lines.push('')

  return {
    filename: 'test-utils.ts',
    content: lines.join('\n'),
  }
}
