import { describe, it, expect } from 'vitest'
import { generateClientConfig } from '../plugins/client-config.js'
import { compileSingleFile, assertNoTsDiagnostics } from './helpers.js'

describe('generateClientConfig', () => {
  it('returns filename client-config.ts', () => {
    expect(generateClientConfig().filename).toBe('client-config.ts')
  })

  it('contains the auto-generated header', () => {
    expect(generateClientConfig().content).toContain(
      '// This file is auto-generated by openapi-zod-ts'
    )
  })

  it('exports ClientConfig interface', () => {
    expect(generateClientConfig().content).toContain('export interface ClientConfig')
  })

  it('exports configureClient function', () => {
    expect(generateClientConfig().content).toContain('export function configureClient')
  })

  it('exports getConfig function', () => {
    expect(generateClientConfig().content).toContain('export function getConfig')
  })

  it('supports token as string or function in interface', () => {
    const content = generateClientConfig().content
    expect(content).toContain('token?')
    expect(content).toContain('Promise<string>')
  })

  it('supports credentials field', () => {
    expect(generateClientConfig().content).toContain('credentials?')
  })

  it('generated content compiles with TypeScript strict mode', () => {
    const content = generateClientConfig().content

    const diagnostics = compileSingleFile('client-config.ts', content, {
      lib: ['ES2022', 'DOM'],
    })

    assertNoTsDiagnostics(diagnostics, 'generated client-config.ts')
    expect(diagnostics.length).toBe(0)
  })
})
