import { describe, it, expect, beforeAll } from 'vitest'
import { parseSpec } from '../parser.js'
import { generateClient, hasCookieAuth } from '../plugins/client.js'
import { generateClientConfig } from '../plugins/client-config.js'
import { generateTypes } from '../plugins/types.js'
import type { OpenAPIV3_1 } from 'openapi-types'
import ts from 'typescript'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'
import { compileFiles } from './helpers.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const taskApiFixture = join(__dirname, '../__fixtures__/specs/task-api.json')
const featureShowcaseFixture = join(__dirname, '../__fixtures__/specs/feature-showcase.json')
const deprecatedApiFixture = join(__dirname, '../__fixtures__/specs/deprecated-api.json')

describe('generateClient', () => {
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(taskApiFixture)
    content = generateClient(spec).content
  })

  it('returns filename client.ts', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).filename).toBe('client.ts')
  })

  it('contains the auto-generated header', () => {
    expect(content).toContain('// This file is auto-generated by openapi-zod-ts')
  })

  it('imports getConfig and ClientConfig from ./client-config.js', () => {
    expect(content).toContain("from './client-config.js'")
    expect(content).toContain('getConfig')
    expect(content).toContain('ClientConfig')
  })

  it('imports types from ./models.js', () => {
    expect(content).toContain("from './models.js'")
  })

  it('exports ApiError class', () => {
    expect(content).toContain('export class ApiError')
    // ApiError is now generic — status is typed as the Status param (default: number)
    expect(content).toContain('public readonly status: Status')
  })

  it('generates getTasks function', () => {
    expect(content).toContain('export async function getTasks(')
  })

  it('getTasks has query params object', () => {
    expect(content).toContain('page')
    expect(content).toContain('status')
  })

  it('generates createTask with body parameter', () => {
    expect(content).toContain('export async function createTask(')
    expect(content).toContain('CreateTaskRequest')
    expect(content).toContain('Content-Type')
    expect(content).toContain('JSON.stringify')
  })

  it('generates getTaskById with path parameter', () => {
    expect(content).toContain('export async function getTaskById(')
    expect(content).toContain('id:')
    expect(content).toContain('encodeURIComponent')
  })

  it('generates deleteTask returning void (no res.json)', () => {
    expect(content).toContain('export async function deleteTask(')
    // DELETE with 204 response returns void — extract the deleteTask function block
    const deleteFnMatch = content.match(/export async function deleteTask[\s\S]*?^\}/m)
    if (deleteFnMatch) {
      expect(deleteFnMatch[0]).not.toContain('res.json()')
    }
  })

  it('onError is present in generated client (error hook from config)', () => {
    // onError is always emitted regardless of auth features
    expect(content).toContain('onError')
    expect(content).toContain('onError?.(err)')
  })

  it('generates updateTask with path param and body', () => {
    expect(content).toContain('updateTask')
    expect(content).toContain('CreateTaskRequest')
  })

  it('handles nested path /tasks/{id}/tags', () => {
    expect(content).toContain('addTagToTask')
    expect(content).toContain('/api/v1/tasks')
    expect(content).toContain('tags')
  })

  it('every generated function accepts optional config parameter last', () => {
    // All generated functions should accept config? as the last parameter
    expect(content).toContain('config?: Partial<ClientConfig>')
    // The spread pattern merges global config with per-request override
    expect(content).toContain('{ ...getConfig(), ...config }')
  })

  it('snapshot: stable output', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).content).toMatchSnapshot()
  })

  it('compiles without TypeScript errors (with models.ts and client-config.ts)', async () => {
    const spec = await parseSpec(taskApiFixture)
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`
        )
        .join('\n')
      throw new Error(`TypeScript errors in generated client:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })

  it('SSR usage compiles: per-request config override passes TypeScript strict checks', async () => {
    const spec = await parseSpec(taskApiFixture)
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    // Simulate SSR consumer code that uses per-request config overrides
    // Note: page is required in the task-api fixture, so params arg is required
    const usageContent = `
import { getTasks, getTaskById, createTask, deleteTask } from './client'
import type { CreateTaskRequest } from './models'

async function serverSideExample() {
  // SSR: absolute base URL + session token, no global mutation
  const tasks = await getTasks({ page: 1 }, {
    baseUrl: 'https://api.example.com',
    token: 'server-session-token',
    credentials: 'omit',
  })

  // SSR with query params and config override
  const filtered = await getTasks({ page: 1, status: 'active' }, {
    baseUrl: 'https://api.example.com',
    token: async () => 'refreshed-token',
  })

  // SSR with path param
  const task = await getTaskById('123', {
    baseUrl: 'https://api.example.com',
    token: 'server-session-token',
  })

  // CSR usage unchanged (backward compat) — no config param needed
  const csrTasks = await getTasks({ page: 1 })

  // Type check: config is Partial — all fields optional
  const withPartialOverride = await getTasks({ page: 2 }, { baseUrl: 'https://override.com' })

  return { tasks, filtered, task, csrTasks, withPartialOverride }
}
`

    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
      'usage.ts': usageContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`
        )
        .join('\n')
      throw new Error(`TypeScript errors in SSR usage:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })
})

describe('required query params', () => {
  it('required param has no ? in the params object', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    // page is required in task-api.json — should be `page: number` not `page?: number`
    expect(out).toContain('page: number')
    expect(out).not.toContain('page?: number')
  })

  it('optional param still has ? in the params object', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    expect(out).toContain('status?: string')
  })

  it('params object itself is required when any param is required', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    // getTasks has required page — params arg must not be optional
    expect(out).toMatch(/getTasks\(params: \{/)
    expect(out).not.toMatch(/getTasks\(params\?: \{/)
  })
})

describe('inline response schemas', () => {
  it('inline object response with properties is expanded to a typed object (#298)', async () => {
    // searchPosts in blog-api has an inline object response { results: Post[]; total }
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    const out = generateClient(spec).content
    expect(out).toContain('searchPosts')
    // The inline object must be expanded, not collapsed to the Record catch-all.
    expect(out).not.toContain('Promise<Record<string, unknown>>')
    expect(out).toContain('Promise<{ results?: Post[]; total?: number }>')
    // The referenced component schema must be imported from ./models.js.
    expect(out).toMatch(/import type \{[^}]*\bPost\b[^}]*\} from '\.\/models\.js'/)
  })

  it('primitive response schema → correct primitive type', async () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/ping': {
          get: {
            operationId: 'ping',
            responses: {
              '200': {
                content: { 'application/json': { schema: { type: 'string' } } },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<string>')
  })
})

describe('error_body_type (#293): typed schema-less error bodies', () => {
  const minimalSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'T', version: '1' },
    paths: {
      '/items': {
        get: {
          operationId: 'listItems',
          responses: {
            '200': { content: { 'application/json': { schema: { type: 'string' } } } },
          },
        },
      },
    },
  }

  it('without errorBodyType: error body cast uses no type annotation', () => {
    const out = generateClient(minimalSpec).content
    expect(out).toContain('await res.json().catch(() => null)')
    expect(out).not.toContain(' as ')
  })

  it('errorBodyType laravel: LaravelValidationError type is emitted after ApiError', () => {
    const out = generateClient(minimalSpec, { errorBodyType: 'laravel' }).content
    expect(out).toContain('export type LaravelValidationError = {')
    expect(out).toContain('message: string')
    expect(out).toContain('errors: Record<string, string[]>')
  })

  it('errorBodyType laravel: error body is cast to LaravelValidationError', () => {
    const out = generateClient(minimalSpec, { errorBodyType: 'laravel' }).content
    expect(out).toContain('await res.json().catch(() => null) as LaravelValidationError')
  })

  it('errorBodyType laravel: no import is emitted for LaravelValidationError', () => {
    const out = generateClient(minimalSpec, { errorBodyType: 'laravel' }).content
    expect(out).not.toMatch(/import type \{.*LaravelValidationError/)
  })

  it('errorBodyType custom + importPath: import type is emitted at top', () => {
    const out = generateClient(minimalSpec, {
      errorBodyType: 'ApiErrorBody',
      errorBodyTypeImport: './types/errors',
    }).content
    expect(out).toContain("import type { ApiErrorBody } from './types/errors'")
  })

  it('errorBodyType custom + importPath: error body is cast to custom type', () => {
    const out = generateClient(minimalSpec, {
      errorBodyType: 'ApiErrorBody',
      errorBodyTypeImport: './types/errors',
    }).content
    expect(out).toContain('await res.json().catch(() => null) as ApiErrorBody')
  })

  it('errorBodyType custom without importPath: cast emitted, no import', () => {
    const out = generateClient(minimalSpec, { errorBodyType: 'GlobalErrorType' }).content
    expect(out).toContain('await res.json().catch(() => null) as GlobalErrorType')
    expect(out).not.toMatch(/import type \{.*GlobalErrorType/)
  })

  it('errorBodyType custom: LaravelValidationError type NOT emitted', () => {
    const out = generateClient(minimalSpec, { errorBodyType: 'ApiErrorBody' }).content
    expect(out).not.toContain('LaravelValidationError')
  })
})

describe('generateClient with empty paths', () => {
  it('handles spec with no paths gracefully', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(() => generateClient(spec)).not.toThrow()
  })

  it('still exports ApiError when no paths', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(generateClient(spec).content).toContain('ApiError')
  })
})

describe('fixture: blog-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    content = generateClient(spec).content
  })

  it('generates listPosts with 2 required + 2 optional params', () => {
    expect(content).toContain('listPosts')
    expect(content).toContain('page: number')
    expect(content).toContain('limit: number')
    expect(content).toContain('tag?: string')
    expect(content).toContain('published?: boolean')
  })

  it('generates searchPosts with required q param', () => {
    expect(content).toContain('searchPosts')
    expect(content).toContain('q: string')
  })

  it('generates deletePost returning void', () => {
    expect(content).toContain('deletePost')
    expect(content).toContain('Promise<void>')
  })

  it('generates publishPost with path param, no body', () => {
    expect(content).toContain('publishPost')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: auth-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/auth-api.json'))
    content = generateClient(spec).content
  })

  it('generates login, logout, getMe', () => {
    expect(content).toContain('login')
    expect(content).toContain('logout')
    expect(content).toContain('getMe')
  })

  it('generates logout returning void (204)', () => {
    const match = content.match(/export async function logout[\s\S]*?^\}/m)
    expect(match).toBeTruthy()
    expect(match![0]).toContain('Promise<void>')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/auth-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: ecommerce-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/ecommerce-api.json'))
    content = generateClient(spec).content
  })

  it('generates listProducts with required page + pageSize', () => {
    expect(content).toContain('listProducts')
    expect(content).toContain('page: number')
    expect(content).toContain('pageSize: number')
    expect(content).toContain('minPrice?: number')
    expect(content).toContain('inStock?: boolean')
  })

  it('generates full cart + order lifecycle', () => {
    expect(content).toContain('getCart')
    expect(content).toContain('addToCart')
    expect(content).toContain('removeFromCart')
    expect(content).toContain('placeOrder')
    expect(content).toContain('getOrder')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/ecommerce-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: petstore31 (real-world public spec)', () => {
  it('parses and generates without errors', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/petstore31.json'))
    expect(() => generateTypes(spec)).not.toThrow()
    expect(() => generateClient(spec)).not.toThrow()
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/petstore31.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('enum query params', () => {
  it('string enum query param generates union literal type', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const out = generateClient(spec).content
    // category has enum: ["books", "electronics", "clothing"]
    // JSON.stringify uses double quotes for string literals
    expect(out).toContain('"books" | "electronics" | "clothing"')
  })

  it('required integer param stays as number (not enum)', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const out = generateClient(spec).content
    expect(out).toContain('page: number')
  })

  it('enum param compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('$ref parameter resolution', () => {
  const refParamsFixture = join(__dirname, '../__fixtures__/specs/ref-params.json')
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(refParamsFixture)
    content = generateClient(spec).content
  })

  it('resolves $ref path param: uuid appears as positional string arg', () => {
    expect(content).toContain('uuid: string')
  })

  it('resolves $ref query param: page appears in optional params object', () => {
    expect(content).toContain('page?: number')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(refParamsFixture)
    const diagnostics = compileFiles({
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`
        )
        .join('\n')
      throw new Error(`TypeScript errors in ref-params client:\n${messages}`)
    }
    expect(diagnostics.length).toBe(0)
  })
})

describe('YAML spec support', () => {
  it('parses YAML spec without errors', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    expect(() => generateClient(spec)).not.toThrow()
    expect(() => generateTypes(spec)).not.toThrow()
  })

  it('generates listItems from YAML spec', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const out = generateClient(spec).content
    expect(out).toContain('listItems')
    expect(out).toContain('page: number')
    expect(out).toContain('Promise<Item[]>')
  })

  it('generates getItem with path param from YAML spec', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const out = generateClient(spec).content
    expect(out).toContain('getItem')
    expect(out).toContain('Promise<Item>')
  })

  it('generates deleteItem returning void from YAML spec', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/simple-api.yaml'))
    const out = generateClient(spec).content
    expect(out).toContain('deleteItem')
    expect(out).toContain('Promise<void>')
  })
})

describe('feature-showcase fixture', () => {
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(featureShowcaseFixture)
    content = generateClient(spec).content
  })

  // Feature 1: Query array params — correct serialization
  it('uses searchParams.append for array query params (tags)', () => {
    expect(content).toContain("searchParams.append('tags'")
    expect(content).not.toContain("searchParams.set('tags'")
  })

  it('uses searchParams.append for array query params (status)', () => {
    expect(content).toContain("searchParams.append('status'")
    expect(content).not.toContain("searchParams.set('status'")
  })

  it('array param type is string[] in the params interface', () => {
    expect(content).toContain('tags?: string[]')
  })

  // Feature 2: Header parameters
  it('header param xStripeSignature is non-optional in params', () => {
    expect(content).toContain('xStripeSignature: string')
    expect(content).not.toContain('xStripeSignature?: string')
  })

  it('header param is forwarded to fetch headers', () => {
    // Non-string header values are coerced with String() to satisfy Record<string, string>.
    // JSON.stringify produces double-quoted keys; property name xStripeSignature unchanged.
    expect(content).toContain('"X-Stripe-Signature": String(params.xStripeSignature)')
  })

  // Feature 3: Cookie auth — generateClientConfig with defaultCredentials: 'include'
  it('generateClientConfig with defaultCredentials include emits credentials: include', () => {
    const out = generateClientConfig({ defaultCredentials: 'include' }).content
    expect(out).toContain("credentials: 'include'")
  })

  it('generateClientConfig with cookie auth has the cookie auth comment', () => {
    const out = generateClientConfig({ defaultCredentials: 'include' }).content
    expect(out).toContain('Cookie auth: send session cookie automatically')
  })

  // Feature 4: multipart/form-data
  it('upload endpoint uses FormData instead of JSON.stringify', () => {
    expect(content).toContain('new FormData()')
    expect(content).toContain(`formData.append("file"`)
  })

  it('upload endpoint does NOT contain JSON.stringify(body)', () => {
    // Extract just the uploadFile function block to avoid false positives
    const uploadMatch = content.match(/export async function uploadFile[\s\S]*?^\}/m)
    expect(uploadMatch).toBeTruthy()
    expect(uploadMatch![0]).not.toContain('JSON.stringify(body)')
  })

  it('upload endpoint does NOT emit Content-Type application/json', () => {
    const uploadMatch = content.match(/export async function uploadFile[\s\S]*?^\}/m)
    expect(uploadMatch).toBeTruthy()
    expect(uploadMatch![0]).not.toContain("'Content-Type': 'application/json'")
  })

  // Feature 5: TypeScript compilation
  it('compiles without TypeScript errors', async () => {
    const spec = await parseSpec(featureShowcaseFixture)
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    const diagnostics = compileFiles({
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`
        )
        .join('\n')
      throw new Error(`TypeScript errors in generated feature-showcase client:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })
})

describe('coverage: hasCookieAuth (lines 515-518)', () => {
  it('returns true when spec has apiKey-in-cookie security scheme', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {},
      components: {
        securitySchemes: {
          // @ts-expect-error — OpenAPI types lag on apiKey security scheme shape
          cookieAuth: { type: 'apiKey', in: 'cookie', name: 'session' },
        },
      },
    }
    expect(hasCookieAuth(spec)).toBe(true)
  })

  it('returns false when spec has no securitySchemes', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {},
    }
    expect(hasCookieAuth(spec)).toBe(false)
  })

  it('returns false when security scheme is Bearer (not cookie)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {},
      components: {
        securitySchemes: {
          // @ts-expect-error — testing non-cookie scheme type
          bearerAuth: { type: 'http', scheme: 'bearer' },
        },
      },
    }
    expect(hasCookieAuth(spec)).toBe(false)
  })
})

describe('coverage: deprecated + throws together (lines 321-329, 387-394)', () => {
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(deprecatedApiFixture)
    content = generateClient(spec).content
  })

  it('deprecated operation with error $ref generates @deprecated JSDoc tag', () => {
    // getTask is deprecated AND has 404/422 error $ref responses
    // → hasJsDoc block is emitted (lines 387-394)
    expect(content).toContain('* @deprecated')
  })

  it('error responses with $ref schema generate @throws JSDoc tags', () => {
    // getThrowsTags finds 404/422 with $ref schemas → @throws tags are generated (lines 321-329)
    expect(content).toContain('@throws {ApiError<404, NotFoundError>}')
    expect(content).toContain('@throws {ApiError<422, ValidationError>}')
  })

  it('deprecated + throws together produce a combined JSDoc block', () => {
    // Verify the JSDoc block has both @deprecated and @throws (both branches active)
    const match = content.match(/\/\*\*[\s\S]*?\*\//m)
    expect(match).toBeTruthy()
    const jsdoc = match![0]
    expect(jsdoc).toContain('@deprecated')
    expect(jsdoc).toContain('@throws')
  })

  it('non-deprecated operation with $ref error still gets @throws without @deprecated', () => {
    // createTask is not deprecated but has 422 ValidationError → only @throws, no @deprecated
    expect(content).not.toMatch(/createTask[\s\S]{0,200}@deprecated/)
  })
})

describe('inline additionalProperties response typing (#294)', () => {
  it('operation response with additionalProperties schema object -> Record<string, T>', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/metrics': {
          get: {
            operationId: 'getMetrics',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      additionalProperties: { type: 'integer', format: 'int32' },
                    },
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<Record<string, number>>')
    expect(out).not.toContain('Record<string, unknown>')
  })

  it('operation response with additionalProperties: true -> Record<string, unknown>', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/data': {
          get: {
            operationId: 'getData',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      additionalProperties: true,
                    },
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<Record<string, unknown>>')
  })

  it('operation response with object and no additionalProperties -> Record<string, unknown>', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/plain': {
          get: {
            operationId: 'getPlain',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                    },
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<Record<string, unknown>>')
  })

  it('operation response with additionalProperties string schema -> Record<string, string>', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/labels': {
          get: {
            operationId: 'getLabels',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      additionalProperties: { type: 'string' },
                    },
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<Record<string, string>>')
  })
})

describe('coverage: inlineSchemaToTs edge cases (lines 28, 31-33, 37)', () => {
  it('response with nullable array type → string | null (line 28: Array.isArray(s.type) branch)', () => {
    // inlineSchemaToTs handles type: ['string', 'null'] → 'string | null'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/ping': {
          get: {
            operationId: 'ping',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: { type: ['string', 'null'] },
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<string | null>')
  })

  it('request body with inline array schema → array type string (lines 31-33)', () => {
    // inlineSchemaToTs: type === 'array' with items → returns `${inlineSchemaToTs(items)}[]`
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/submit': {
          post: {
            operationId: 'submit',
            requestBody: {
              content: {
                'application/json': {
                  schema: {
                    type: 'array',
                    items: { type: 'string' },
                  },
                },
              },
            },
            responses: { '204': { description: 'ok' } },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('body: string[]')
  })

  it('request body with no type → unknown fallback (line 37)', () => {
    // inlineSchemaToTs: s.type is undefined, not array, not object → returns 'unknown'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/process': {
          post: {
            operationId: 'process',
            requestBody: {
              content: {
                'application/json': {
                  // Schema with no type — triggers the unknown fallback
                  schema: {},
                },
              },
            },
            responses: { '204': { description: 'ok' } },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('body: unknown')
  })
})

describe('coverage: queryParamType edge cases (lines 70, 81)', () => {
  it('boolean query param → boolean type in generated params', () => {
    // queryParamType for boolean type falls through to primitiveToTs which returns 'boolean'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [{ name: 'active', in: 'query', schema: { type: 'boolean' } }],
            responses: {
              '200': {
                content: {
                  'application/json': { schema: { type: 'array', items: { type: 'string' } } },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('active?: boolean')
  })

  it('array of integer query param → number[] type (return number[] branch)', () => {
    // queryParamType: type === 'array', items.type === 'integer' → return 'number[]'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [
              {
                name: 'ids',
                in: 'query',
                schema: { type: 'array', items: { type: 'integer' } },
              },
            ],
            responses: {
              '200': {
                content: {
                  'application/json': { schema: { type: 'array', items: { type: 'string' } } },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('ids?: number[]')
  })

  it('query param with undefined type schema → unknown (primitiveToTs default)', () => {
    // queryParamType calls primitiveToTs(undefined) → default case returns 'unknown'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [
              // Schema with no type — primitiveToTs(undefined) returns 'unknown'
              { name: 'filter', in: 'query', schema: {} },
            ],
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('filter?: unknown')
  })
})

describe('coverage: deriveOperationName via no-operationId spec (lines 101-123, 540)', () => {
  it('operation without operationId derives function name from method + path', () => {
    // When operationId is absent, deriveOperationName(method, path) is called (line 540)
    // covering the full deriveOperationName function (lines 101-123)
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/api/v1/tasks': {
          get: {
            // No operationId — deriveOperationName('get', '/api/v1/tasks') → 'getTasks'
            responses: {
              '200': {
                content: {
                  'application/json': { schema: { type: 'array', items: { type: 'string' } } },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('export async function getTasks(')
  })

  it('path param without operationId produces ById suffix', () => {
    // deriveOperationName('get', '/api/v1/tasks/{id}') → 'getTasksById'
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/api/v1/tasks/{id}': {
          get: {
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('ById')
  })

  it('POST without operationId gets create prefix', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/widgets': {
          post: {
            requestBody: {
              content: { 'application/json': { schema: { type: 'object' } } },
            },
            responses: {
              '201': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('export async function createWidgets(')
  })
})

describe('coverage: getReturnType no-successful-response fallback (line 153)', () => {
  it('operation with only error responses returns void', () => {
    // When responses has only 4xx codes (no 200/201/204), getReturnType falls through
    // to the final return { typeName: 'void', ... } at line 153
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/break': {
          delete: {
            operationId: 'breakThings',
            responses: {
              '400': {
                description: 'bad request',
                content: { 'application/json': { schema: { type: 'object' } } },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('export async function breakThings(')
    expect(out).toContain('Promise<void>')
  })
})

describe('schema-enhanced client generation', () => {
  // A minimal spec with $ref request body and $ref response
  const petSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Pet API', version: '1' },
    paths: {
      '/pets': {
        get: {
          operationId: 'listPets',
          responses: {
            '200': {
              description: 'list of pets',
              content: {
                'application/json': {
                  schema: { type: 'array', items: { $ref: '#/components/schemas/Pet' } },
                },
              },
            },
          },
        },
        post: {
          operationId: 'createPet',
          requestBody: {
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/CreatePetRequest' },
              },
            },
          },
          responses: {
            '201': {
              description: 'created pet',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/Pet' },
                },
              },
            },
          },
        },
      },
      '/pets/{id}': {
        get: {
          operationId: 'getPet',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            '200': {
              description: 'a pet',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/Pet' },
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        Pet: {
          type: 'object',
          required: ['id', 'name'],
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
          },
        },
        CreatePetRequest: {
          type: 'object',
          required: ['name'],
          properties: {
            name: { type: 'string' },
            species: { type: 'string' },
          },
        },
      },
    },
  }

  it('without schema options: no Zod validation injected', () => {
    const out = generateClient(petSpec).content
    expect(out).not.toContain('.parse(')
    expect(out).toContain('return res.json()')
  })

  it('with schema options: request body gets Schema.parse(body) validation before fetch', () => {
    const out = generateClient(petSpec, {
      schemaNames: new Set(['CreatePetRequestSchema', 'PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Validates the request body against the Zod schema before sending.
    // Note: we use .parse() not .strip().parse() because not all schemas are ZodObject
    // (allOf → ZodIntersection, oneOf/anyOf → ZodUnion — neither has .strip()).
    expect(out).toContain('CreatePetRequestSchema.parse(body)')
  })

  it('with schema options: single-object response gets Schema.parse(await res.json())', () => {
    const out = generateClient(petSpec, {
      schemaNames: new Set(['CreatePetRequestSchema', 'PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // getPet and createPet both return Pet — should validate
    expect(out).toContain('PetSchema.parse(await res.json())')
  })

  it('with schema options: array response gets z.array(Schema).parse(await res.json())', () => {
    const out = generateClient(petSpec, {
      schemaNames: new Set(['PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // listPets returns array of Pet — should use z.array
    expect(out).toContain('z.array(PetSchema).parse(await res.json())')
  })

  it('with schema options: imports z from zod for array validation', () => {
    const out = generateClient(petSpec, {
      schemaNames: new Set(['PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).toContain("import { z } from 'zod'")
  })

  it('with schema options: imports schema names from schemaImportPath', () => {
    const out = generateClient(petSpec, {
      schemaNames: new Set(['PetSchema', 'CreatePetRequestSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).toContain("from './schemas.js'")
    expect(out).toContain('PetSchema')
    expect(out).toContain('CreatePetRequestSchema')
  })

  it('drift-safe: no validation when schemaName not in schemaNames set', () => {
    // Only PetSchema provided — CreatePetRequestSchema absent (drift scenario)
    const out = generateClient(petSpec, {
      schemaNames: new Set(['PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Request body (CreatePetRequest) not in schemaNames — no parse call
    expect(out).not.toContain('CreatePetRequestSchema.strip().parse(body)')
  })

  it('without schema options: falls back to res.json() for all responses', () => {
    const out = generateClient(petSpec).content
    // All success responses should use res.json() without z.array wrapper
    const matches = out.match(/return res\.json\(\)/g) ?? []
    expect(matches.length).toBeGreaterThan(0)
  })
})

describe('_request helper: shared fetch abstraction (issue #124)', () => {
  // Design: two private helpers
  //   _request     — handles all JSON/no-body endpoints (always emitted when spec has endpoints)
  //   _requestForm — handles multipart/form-data endpoints (only emitted when spec has them)
  // Tree-shaking: _requestForm is absent from generated code for specs with no multipart endpoints.

  let taskContent: string // no multipart → only _request emitted
  let showcaseContent: string // has multipart → both _request and _requestForm emitted

  beforeAll(async () => {
    const taskSpec = await parseSpec(taskApiFixture)
    taskContent = generateClient(taskSpec).content

    const showcaseSpec = await parseSpec(featureShowcaseFixture)
    showcaseContent = generateClient(showcaseSpec).content
  })

  // --- Structural: helpers not exported, fetch/config not duplicated per endpoint ---

  it('emits _request helper in a spec with JSON endpoints', () => {
    expect(taskContent).toContain('async function _request(')
  })

  it('_request is not exported (private to the generated module)', () => {
    expect(taskContent).not.toContain('export async function _request(')
  })

  it('emits _requestForm only for specs that have multipart endpoints', () => {
    // showcase has uploadFile (multipart) → _requestForm is present
    expect(showcaseContent).toContain('async function _requestForm(')
    // task-api has no multipart → _requestForm is absent (tree-shaking benefit)
    expect(taskContent).not.toContain('_requestForm')
  })

  it('_requestForm is not exported (private to the generated module)', () => {
    expect(showcaseContent).not.toContain('export async function _requestForm(')
  })

  it('fetch is called exactly once in specs without multipart (only inside _request)', () => {
    // Before refactor: N endpoint functions × 1 fetch each = N occurrences
    // After refactor: only _request calls fetch = 1 occurrence
    const count = (taskContent.match(/await fetch\(/g) ?? []).length
    expect(count).toBe(1)
  })

  it('getConfig() is called exactly once in specs without multipart (only inside _request)', () => {
    // Before refactor: getConfig() duplicated in every endpoint function
    // After refactor: only _request calls getConfig()
    const count = (taskContent.match(/getConfig\(\)/g) ?? []).length
    expect(count).toBe(1)
  })

  // --- Endpoint functions delegate to the correct helper ---

  it('JSON GET endpoint delegates to _request', () => {
    expect(taskContent).toContain("_request('GET'")
  })

  it('JSON POST endpoint delegates to _request', () => {
    expect(taskContent).toContain("_request('POST'")
  })

  it('DELETE endpoint delegates to _request', () => {
    expect(taskContent).toContain("_request('DELETE'")
  })

  it('void endpoint does not call res.json()', () => {
    // deleteTask returns void — just await _request(...), no res.json()
    const deleteFnMatch = taskContent.match(/export async function deleteTask[\s\S]*?^\}/m)
    expect(deleteFnMatch).toBeTruthy()
    expect(deleteFnMatch![0]).not.toContain('res.json()')
  })

  it('non-void endpoint calls res.json() to parse the response', () => {
    expect(taskContent).toContain('res.json()')
  })

  it('query params are built as URLSearchParams and forwarded to _request', () => {
    expect(taskContent).toContain('new URLSearchParams()')
    expect(taskContent).toContain('searchParams')
  })

  it('header params are forwarded as extraHeaders option to _request', () => {
    // feature-showcase has an endpoint with X-Stripe-Signature header param
    expect(showcaseContent).toContain('extraHeaders')
  })

  it('multipart endpoint delegates to _requestForm, not inline fetch', () => {
    // feature-showcase uploadFile should call _requestForm(...)
    expect(showcaseContent).toContain('_requestForm(')
  })

  // --- TypeScript still compiles after refactor ---

  it('refactored task-api client compiles without TypeScript errors', async () => {
    const spec = await parseSpec(taskApiFixture)
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })

  it('refactored feature-showcase client compiles without TypeScript errors', async () => {
    const spec = await parseSpec(featureShowcaseFixture)
    const diagnostics = compileFiles({
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

// ── Feature-conditional helpers (issue #129) ──────────────────────────────────
// The _request / _requestForm helpers should only emit code for features that
// the spec actually uses. Specs without auth get a lean helper; specs with auth
// get the full token-resolution + Authorization header.

const noAuthSpec: OpenAPIV3_1.Document = {
  openapi: '3.1.0',
  info: { title: 'No-Auth API', version: '1' },
  paths: {
    '/items': {
      get: {
        operationId: 'listItems',
        responses: {
          '200': {
            content: {
              'application/json': { schema: { type: 'array', items: { type: 'string' } } },
            },
          },
        },
      },
      post: {
        operationId: 'createItem',
        requestBody: { content: { 'application/json': { schema: { type: 'string' } } } },
        responses: { '201': { content: { 'application/json': { schema: { type: 'string' } } } } },
      },
    },
    '/items/{id}': {
      delete: {
        operationId: 'deleteItem',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: { '204': { description: 'deleted' } },
      },
    },
  },
}

const bearerAuthSpec: OpenAPIV3_1.Document = {
  openapi: '3.1.0',
  info: { title: 'Bearer API', version: '1' },
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      // @ts-expect-error — OpenAPI types lag on http security scheme shape
      bearerAuth: { type: 'http', scheme: 'bearer' },
    },
  },
  paths: {
    '/items': {
      get: {
        operationId: 'listItems',
        responses: { '200': { content: { 'application/json': { schema: { type: 'string' } } } } },
      },
    },
  },
}

const cookieAuthSpec: OpenAPIV3_1.Document = {
  openapi: '3.1.0',
  info: { title: 'Cookie API', version: '1' },
  components: {
    securitySchemes: {
      // @ts-expect-error — testing apiKey-in-cookie scheme
      sessionCookie: { type: 'apiKey', in: 'cookie', name: 'session' },
    },
  },
  paths: {
    '/me': {
      get: {
        operationId: 'getMe',
        responses: { '200': { content: { 'application/json': { schema: { type: 'string' } } } } },
      },
    },
  },
}

describe('feature-conditional _request helper (issue #129)', () => {
  // ── No-auth spec: lean helper ──

  it('no-auth spec: _request does NOT contain resolvedToken', () => {
    const out = generateClient(noAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('resolvedToken')
  })

  it('no-auth spec: _request does NOT include Authorization header', () => {
    const out = generateClient(noAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('Authorization')
  })

  it('no-auth spec: _request does NOT include credentials (no cookie auth)', () => {
    const out = generateClient(noAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('credentials')
  })

  it('no-auth spec without header params: _request opts omit extraHeaders', () => {
    const out = generateClient(noAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('extraHeaders')
  })

  it('no-auth spec: TypeScript still compiles cleanly', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })

  // ── Bearer-auth spec: token resolution included ──

  it('bearer-auth spec: _request includes resolvedToken', () => {
    const out = generateClient(bearerAuthSpec as OpenAPIV3_1.Document).content
    expect(out).toContain('resolvedToken')
  })

  it('bearer-auth spec: _request includes Authorization header', () => {
    const out = generateClient(bearerAuthSpec as OpenAPIV3_1.Document).content
    expect(out).toContain('Authorization')
    expect(out).toContain('Bearer')
  })

  it('bearer-auth spec: does NOT include credentials (no cookie auth)', () => {
    const out = generateClient(bearerAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('credentials')
  })

  // ── Cookie-auth spec: credentials included ──

  it('cookie-auth spec: _request includes credentials', () => {
    const out = generateClient(cookieAuthSpec as OpenAPIV3_1.Document).content
    expect(out).toContain('credentials')
  })

  it('cookie-auth spec: does NOT include resolvedToken (no bearer)', () => {
    const out = generateClient(cookieAuthSpec as OpenAPIV3_1.Document).content
    expect(out).not.toContain('resolvedToken')
  })

  // ── Header params: extraHeaders only when spec has them ──

  it('spec with header params: _request opts include extraHeaders', async () => {
    const spec = await parseSpec(featureShowcaseFixture)
    const out = generateClient(spec).content
    expect(out).toContain('extraHeaders')
  })

  it('spec without header params: _request does not mention extraHeaders', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    expect(out).not.toContain('extraHeaders')
  })

  // ── feature-showcase: cookie auth + header params — both present ──

  it('feature-showcase: credentials AND extraHeaders present (cookie auth + header params)', async () => {
    const spec = await parseSpec(featureShowcaseFixture)
    const out = generateClient(spec).content
    expect(out).toContain('credentials')
    expect(out).toContain('extraHeaders')
  })
})

// ── sanitizeOperationId: real-world patterns ──────────────────────────────────
// The function is private, so we test it by running generateClient on a spec
// with the problematic operationId and asserting the generated function name.

function specWithOperationId(operationId: string): OpenAPIV3_1.Document {
  return {
    openapi: '3.1.0',
    info: { title: 'T', version: '1' },
    paths: {
      '/test': {
        get: {
          operationId,
          responses: { '200': { content: { 'application/json': { schema: { type: 'string' } } } } },
        },
      },
    },
  }
}

describe('sanitizeOperationId: real-world operationId formats', () => {
  it('kebab-case with mixed casing: post-applePay-sessions → postApplePaySessions', () => {
    const out = generateClient(specWithOperationId('post-applePay-sessions')).content
    expect(out).toContain('export async function postApplePaySessions(')
  })

  it('dot-separated (Google-style): calendar.calendars.insert → calendarCalendarsInsert', () => {
    const out = generateClient(specWithOperationId('calendar.calendars.insert')).content
    expect(out).toContain('export async function calendarCalendarsInsert(')
  })

  it('space-separated words: Get User Profile → getUserProfile', () => {
    const out = generateClient(specWithOperationId('Get User Profile')).content
    expect(out).toContain('export async function getUserProfile(')
  })

  it('parentheses: forgotPassword(oneTimeCode) → forgotPasswordOneTimeCode', () => {
    const out = generateClient(specWithOperationId('forgotPassword(oneTimeCode)')).content
    expect(out).toContain('export async function forgotPasswordOneTimeCode(')
  })

  it('braces: getSearchArticlesQuery{} → getSearchArticlesQuery', () => {
    const out = generateClient(specWithOperationId('getSearchArticlesQuery{}')).content
    expect(out).toContain('export async function getSearchArticlesQuery(')
  })

  it("apostrophe: user's group → usersGroup (apostrophe stripped, not split)", () => {
    const out = generateClient(specWithOperationId("user's group")).content
    expect(out).toContain('export async function usersGroup(')
  })

  it('mixed separators: api.v2/users-list → apiV2UsersList', () => {
    const out = generateClient(specWithOperationId('api.v2/users-list')).content
    expect(out).toContain('export async function apiV2UsersList(')
  })
})

describe('coverage: array response with no items → unknown[]', () => {
  it('array schema without items property produces unknown[] return type', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            responses: {
              '200': {
                description: 'ok',
                content: {
                  'application/json': {
                    schema: { type: 'array' }, // no items property
                  },
                },
              },
            },
          },
        },
      },
    }
    const { content } = generateClient(spec)
    expect(content).toContain('Promise<unknown[]>')
  })
})

describe('coverage: queryParamType with no schema (line 77)', () => {
  it('query param without schema property produces string type', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [
              // No schema property - queryParamType(undefined) returns 'string'
              { name: 'cursor', in: 'query' } as any,
            ],
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
    }
    const out = generateClient(spec).content
    expect(out).toContain('cursor?: string')
  })
})

describe('coverage: sanitizeOperationId edge cases (lines 117, 124)', () => {
  it('all-punctuation operationId produces unknown function name (line 117)', () => {
    const out = generateClient(specWithOperationId('!!!')).content
    expect(out).toContain('export async function unknown(')
  })

  it('digit-starting operationId gets underscore prefix (line 124)', () => {
    const out = generateClient(specWithOperationId('1getItems')).content
    expect(out).toContain('export async function _1getItems(')
  })
})

describe('coverage: getReturnType + getThrowsTags with no responses (lines 163, 387)', () => {
  it('operation without responses property produces Promise<unknown>', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            // no responses property at all
          } as any,
        },
      },
    }
    const out = generateClient(spec).content
    expect(out).toContain('Promise<unknown>')
  })
})

describe('coverage: resolveParamRef edge cases (lines 202-204)', () => {
  it('$ref param with no components.parameters returns null and is dropped (line 202)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [{ $ref: '#/components/parameters/PageParam' } as any],
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
      components: { schemas: {} }, // has components but no parameters key
    }
    expect(() => generateClient(spec)).not.toThrow()
    // Dropped param means no params arg in the function signature
    expect(generateClient(spec).content).toContain('export async function listItems(')
  })

  it('$ref param where resolved value is itself a $ref (double-ref, line 204)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            parameters: [{ $ref: '#/components/parameters/PageParam' } as any],
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
      components: {
        parameters: {
          // PageParam is itself a $ref (double-ref) - resolveParamRef returns null
          PageParam: { $ref: '#/components/parameters/ActualPageParam' } as any,
        },
      },
    }
    expect(() => generateClient(spec)).not.toThrow()
  })
})

describe('coverage: getRequestBodyInfo with no content (line 334)', () => {
  it('requestBody with no content property is treated as no body', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          post: {
            operationId: 'createItem',
            requestBody: { required: true } as any, // no content
            responses: {
              '201': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
    }
    const out = generateClient(spec).content
    // Extract just the createItem function block to verify no body param
    const match = out.match(/export async function createItem[\s\S]*?^\}/m)
    expect(match).toBeTruthy()
    // When requestBody has no content, bodyInfo is undefined: function has no body parameter
    expect(match![0]).not.toContain('body:')
  })
})

describe('coverage: spec without paths property (line 815 FALSE)', () => {
  it('spec with paths=undefined: generateClient does not throw and still emits ApiError', () => {
    // When spec.paths is undefined (not even {}), the main generation loop is skipped entirely.
    // This covers the FALSE branch of `if (paths !== undefined)` at line 815.
    const spec = { openapi: '3.1.0', info: { title: 'T', version: '1' } } as OpenAPIV3_1.Document
    expect(() => generateClient(spec)).not.toThrow()
    expect(generateClient(spec).content).toContain('ApiError')
    // No endpoints means no _request helper either
    expect(generateClient(spec).content).not.toContain('async function _request(')
  })
})

describe('coverage: detectBearerAuth with $ref security scheme (line 488)', () => {
  it('security scheme that is a $ref returns false from isRef check', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            responses: {
              '200': { content: { 'application/json': { schema: { type: 'string' } } } },
            },
          },
        },
      },
      components: {
        securitySchemes: {
          // A $ref scheme - isRef(s) returns true, .some() returns false for it
          externalAuth: { $ref: '#/components/securitySchemes/ActualAuth' } as any,
        },
      },
    }
    expect(() => generateClient(spec)).not.toThrow()
    // $ref scheme does not trigger bearer auth
    expect(generateClient(spec).content).not.toContain('resolvedToken')
  })
})

describe('coverage: schema-enhanced mode edge cases (lines 421-431, 437-439, 446-448, 910)', () => {
  it('requestBody with no content in schema-enhanced mode: no validation injected (line 421)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          post: {
            operationId: 'createItem',
            requestBody: { required: true } as any, // no content
            responses: { '201': { description: 'created' } },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['CreateItemSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).toContain('export async function createItem(')
    expect(out).not.toContain('CreateItemSchema.parse(')
  })

  it('inline (non-$ref) request body in schema-enhanced mode: no schema name returned (line 424)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          post: {
            operationId: 'createItem',
            requestBody: {
              content: {
                'application/json': {
                  schema: { type: 'object' }, // inline schema, not a $ref
                },
              },
            },
            responses: { '201': { description: 'created' } },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['CreateItemSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Non-$ref schema: getRequestBodySchemaName returns undefined, no validation
    expect(out).not.toContain('CreateItemSchema.parse(')
  })

  it('getResponseSchemaName with no responses in schema-enhanced mode (line 431)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            // no responses property
          } as any,
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['ItemSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).not.toContain('ItemSchema.parse(')
  })

  it('200 response with no content in schema-enhanced mode: skips schema extraction (line 437)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            responses: { '200': { description: 'ok' } }, // no content
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['ItemSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).not.toContain('ItemSchema.parse(')
  })

  it('array response with inline items in schema-enhanced mode: no z.array() (lines 446-448 FALSE)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items': {
          get: {
            operationId: 'listItems',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { type: 'string' } }, // inline items, not $ref
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['ItemSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Inline array items: getResponseSchemaName returns undefined, no z.array() call
    expect(out).not.toContain('z.array(')
  })

  it('schema-enhanced with only single-object responses: no z import needed (line 910 FALSE)', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/pet': {
          get: {
            operationId: 'getPet',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: { $ref: '#/components/schemas/Pet' }, // single $ref, not an array
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['PetSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Single-object response: PetSchema.parse() used but no z.array(), so no z import
    expect(out).toContain('PetSchema.parse(')
    expect(out).not.toContain("import { z } from 'zod'")
  })

  it('requestBody with non-JSON content in schema-enhanced mode: no schema name (line 423)', () => {
    // getRequestBodySchemaName: content is defined but no application/json key
    // content['application/json'] === undefined -> return undefined at line 423
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/upload': {
          post: {
            operationId: 'uploadFile',
            requestBody: {
              content: {
                'multipart/form-data': {
                  schema: {
                    type: 'object',
                    properties: { file: { type: 'string', format: 'binary' } },
                  },
                },
                // no application/json key
              },
            },
            responses: { '201': { description: 'created' } },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['UploadFileSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // No application/json -> no schema name -> no validation injected
    expect(out).not.toContain('UploadFileSchema.parse(')
  })

  it('200 response with non-JSON content in schema-enhanced mode: skips schema (line 439)', () => {
    // getResponseSchemaName: content defined but no application/json key
    // jsonContent === undefined -> continue at line 439
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/report': {
          get: {
            operationId: 'getReport',
            responses: {
              '200': {
                content: {
                  'text/csv': { schema: { type: 'string' } },
                  // no application/json key
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['ReportSchema']),
      schemaImportPath: './schemas.js',
    }).content
    expect(out).not.toContain('ReportSchema.parse(')
  })

  it('200 response with inline object (not $ref, not array) in schema-enhanced mode (line 446 FALSE)', () => {
    // getResponseSchemaName: schema is not a $ref and not array -> line 446 FALSE -> return undefined
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/status': {
          get: {
            operationId: 'getStatus',
            responses: {
              '200': {
                content: {
                  'application/json': {
                    schema: { type: 'object', properties: { ok: { type: 'boolean' } } },
                    // inline object schema, not a $ref and not type:array
                  },
                },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec, {
      schemaNames: new Set(['StatusSchema']),
      schemaImportPath: './schemas.js',
    }).content
    // Inline object: getResponseSchemaName returns undefined -> no validation
    expect(out).not.toContain('StatusSchema.parse(')
  })
})

// ── 204 no-content guard (fixes #272) ────────────────────────────────────────
// Operations that declare a 204 alongside a 200/201 body response must not
// call res.json() unconditionally (crashes on empty body). The generator must
// emit a status check and return undefined for 204.

describe('204 no-content guard (issue #272)', () => {
  it('operation with 200 body + 204 emits undefined return type union', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items/{id}': {
          delete: {
            operationId: 'deleteItem',
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '200': {
                description: 'error info',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
              },
              '204': { description: 'no content' },
            },
          },
        },
      },
      components: {
        schemas: {
          ErrorResponse: {
            type: 'object',
            properties: { message: { type: 'string' } },
          },
        },
      },
    }
    const out = generateClient(spec).content
    // Return type must be union with undefined
    expect(out).toContain('Promise<ErrorResponse | undefined>')
    // Must not call res.json() without first guarding against 204
    expect(out).toContain('if (res.status === 204) return undefined')
    // The guard must appear before res.json()
    const guardIdx = out.indexOf('if (res.status === 204) return undefined')
    const jsonIdx = out.indexOf('return res.json()')
    expect(guardIdx).toBeLessThan(jsonIdx)
  })

  it('operation with 200 body + 204 does not crash on 204 at runtime', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items/{id}': {
          delete: {
            operationId: 'deleteItem',
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '200': {
                description: 'error info',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
              },
              '204': { description: 'no content' },
            },
          },
        },
      },
      components: {
        schemas: {
          ErrorResponse: {
            type: 'object',
            properties: { message: { type: 'string' } },
          },
        },
      },
    }
    const out = generateClient(spec).content
    // The guard must be present so a real 204 returns undefined instead of throwing
    expect(out).toContain('if (res.status === 204) return undefined')
    // res.json() must still be present for the 200 case
    expect(out).toContain('return res.json()')
  })

  it('204-only operation still returns Promise<void> and does not call res.json()', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items/{id}': {
          delete: {
            operationId: 'deleteItem',
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '204': { description: 'deleted' },
            },
          },
        },
      },
    }
    const out = generateClient(spec).content
    expect(out).toContain('Promise<void>')
    // 204-only: no res captured, no res.json() call
    const fnMatch = out.match(/export async function deleteItem[\s\S]*?^\}/m)
    expect(fnMatch).toBeTruthy()
    expect(fnMatch![0]).not.toContain('res.json()')
    expect(fnMatch![0]).not.toContain('const res =')
  })

  it('operation with 200 body + 204 compiles without TypeScript errors', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/items/{id}': {
          delete: {
            operationId: 'deleteItem',
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: {
              '200': {
                description: 'error info',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
              },
              '204': { description: 'no content' },
            },
          },
        },
      },
      components: {
        schemas: {
          ErrorResponse: {
            type: 'object',
            properties: { message: { type: 'string' } },
          },
        },
      },
    }
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content
    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
    })
    expect(diagnostics.length).toBe(0)
  })
})
