import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it, expect } from 'vitest'
import type { OpenAPIV3_1 } from 'openapi-types'
import { generateHandlers } from '../plugins/handlers.js'

const fixturePath = join(import.meta.dirname, '../__fixtures__/specs/task-api.json')
const spec = JSON.parse(readFileSync(fixturePath, 'utf-8')) as OpenAPIV3_1.Document

const DEFAULT_OPTS = { seed: 42, maxArrayItems: 3, depthCap: 30 }

const { filename, content } = generateHandlers(spec, DEFAULT_OPTS)

describe('generateHandlers: task-api.json fixture', () => {
  it('filename is handlers.ts', () => {
    expect(filename).toBe('handlers.ts')
  })

  it('contains auto-generated header comment', () => {
    expect(content).toContain(
      '// This file is auto-generated by @codewithagents/openapi-msw, do not edit'
    )
  })

  it('imports http and HttpResponse from msw', () => {
    expect(content).toContain("import { http, HttpResponse } from 'msw'")
  })

  it('imports faker from @faker-js/faker', () => {
    expect(content).toContain("import { faker } from '@faker-js/faker'")
  })

  it('emits faker.seed() call at top level', () => {
    expect(content).toContain('faker.seed(42)')
  })

  it('exports const handlers array', () => {
    expect(content).toContain('export const handlers = [')
  })

  it('generates http.get handler for listTasks', () => {
    expect(content).toContain("http.get('/api/v1/tasks'")
  })

  it('generates http.post handler for createTask', () => {
    expect(content).toContain("http.post('/api/v1/tasks'")
  })

  it('generates http.get handler for getTask with colon param', () => {
    expect(content).toContain("http.get('/api/v1/tasks/:id'")
  })

  it('generates http.put handler for updateTask', () => {
    expect(content).toContain("http.put('/api/v1/tasks/:id'")
  })

  it('generates http.delete handler for deleteTask', () => {
    expect(content).toContain("http.delete('/api/v1/tasks/:id'")
  })

  it('generates null response body for 204 delete operation', () => {
    // deleteTask returns 204 No Content, should emit null body
    expect(content).toContain('null, { status: 204 }')
  })

  it('generates HttpResponse.json with 201 status for createTask', () => {
    // createTask returns 201, should include status: 201
    expect(content).toContain('status: 201')
  })

  it('uses faker.string.uuid() for uuid format fields', () => {
    expect(content).toContain('faker.string.uuid()')
  })

  it('uses faker.date.recent().toISOString() for date-time fields', () => {
    expect(content).toContain('faker.date.recent().toISOString()')
  })

  it('uses faker.date.recent().toISOString().slice(0, 10) for date fields', () => {
    expect(content).toContain("faker.date.recent().toISOString().slice(0, 10)")
  })

  it('uses faker.internet.url() for uri format fields', () => {
    expect(content).toContain('faker.internet.url()')
  })

  it('uses faker.internet.email() for email format fields', () => {
    expect(content).toContain('faker.internet.email()')
  })

  it('uses faker.datatype.boolean() for boolean fields', () => {
    expect(content).toContain('faker.datatype.boolean()')
  })

  it('uses faker.number.int() for integer fields', () => {
    expect(content).toContain('faker.number.int(')
  })

  it('uses faker.number.float() for number fields', () => {
    expect(content).toContain('faker.number.float(')
  })

  it('uses Array.from for array type responses', () => {
    // listTasks returns array of Task
    expect(content).toContain('Array.from(')
  })

  it('uses faker.helpers.arrayElement for enum fields', () => {
    // TaskStatus is an enum
    expect(content).toContain('faker.helpers.arrayElement(')
    expect(content).toContain('"pending"')
    expect(content).toContain('"in_progress"')
    expect(content).toContain('"done"')
  })
})

describe('generateHandlers: seed option', () => {
  it('uses the configured seed value', () => {
    const { content: c } = generateHandlers(spec, { ...DEFAULT_OPTS, seed: 123 })
    expect(c).toContain('faker.seed(123)')
    expect(c).not.toContain('faker.seed(42)')
  })
})

describe('generateHandlers: maxArrayItems option', () => {
  it('uses maxArrayItems in Array.from length', () => {
    const { content: c } = generateHandlers(spec, { ...DEFAULT_OPTS, maxArrayItems: 5 })
    expect(c).toContain('length: 5')
  })
})

describe('generateHandlers: depth cap on circular schemas', () => {
  const circularSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Circular', version: '1.0.0' },
    paths: {
      '/nodes': {
        get: {
          operationId: 'listNodes',
          responses: {
            '200': {
              description: 'ok',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/Node' },
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        Node: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            child: { $ref: '#/components/schemas/Node' },
          },
        },
      },
    },
  }

  it('terminates circular reference with null comment', () => {
    const { content: c } = generateHandlers(circularSpec, { seed: 42, maxArrayItems: 3, depthCap: 2 })
    expect(c).toContain('null /* circular ref: depth cap reached */')
  })
})

describe('generateHandlers: allOf schema merging', () => {
  const allOfSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'AllOf', version: '1.0.0' },
    paths: {
      '/items': {
        get: {
          operationId: 'listItems',
          responses: {
            '200': {
              description: 'ok',
              content: {
                'application/json': {
                  schema: {
                    allOf: [
                      { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
                      { type: 'object', properties: { name: { type: 'string' } } },
                    ],
                  },
                },
              },
            },
          },
        },
      },
    },
  }

  it('merges allOf properties into one object', () => {
    const { content: c } = generateHandlers(allOfSpec, DEFAULT_OPTS)
    expect(c).toContain('faker.string.uuid()')
    expect(c).toContain('faker.lorem.word()')
  })
})

describe('generateHandlers: anyOf/oneOf picks first member', () => {
  const anyOfSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'AnyOf', version: '1.0.0' },
    paths: {
      '/things': {
        get: {
          operationId: 'listThings',
          responses: {
            '200': {
              description: 'ok',
              content: {
                'application/json': {
                  schema: {
                    anyOf: [
                      { type: 'string' },
                      { type: 'integer' },
                    ],
                  },
                },
              },
            },
          },
        },
      },
    },
  }

  it('picks first concrete member of anyOf', () => {
    const { content: c } = generateHandlers(anyOfSpec, DEFAULT_OPTS)
    expect(c).toContain('faker.lorem.word()')
  })
})

describe('generateHandlers: operations without operationId', () => {
  const noOpIdSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'NoOpId', version: '1.0.0' },
    paths: {
      '/widgets': {
        get: {
          responses: {
            '200': {
              description: 'ok',
              content: {
                'application/json': {
                  schema: { type: 'array', items: { type: 'string' } },
                },
              },
            },
          },
        },
      },
    },
  }

  it('generates a handler even without operationId', () => {
    const { content: c } = generateHandlers(noOpIdSpec, DEFAULT_OPTS)
    expect(c).toContain("http.get('/widgets'")
  })
})

describe('generateHandlers: path param conversion', () => {
  it('converts {param} to :param in MSW path', () => {
    const { content: c } = generateHandlers(spec, DEFAULT_OPTS)
    expect(c).toContain('/api/v1/tasks/:id')
    expect(c).not.toContain('{id}')
  })

  it('converts multiple path params', () => {
    const multiParamSpec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'Multi', version: '1.0.0' },
      paths: {
        '/orgs/{orgId}/repos/{repoId}': {
          get: {
            operationId: 'getRepo',
            parameters: [
              { name: 'orgId', in: 'path', required: true, schema: { type: 'string' } },
              { name: 'repoId', in: 'path', required: true, schema: { type: 'string' } },
            ],
            responses: { '200': { description: 'ok' } },
          },
        },
      },
    }
    const { content: c } = generateHandlers(multiParamSpec, DEFAULT_OPTS)
    expect(c).toContain('/orgs/:orgId/repos/:repoId')
  })
})

describe('generateHandlers: non-JSON content type responses', () => {
  const binarySpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Binary', version: '1.0.0' },
    paths: {
      '/export': {
        get: {
          operationId: 'exportData',
          responses: {
            '200': {
              description: 'CSV export',
              content: {
                'text/csv': {
                  schema: { type: 'string' },
                },
              },
            },
          },
        },
      },
    },
  }

  it('emits new HttpResponse() instead of HttpResponse.json() for non-JSON content types', () => {
    const { content: c } = generateHandlers(binarySpec, DEFAULT_OPTS)
    expect(c).toContain('new HttpResponse(null,')
    expect(c).not.toContain('HttpResponse.json(null,')
  })
})
