// This file is auto-generated by @codewithagents/openapi-react-query — do not edit

import {
  queryOptions,
  useQuery,
  type UseQueryOptions,
  useMutation,
  type UseMutationOptions,
} from '@tanstack/react-query'
import {
  deleteBusinessLinesId,
  deleteDocumentsId,
  deleteTransferInstrumentsId,
  getBusinessLinesId,
  getDocumentsId,
  getLegalEntitiesId,
  getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference,
  getLegalEntitiesIdBusinessLines,
  getLegalEntitiesIdPciQuestionnaires,
  getLegalEntitiesIdPciQuestionnairesPciid,
  getLegalEntitiesIdTermsOfServiceAcceptanceInfos,
  getLegalEntitiesIdTermsOfServiceStatus,
  getThemes,
  getThemesId,
  getTransferInstrumentsId,
  patchBusinessLinesId,
  patchDocumentsId,
  patchLegalEntitiesId,
  patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid,
  patchTransferInstrumentsId,
  postBusinessLines,
  postDocuments,
  postLegalEntities,
  postLegalEntitiesIdCheckTaxElectronicDeliveryConsent,
  postLegalEntitiesIdCheckVerificationErrors,
  postLegalEntitiesIdConfirmDataReview,
  postLegalEntitiesIdOnboardingLinks,
  postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates,
  postLegalEntitiesIdPciQuestionnairesSignPciTemplates,
  postLegalEntitiesIdPciQuestionnairesSigningRequired,
  postLegalEntitiesIdRequestPeriodicReview,
  postLegalEntitiesIdSetTaxElectronicDeliveryConsent,
  postLegalEntitiesIdTermsOfService,
  postTransferInstruments,
  type ApiError,
} from './client.js'

// ── Query key factories ──────────────────────────────────────

export const businessLineKeys = {
  all: () => ['businessLines'] as const,
  detail: (id: Parameters<typeof getBusinessLinesId>[0]) => ['businessLines', id] as const,
}

export const documentKeys = {
  all: () => ['documents'] as const,
  detail: (
    id: Parameters<typeof getDocumentsId>[0],
    params?: Parameters<typeof getDocumentsId>[1]
  ) => ['documents', id, params] as const,
}

export const legalEntityKeys = {
  all: () => ['legalEntities'] as const,
  getLegalEntitiesId: (id: Parameters<typeof getLegalEntitiesId>[0]) =>
    ['legalEntities', 'getLegalEntitiesId', id] as const,
  getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference: (
    id: Parameters<
      typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
    >[0],
    termsofserviceacceptancereference: Parameters<
      typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
    >[1],
    params?: Parameters<
      typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
    >[2]
  ) =>
    [
      'legalEntities',
      'getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference',
      id,
      termsofserviceacceptancereference,
      params,
    ] as const,
  getLegalEntitiesIdBusinessLines: (id: Parameters<typeof getLegalEntitiesIdBusinessLines>[0]) =>
    ['legalEntities', 'getLegalEntitiesIdBusinessLines', id] as const,
  getLegalEntitiesIdPciQuestionnaires: (
    id: Parameters<typeof getLegalEntitiesIdPciQuestionnaires>[0]
  ) => ['legalEntities', 'getLegalEntitiesIdPciQuestionnaires', id] as const,
  getLegalEntitiesIdPciQuestionnairesPciid: (
    id: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[0],
    pciid: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[1]
  ) => ['legalEntities', 'getLegalEntitiesIdPciQuestionnairesPciid', id, pciid] as const,
  getLegalEntitiesIdTermsOfServiceAcceptanceInfos: (
    id: Parameters<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>[0]
  ) => ['legalEntities', 'getLegalEntitiesIdTermsOfServiceAcceptanceInfos', id] as const,
  getLegalEntitiesIdTermsOfServiceStatus: (
    id: Parameters<typeof getLegalEntitiesIdTermsOfServiceStatus>[0]
  ) => ['legalEntities', 'getLegalEntitiesIdTermsOfServiceStatus', id] as const,
}

export const themeKeys = {
  all: () => ['themes'] as const,
  list: () => ['themes', 'list'] as const,
  detail: (id: Parameters<typeof getThemesId>[0]) => ['themes', id] as const,
}

export const transferInstrumentKeys = {
  all: () => ['transferInstruments'] as const,
  detail: (id: Parameters<typeof getTransferInstrumentsId>[0]) =>
    ['transferInstruments', id] as const,
}

// ── Query options factories ──────────────────────────────────

export function getBusinessLinesIdQueryOptions(
  id: Parameters<typeof getBusinessLinesId>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBusinessLinesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getBusinessLinesId>>, ApiError>({
    queryKey: businessLineKeys.detail(id),
    queryFn: () => getBusinessLinesId(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDocumentsIdQueryOptions(
  id: Parameters<typeof getDocumentsId>[0],
  params?: Parameters<typeof getDocumentsId>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDocumentsId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDocumentsId>>, ApiError>({
    queryKey: documentKeys.detail(id, params),
    queryFn: () => getDocumentsId(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdQueryOptions(
  id: Parameters<typeof getLegalEntitiesId>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLegalEntitiesId>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesId(id),
    queryFn: () => getLegalEntitiesId(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereferenceQueryOptions(
  id: Parameters<
    typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
  >[0],
  termsofserviceacceptancereference: Parameters<
    typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
  >[1],
  params?: Parameters<
    typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
  >[2],
  options?: Omit<
    UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
        >
      >,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<
      ReturnType<
        typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
      >
    >,
    ApiError
  >({
    queryKey:
      legalEntityKeys.getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference(
        id,
        termsofserviceacceptancereference,
        params
      ),
    queryFn: () =>
      getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference(
        id,
        termsofserviceacceptancereference,
        params
      ),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdBusinessLinesQueryOptions(
  id: Parameters<typeof getLegalEntitiesIdBusinessLines>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdBusinessLines>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdBusinessLines>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdBusinessLines(id),
    queryFn: () => getLegalEntitiesIdBusinessLines(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdPciQuestionnairesQueryOptions(
  id: Parameters<typeof getLegalEntitiesIdPciQuestionnaires>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnaires>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnaires>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdPciQuestionnaires(id),
    queryFn: () => getLegalEntitiesIdPciQuestionnaires(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdPciQuestionnairesPciidQueryOptions(
  id: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[0],
  pciid: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnairesPciid>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnairesPciid>>,
    ApiError
  >({
    queryKey: legalEntityKeys.getLegalEntitiesIdPciQuestionnairesPciid(id, pciid),
    queryFn: () => getLegalEntitiesIdPciQuestionnairesPciid(id, pciid),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdTermsOfServiceAcceptanceInfosQueryOptions(
  id: Parameters<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>[0],
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>>,
    ApiError
  >({
    queryKey: legalEntityKeys.getLegalEntitiesIdTermsOfServiceAcceptanceInfos(id),
    queryFn: () => getLegalEntitiesIdTermsOfServiceAcceptanceInfos(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getLegalEntitiesIdTermsOfServiceStatusQueryOptions(
  id: Parameters<typeof getLegalEntitiesIdTermsOfServiceStatus>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceStatus>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceStatus>>, ApiError>(
    {
      queryKey: legalEntityKeys.getLegalEntitiesIdTermsOfServiceStatus(id),
      queryFn: () => getLegalEntitiesIdTermsOfServiceStatus(id),
      staleTime: 0,
      gcTime: 300000,
      ...options,
    }
  )
}

export function getThemesQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getThemes>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getThemes>>, ApiError>({
    queryKey: themeKeys.list(),
    queryFn: () => getThemes(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getThemesIdQueryOptions(
  id: Parameters<typeof getThemesId>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getThemesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getThemesId>>, ApiError>({
    queryKey: themeKeys.detail(id),
    queryFn: () => getThemesId(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTransferInstrumentsIdQueryOptions(
  id: Parameters<typeof getTransferInstrumentsId>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTransferInstrumentsId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTransferInstrumentsId>>, ApiError>({
    queryKey: transferInstrumentKeys.detail(id),
    queryFn: () => getTransferInstrumentsId(id),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Queries ──────────────────────────────────────────────────

export function useGetBusinessLinesId(
  id: Parameters<typeof getBusinessLinesId>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBusinessLinesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getBusinessLinesId>>, ApiError>({
    queryKey: businessLineKeys.detail(id!),
    queryFn: () => getBusinessLinesId(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDocumentsId(
  id: Parameters<typeof getDocumentsId>[0] | undefined | null,
  params?: Parameters<typeof getDocumentsId>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDocumentsId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDocumentsId>>, ApiError>({
    queryKey: documentKeys.detail(id!, params),
    queryFn: () => getDocumentsId(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesId(
  id: Parameters<typeof getLegalEntitiesId>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLegalEntitiesId>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesId(id!),
    queryFn: () => getLegalEntitiesId(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference(
  id:
    | Parameters<
        typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
      >[0]
    | undefined
    | null,
  termsofserviceacceptancereference:
    | Parameters<
        typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
      >[1]
    | undefined
    | null,
  params?: Parameters<
    typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
  >[2],
  options?: Omit<
    UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
        >
      >,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<
    Awaited<
      ReturnType<
        typeof getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference
      >
    >,
    ApiError
  >({
    queryKey:
      legalEntityKeys.getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference(
        id!,
        termsofserviceacceptancereference!,
        params
      ),
    queryFn: () =>
      getLegalEntitiesIdAcceptedTermsOfServiceDocumentTermsofserviceacceptancereference(
        id!,
        termsofserviceacceptancereference!,
        params
      ),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && termsofserviceacceptancereference != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdBusinessLines(
  id: Parameters<typeof getLegalEntitiesIdBusinessLines>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdBusinessLines>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLegalEntitiesIdBusinessLines>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdBusinessLines(id!),
    queryFn: () => getLegalEntitiesIdBusinessLines(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdPciQuestionnaires(
  id: Parameters<typeof getLegalEntitiesIdPciQuestionnaires>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnaires>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnaires>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdPciQuestionnaires(id!),
    queryFn: () => getLegalEntitiesIdPciQuestionnaires(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdPciQuestionnairesPciid(
  id: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[0] | undefined | null,
  pciid: Parameters<typeof getLegalEntitiesIdPciQuestionnairesPciid>[1] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnairesPciid>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLegalEntitiesIdPciQuestionnairesPciid>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdPciQuestionnairesPciid(id!, pciid!),
    queryFn: () => getLegalEntitiesIdPciQuestionnairesPciid(id!, pciid!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && pciid != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdTermsOfServiceAcceptanceInfos(
  id: Parameters<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<
    Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceAcceptanceInfos>>,
    ApiError
  >({
    queryKey: legalEntityKeys.getLegalEntitiesIdTermsOfServiceAcceptanceInfos(id!),
    queryFn: () => getLegalEntitiesIdTermsOfServiceAcceptanceInfos(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetLegalEntitiesIdTermsOfServiceStatus(
  id: Parameters<typeof getLegalEntitiesIdTermsOfServiceStatus>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceStatus>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getLegalEntitiesIdTermsOfServiceStatus>>, ApiError>({
    queryKey: legalEntityKeys.getLegalEntitiesIdTermsOfServiceStatus(id!),
    queryFn: () => getLegalEntitiesIdTermsOfServiceStatus(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetThemes(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getThemes>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getThemes>>, ApiError>({
    queryKey: themeKeys.list(),
    queryFn: () => getThemes(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetThemesId(
  id: Parameters<typeof getThemesId>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getThemesId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getThemesId>>, ApiError>({
    queryKey: themeKeys.detail(id!),
    queryFn: () => getThemesId(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetTransferInstrumentsId(
  id: Parameters<typeof getTransferInstrumentsId>[0] | undefined | null,
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTransferInstrumentsId>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTransferInstrumentsId>>, ApiError>({
    queryKey: transferInstrumentKeys.detail(id!),
    queryFn: () => getTransferInstrumentsId(id!),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

// ── Mutations ────────────────────────────────────────────────

export function usePostBusinessLines(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postBusinessLines>>,
      ApiError,
      Parameters<typeof postBusinessLines>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postBusinessLines>>,
    ApiError,
    Parameters<typeof postBusinessLines>[0]
  >({
    mutationFn: (vars) => postBusinessLines(vars),
    ...options,
  })
}

export function usePatchBusinessLinesId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchBusinessLinesId>>,
      ApiError,
      {
        id: Parameters<typeof patchBusinessLinesId>[0]
        body: Parameters<typeof patchBusinessLinesId>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchBusinessLinesId>>,
    ApiError,
    {
      id: Parameters<typeof patchBusinessLinesId>[0]
      body: Parameters<typeof patchBusinessLinesId>[1]
    }
  >({
    mutationFn: ({ id, body }) => patchBusinessLinesId(id, body),
    ...options,
  })
}

export function useDeleteBusinessLinesId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteBusinessLinesId>>,
      ApiError,
      Parameters<typeof deleteBusinessLinesId>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteBusinessLinesId>>,
    ApiError,
    Parameters<typeof deleteBusinessLinesId>[0]
  >({
    mutationFn: (id) => deleteBusinessLinesId(id),
    ...options,
  })
}

export function usePostDocuments(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postDocuments>>,
      ApiError,
      { body: Parameters<typeof postDocuments>[0]; params: Parameters<typeof postDocuments>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postDocuments>>,
    ApiError,
    { body: Parameters<typeof postDocuments>[0]; params: Parameters<typeof postDocuments>[1] }
  >({
    mutationFn: ({ body, params }) => postDocuments(body, params),
    ...options,
  })
}

export function usePatchDocumentsId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchDocumentsId>>,
      ApiError,
      {
        id: Parameters<typeof patchDocumentsId>[0]
        body: Parameters<typeof patchDocumentsId>[1]
        params: Parameters<typeof patchDocumentsId>[2]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchDocumentsId>>,
    ApiError,
    {
      id: Parameters<typeof patchDocumentsId>[0]
      body: Parameters<typeof patchDocumentsId>[1]
      params: Parameters<typeof patchDocumentsId>[2]
    }
  >({
    mutationFn: ({ id, body, params }) => patchDocumentsId(id, body, params),
    ...options,
  })
}

export function useDeleteDocumentsId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteDocumentsId>>,
      ApiError,
      Parameters<typeof deleteDocumentsId>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteDocumentsId>>,
    ApiError,
    Parameters<typeof deleteDocumentsId>[0]
  >({
    mutationFn: (id) => deleteDocumentsId(id),
    ...options,
  })
}

export function usePostLegalEntities(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntities>>,
      ApiError,
      {
        body: Parameters<typeof postLegalEntities>[0]
        params: Parameters<typeof postLegalEntities>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntities>>,
    ApiError,
    {
      body: Parameters<typeof postLegalEntities>[0]
      params: Parameters<typeof postLegalEntities>[1]
    }
  >({
    mutationFn: ({ body, params }) => postLegalEntities(body, params),
    ...options,
  })
}

export function usePatchLegalEntitiesId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchLegalEntitiesId>>,
      ApiError,
      {
        id: Parameters<typeof patchLegalEntitiesId>[0]
        body: Parameters<typeof patchLegalEntitiesId>[1]
        params: Parameters<typeof patchLegalEntitiesId>[2]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchLegalEntitiesId>>,
    ApiError,
    {
      id: Parameters<typeof patchLegalEntitiesId>[0]
      body: Parameters<typeof patchLegalEntitiesId>[1]
      params: Parameters<typeof patchLegalEntitiesId>[2]
    }
  >({
    mutationFn: ({ id, body, params }) => patchLegalEntitiesId(id, body, params),
    ...options,
  })
}

export function usePostLegalEntitiesIdCheckTaxElectronicDeliveryConsent(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdCheckTaxElectronicDeliveryConsent>>,
      ApiError,
      Parameters<typeof postLegalEntitiesIdCheckTaxElectronicDeliveryConsent>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdCheckTaxElectronicDeliveryConsent>>,
    ApiError,
    Parameters<typeof postLegalEntitiesIdCheckTaxElectronicDeliveryConsent>[0]
  >({
    mutationFn: (id) => postLegalEntitiesIdCheckTaxElectronicDeliveryConsent(id),
    ...options,
  })
}

export function usePostLegalEntitiesIdCheckVerificationErrors(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdCheckVerificationErrors>>,
      ApiError,
      Parameters<typeof postLegalEntitiesIdCheckVerificationErrors>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdCheckVerificationErrors>>,
    ApiError,
    Parameters<typeof postLegalEntitiesIdCheckVerificationErrors>[0]
  >({
    mutationFn: (id) => postLegalEntitiesIdCheckVerificationErrors(id),
    ...options,
  })
}

export function usePostLegalEntitiesIdConfirmDataReview(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdConfirmDataReview>>,
      ApiError,
      Parameters<typeof postLegalEntitiesIdConfirmDataReview>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdConfirmDataReview>>,
    ApiError,
    Parameters<typeof postLegalEntitiesIdConfirmDataReview>[0]
  >({
    mutationFn: (id) => postLegalEntitiesIdConfirmDataReview(id),
    ...options,
  })
}

export function usePostLegalEntitiesIdOnboardingLinks(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdOnboardingLinks>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdOnboardingLinks>[0]
        body: Parameters<typeof postLegalEntitiesIdOnboardingLinks>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdOnboardingLinks>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdOnboardingLinks>[0]
      body: Parameters<typeof postLegalEntitiesIdOnboardingLinks>[1]
    }
  >({
    mutationFn: ({ id, body }) => postLegalEntitiesIdOnboardingLinks(id, body),
    ...options,
  })
}

export function usePostLegalEntitiesIdPciQuestionnairesGeneratePciTemplates(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>[0]
        body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>[0]
      body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates>[1]
    }
  >({
    mutationFn: ({ id, body }) =>
      postLegalEntitiesIdPciQuestionnairesGeneratePciTemplates(id, body),
    ...options,
  })
}

export function usePostLegalEntitiesIdPciQuestionnairesSignPciTemplates(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>[0]
        body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>[0]
      body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSignPciTemplates>[1]
    }
  >({
    mutationFn: ({ id, body }) => postLegalEntitiesIdPciQuestionnairesSignPciTemplates(id, body),
    ...options,
  })
}

export function usePostLegalEntitiesIdPciQuestionnairesSigningRequired(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>[0]
        body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>[0]
      body: Parameters<typeof postLegalEntitiesIdPciQuestionnairesSigningRequired>[1]
    }
  >({
    mutationFn: ({ id, body }) => postLegalEntitiesIdPciQuestionnairesSigningRequired(id, body),
    ...options,
  })
}

export function usePostLegalEntitiesIdSetTaxElectronicDeliveryConsent(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>[0]
        body: Parameters<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>[0]
      body: Parameters<typeof postLegalEntitiesIdSetTaxElectronicDeliveryConsent>[1]
    }
  >({
    mutationFn: ({ id, body }) => postLegalEntitiesIdSetTaxElectronicDeliveryConsent(id, body),
    ...options,
  })
}

export function usePostLegalEntitiesIdTermsOfService(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdTermsOfService>>,
      ApiError,
      {
        id: Parameters<typeof postLegalEntitiesIdTermsOfService>[0]
        body: Parameters<typeof postLegalEntitiesIdTermsOfService>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdTermsOfService>>,
    ApiError,
    {
      id: Parameters<typeof postLegalEntitiesIdTermsOfService>[0]
      body: Parameters<typeof postLegalEntitiesIdTermsOfService>[1]
    }
  >({
    mutationFn: ({ id, body }) => postLegalEntitiesIdTermsOfService(id, body),
    ...options,
  })
}

export function usePatchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>>,
      ApiError,
      {
        id: Parameters<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>[0]
        termsofservicedocumentid: Parameters<
          typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid
        >[1]
        body: Parameters<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>[2]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>>,
    ApiError,
    {
      id: Parameters<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>[0]
      termsofservicedocumentid: Parameters<
        typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid
      >[1]
      body: Parameters<typeof patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid>[2]
    }
  >({
    mutationFn: ({ id, termsofservicedocumentid, body }) =>
      patchLegalEntitiesIdTermsOfServiceTermsofservicedocumentid(
        id,
        termsofservicedocumentid,
        body
      ),
    ...options,
  })
}

export function usePostTransferInstruments(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postTransferInstruments>>,
      ApiError,
      {
        body: Parameters<typeof postTransferInstruments>[0]
        params: Parameters<typeof postTransferInstruments>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postTransferInstruments>>,
    ApiError,
    {
      body: Parameters<typeof postTransferInstruments>[0]
      params: Parameters<typeof postTransferInstruments>[1]
    }
  >({
    mutationFn: ({ body, params }) => postTransferInstruments(body, params),
    ...options,
  })
}

export function usePatchTransferInstrumentsId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof patchTransferInstrumentsId>>,
      ApiError,
      {
        id: Parameters<typeof patchTransferInstrumentsId>[0]
        body: Parameters<typeof patchTransferInstrumentsId>[1]
        params: Parameters<typeof patchTransferInstrumentsId>[2]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof patchTransferInstrumentsId>>,
    ApiError,
    {
      id: Parameters<typeof patchTransferInstrumentsId>[0]
      body: Parameters<typeof patchTransferInstrumentsId>[1]
      params: Parameters<typeof patchTransferInstrumentsId>[2]
    }
  >({
    mutationFn: ({ id, body, params }) => patchTransferInstrumentsId(id, body, params),
    ...options,
  })
}

export function useDeleteTransferInstrumentsId(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteTransferInstrumentsId>>,
      ApiError,
      Parameters<typeof deleteTransferInstrumentsId>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteTransferInstrumentsId>>,
    ApiError,
    Parameters<typeof deleteTransferInstrumentsId>[0]
  >({
    mutationFn: (id) => deleteTransferInstrumentsId(id),
    ...options,
  })
}

export function usePostLegalEntitiesIdRequestPeriodicReview(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postLegalEntitiesIdRequestPeriodicReview>>,
      ApiError,
      Parameters<typeof postLegalEntitiesIdRequestPeriodicReview>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postLegalEntitiesIdRequestPeriodicReview>>,
    ApiError,
    Parameters<typeof postLegalEntitiesIdRequestPeriodicReview>[0]
  >({
    mutationFn: (id) => postLegalEntitiesIdRequestPeriodicReview(id),
    ...options,
  })
}
