// This file is auto-generated by @codewithagents/openapi-gen — do not edit

export interface ClientConfig {
  /** Base URL for all API requests (e.g. 'https://api.example.com') */
  baseUrl: string
  /**
   * Bearer token or a function that returns one (supports async refresh).
   * When provided, adds `Authorization: Bearer <token>` to every request.
   */
  token?: string | (() => string | Promise<string>)
  /**
   * HTTP Basic credentials or a function that returns them.
   * When provided, adds `Authorization: Basic <base64(username:password)>` to every request.
   */
  basicAuth?:
    | { username: string; password: string }
    | (() =>
        | { username: string; password: string }
        | Promise<{ username: string; password: string }>)
  /**
   * Fetch credentials mode. Use 'include' for cookie-based auth.
   * Defaults to 'same-origin'.
   */
  credentials?: RequestCredentials
  /** Additional headers sent with every request */
  headers?: Record<string, string>
  /**
   * Global error hook called with every non-2xx response error before it is
   * thrown. Use for logging, monitoring, or triggering auth refresh flows.
   *
   * @example
   * configureClient({
   *   onError: (err) => Sentry.captureException(err),
   * })
   */
  onError?: (err: Error) => void
  /**
   * Default AbortSignal for every request. Useful for cancelling in-flight
   * requests (e.g. on route change). Overridable per call via the config param.
   */
  signal?: AbortSignal
  /**
   * Default timeout in milliseconds. When set, every request is aborted with a
   * TimeoutError after the specified duration. Overridable per call.
   */
  timeout?: number
  /**
   * Request interceptor called before every fetch. Receives the resolved URL and
   * RequestInit; may return an object with optional url/init overrides.
   *
   * @example
   * configureClient({
   *   onRequest: ({ url, init }) => ({ init: { ...init, headers: { ...init.headers, 'X-Request-Id': crypto.randomUUID() } } }),
   * })
   */
  onRequest?: (req: {
    url: string
    init: RequestInit
  }) =>
    | void
    | { url?: string; init?: RequestInit }
    | Promise<void | { url?: string; init?: RequestInit }>
  /**
   * Custom fetch implementation. Defaults to globalThis.fetch, resolved at
   * call time so test mocks of globalThis.fetch are always honoured.
   */
  fetch?: typeof globalThis.fetch
}

let _config: ClientConfig = {
  baseUrl: '',
  credentials: 'same-origin',
}

/** Configure the API client. Call once at app startup before making any requests. */
export function configureClient(config: ClientConfig): void {
  _config = { ..._config, ...config }
}

/** @internal — used by generated fetch functions */
export function getConfig(): Readonly<ClientConfig> {
  return _config
}
