// This file is auto-generated by openapi-zod-ts - do not edit

export type TicketType = 'event' | 'general'
export const TicketTypeValues = ['event', 'general'] as const

export type Date = string

export type Email = string

export type BuyMuseumTickets = {
  email?: Email
} & Ticket

export type TicketMessage = string

export type TicketId = string

export type TicketConfirmation = string

export interface Ticket {
  ticketId?: TicketId
  ticketDate: Date
  ticketType: TicketType
  eventId?: EventId
}

export type MuseumTicketsConfirmation = Ticket & {
  message: TicketMessage
  confirmationCode: TicketConfirmation
}

export type TicketCodeImage = string

export type MuseumHours = MuseumDailyHours[]

export interface MuseumDailyHours {
  date: Date
  timeOpen: string
  timeClose: string
}

export type EventId = string

export type EventName = string

export type EventLocation = string

export type EventDescription = string

export type EventDates = Date[]

export type EventPrice = number

export interface SpecialEventFields {
  name?: EventName
  location?: EventLocation
  eventDescription?: EventDescription
  dates?: EventDates
  price?: EventPrice
}

export interface SpecialEvent {
  eventId?: EventId
  name: EventName
  location: EventLocation
  eventDescription: EventDescription
  dates: EventDates
  price: EventPrice
}

export type SpecialEventCollection = SpecialEvent[]

export interface Error {
  type?: string
  title?: string
}
