// This file is auto-generated by openapi-zod-ts - do not edit

export interface LinkedTrackObject {
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  type?: string
  uri?: string
}

export interface TrackRestrictionObject {
  reason?: string
}

export interface AlbumRestrictionObject {
  reason?: 'market' | 'product' | 'explicit'
}

export interface EpisodeRestrictionObject {
  reason?: string
}

export interface ChapterRestrictionObject {
  reason?: string
}

export interface ArtistObject {
  external_urls?: ExternalUrlObject
  followers?: FollowersObject
  genres?: string[]
  href?: string
  id?: string
  images?: ImageObject[]
  name?: string
  popularity?: number
  type?: 'artist'
  uri?: string
}

export interface SimplifiedArtistObject {
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  name?: string
  type?: 'artist'
  uri?: string
}

export interface PlayHistoryObject {
  track?: TrackObject
  played_at?: string /* date-time */
  context?: ContextObject
}

export interface PlaylistTrackObject {
  added_at?: string /* date-time */
  added_by?: PlaylistUserObject
  is_local?: boolean
  item?: TrackObject | EpisodeObject
  track?: TrackObject | EpisodeObject
}

export interface QueueObject {
  currently_playing?: TrackObject | EpisodeObject
  queue?: TrackObject | EpisodeObject[]
}

export interface CurrentlyPlayingContextObject {
  device?: DeviceObject
  repeat_state?: string
  shuffle_state?: boolean
  context?: ContextObject
  timestamp?: number /* int64, precision limited to 2^53-1 */
  progress_ms?: number
  is_playing?: boolean
  item?: TrackObject | EpisodeObject
  currently_playing_type?: string
  actions?: DisallowsObject
}

export interface DisallowsObject {
  interrupting_playback?: boolean
  pausing?: boolean
  resuming?: boolean
  seeking?: boolean
  skipping_next?: boolean
  skipping_prev?: boolean
  toggling_repeat_context?: boolean
  toggling_shuffle?: boolean
  toggling_repeat_track?: boolean
  transferring_playback?: boolean
}

export interface ErrorObject {
  status: number
  message: string
}

export interface PrivateUserObject {
  country?: string
  display_name?: string
  email?: string
  explicit_content?: ExplicitContentSettingsObject
  external_urls?: ExternalUrlObject
  followers?: FollowersObject
  href?: string
  id?: string
  images?: ImageObject[]
  product?: string
  type?: string
  uri?: string
}

export interface PublicUserObject {
  display_name?: string | null
  external_urls?: ExternalUrlObject
  followers?: FollowersObject
  href?: string
  id?: string
  images?: ImageObject[]
  type?: 'user'
  uri?: string
}

export interface AudioAnalysisObject {
  meta?: {
    analyzer_version?: string
    platform?: string
    detailed_status?: string
    status_code?: number
    timestamp?: number /* int64, precision limited to 2^53-1 */
    analysis_time?: number
    input_process?: string
  }
  track?: {
    num_samples?: number
    duration?: number
    sample_md5?: string
    offset_seconds?: number
    window_seconds?: number
    analysis_sample_rate?: number
    analysis_channels?: number
    end_of_fade_in?: number
    start_of_fade_out?: number
    loudness?: Loudness
    tempo?: Tempo
    tempo_confidence?: number
    time_signature?: TimeSignature
    time_signature_confidence?: number
    key?: Key
    key_confidence?: number
    mode?: Mode
    mode_confidence?: number
    codestring?: string
    code_version?: number
    echoprintstring?: string
    echoprint_version?: number
    synchstring?: string
    synch_version?: number
    rhythmstring?: string
    rhythm_version?: number
  }
  bars?: TimeIntervalObject[]
  beats?: TimeIntervalObject[]
  sections?: SectionObject[]
  segments?: SegmentObject[]
  tatums?: TimeIntervalObject[]
}

export interface TimeIntervalObject {
  start?: number
  duration?: number
  confidence?: number
}

export interface SectionObject {
  start?: number
  duration?: number
  confidence?: number
  loudness?: number
  tempo?: number
  tempo_confidence?: number
  key?: number
  key_confidence?: number
  mode?: -1 | 0 | 1
  mode_confidence?: number
  time_signature?: TimeSignature
  time_signature_confidence?: number
}

export interface SegmentObject {
  start?: number
  duration?: number
  confidence?: number
  loudness_start?: number
  loudness_max?: number
  loudness_max_time?: number
  loudness_end?: number
  pitches?: number[]
  timbre?: number[]
}

export type TimeSignature = number

export type Tempo = number

export type Loudness = number

export type Key = number

export type Mode = number

export interface AudioFeaturesObject {
  acousticness?: number
  analysis_url?: string
  danceability?: number
  duration_ms?: number
  energy?: number
  id?: string
  instrumentalness?: number
  key?: Key
  liveness?: number
  loudness?: Loudness
  mode?: Mode
  speechiness?: number
  tempo?: Tempo
  time_signature?: TimeSignature
  track_href?: string
  type?: 'audio_features'
  uri?: string
  valence?: number
}

export interface SimplifiedTrackObject {
  artists?: SimplifiedArtistObject[]
  available_markets?: string[]
  disc_number?: number
  duration_ms?: number
  explicit?: boolean
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  is_playable?: boolean
  linked_from?: LinkedTrackObject
  restrictions?: TrackRestrictionObject
  name?: string
  preview_url?: string | null
  track_number?: number
  type?: string
  uri?: string
  is_local?: boolean
}

export interface DeviceObject {
  id?: string | null
  is_active?: boolean
  is_private_session?: boolean
  is_restricted?: boolean
  name?: string
  type?: string
  volume_percent?: number | null
  supports_volume?: boolean
}

export interface CursorObject {
  after?: string
  before?: string
}

export interface CursorPagingObject {
  href?: string
  limit?: number
  next?: string
  cursors?: CursorObject
  total?: number
}

export type CursorPagingPlayHistoryObject = CursorPagingObject & {
  items?: PlayHistoryObject[]
}

export type CursorPagingSimplifiedArtistObject = CursorPagingObject & {
  items?: ArtistObject[]
}

export interface PagingObject {
  href: string
  limit: number
  next: string | null
  offset: number
  previous: string | null
  total: number
}

export type PagingPlaylistObject = PagingObject & {
  items?: SimplifiedPlaylistObject[]
}

export interface PagingFeaturedPlaylistObject {
  message?: string
  playlists?: PagingPlaylistObject
}

export type PagingArtistDiscographyAlbumObject = PagingObject & {
  items?: ArtistDiscographyAlbumObject[]
}

export type PagingSimplifiedAlbumObject = PagingObject & {
  items?: SimplifiedAlbumObject[]
}

export type PagingSavedAlbumObject = PagingObject & {
  items?: SavedAlbumObject[]
}

export type PagingSimplifiedTrackObject = PagingObject & {
  items?: SimplifiedTrackObject[]
}

export type PagingSavedTrackObject = PagingObject & {
  items?: SavedTrackObject[]
}

export type PagingTrackObject = PagingObject & {
  items?: TrackObject[]
}

export type PagingPlaylistTrackObject = PagingObject & {
  items?: PlaylistTrackObject[]
}

export type PagingSimplifiedShowObject = PagingObject & {
  items?: SimplifiedShowObject[]
}

export type PagingSavedShowObject = PagingObject & {
  items?: SavedShowObject[]
}

export type PagingSimplifiedEpisodeObject = PagingObject & {
  items?: SimplifiedEpisodeObject[]
}

export type PagingSavedEpisodeObject = PagingObject & {
  items?: SavedEpisodeObject[]
}

export type PagingSimplifiedAudiobookObject = PagingObject & {
  items?: SimplifiedAudiobookObject[]
}

export type PagingArtistObject = PagingObject & {
  items?: ArtistObject[]
}

export type PagingSimplifiedChapterObject = PagingObject & {
  items?: SimplifiedChapterObject[]
}

export interface RecommendationsObject {
  seeds: RecommendationSeedObject[]
  tracks: TrackObject[]
}

export interface RecommendationSeedObject {
  afterFilteringSize?: number
  afterRelinkingSize?: number
  href?: string
  id?: string
  initialPoolSize?: number
  type?: string
}

export interface SavedAlbumObject {
  added_at?: string /* date-time */
  album?: AlbumObject
}

export interface SavedTrackObject {
  added_at?: string /* date-time */
  track?: TrackObject
}

export interface SavedEpisodeObject {
  added_at?: string /* date-time */
  episode?: EpisodeObject
}

export interface SavedShowObject {
  added_at?: string /* date-time */
  show?: SimplifiedShowObject
}

export interface PlaylistObject {
  collaborative?: boolean
  description?: string | null
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  images?: ImageObject[]
  name?: string
  owner?: PlaylistOwnerObject
  public?: boolean
  snapshot_id?: string
  items?: PagingPlaylistTrackObject
  tracks?: PagingPlaylistTrackObject
  type?: string
  uri?: string
  followers?: FollowersObject
}

export interface SimplifiedPlaylistObject {
  collaborative?: boolean
  description?: string
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  images?: ImageObject[]
  name?: string
  owner?: PlaylistOwnerObject
  public?: boolean
  snapshot_id?: string
  items?: PlaylistTracksRefObject
  tracks?: PlaylistTracksRefObject
  type?: string
  uri?: string
}

export interface PlaylistTracksRefObject {
  href?: string
  total?: number
}

export interface PlaylistUserObject {
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  type?: 'user'
  uri?: string
}

export type PlaylistOwnerObject = PlaylistUserObject & {
  display_name?: string | null
}

export interface CategoryObject {
  href: string
  icons: ImageObject[]
  id: string
  name: string
}

export interface TrackObject {
  album?: SimplifiedAlbumObject
  artists?: SimplifiedArtistObject[]
  available_markets?: string[]
  disc_number?: number
  duration_ms?: number
  explicit?: boolean
  external_ids?: ExternalIdObject
  external_urls?: ExternalUrlObject
  href?: string
  id?: string
  is_playable?: boolean
  linked_from?: LinkedTrackObject
  restrictions?: TrackRestrictionObject
  name?: string
  popularity?: number
  preview_url?: string | null
  track_number?: number
  type?: 'track'
  uri?: string
  is_local?: boolean
}

export type EpisodeObject = EpisodeBase & {
  show: SimplifiedShowObject
}

export type SimplifiedEpisodeObject = EpisodeBase

export interface EpisodeBase {
  audio_preview_url: string | null
  description: string
  html_description: string
  duration_ms: number
  explicit: boolean
  external_urls: ExternalUrlObject
  href: string
  id: string
  images: ImageObject[]
  is_externally_hosted: boolean
  is_playable: boolean
  language?: string
  languages: string[]
  name: string
  release_date: string
  release_date_precision: 'year' | 'month' | 'day'
  resume_point?: ResumePointObject
  type: 'episode'
  uri: string
  restrictions?: EpisodeRestrictionObject
}

export interface ResumePointObject {
  fully_played?: boolean
  resume_position_ms?: number
}

export interface ShowBase {
  available_markets: string[]
  copyrights: CopyrightObject[]
  description: string
  html_description: string
  explicit: boolean
  external_urls: ExternalUrlObject
  href: string
  id: string
  images: ImageObject[]
  is_externally_hosted: boolean
  languages: string[]
  media_type: string
  name: string
  publisher: string
  type: 'show'
  uri: string
  total_episodes: number
}

export type ShowObject = ShowBase & {
  episodes: PagingSimplifiedEpisodeObject
}

export type SimplifiedShowObject = ShowBase

export interface AudiobookBase {
  authors: AuthorObject[]
  available_markets: string[]
  copyrights: CopyrightObject[]
  description: string
  html_description: string
  edition?: string
  explicit: boolean
  external_urls: ExternalUrlObject
  href: string
  id: string
  images: ImageObject[]
  languages: string[]
  media_type: string
  name: string
  narrators: NarratorObject[]
  publisher: string
  type: 'audiobook'
  uri: string
  total_chapters: number
}

export type AudiobookObject = AudiobookBase & {
  chapters: PagingSimplifiedChapterObject
}

export type SimplifiedAudiobookObject = AudiobookBase

export interface AlbumBase {
  album_type: 'album' | 'single' | 'compilation'
  total_tracks: number
  available_markets: string[]
  external_urls: ExternalUrlObject
  href: string
  id: string
  images: ImageObject[]
  name: string
  release_date: string
  release_date_precision: 'year' | 'month' | 'day'
  restrictions?: AlbumRestrictionObject
  type: 'album'
  uri: string
}

export type SimplifiedAlbumObject = AlbumBase & {
  artists: SimplifiedArtistObject[]
}

export type ArtistDiscographyAlbumObject = SimplifiedAlbumObject & {
  album_group: 'album' | 'single' | 'compilation' | 'appears_on'
}

export type ChapterObject = ChapterBase & {
  audiobook: SimplifiedAudiobookObject
}

export type SimplifiedChapterObject = ChapterBase

export interface ChapterBase {
  audio_preview_url: string | null
  available_markets?: string[]
  chapter_number: number
  description: string
  html_description: string
  duration_ms: number
  explicit: boolean
  external_urls: ExternalUrlObject
  href: string
  id: string
  images: ImageObject[]
  is_playable: boolean
  languages: string[]
  name: string
  release_date: string
  release_date_precision: 'year' | 'month' | 'day'
  resume_point?: ResumePointObject
  type: 'episode'
  uri: string
  restrictions?: ChapterRestrictionObject
}

export type AlbumObject = AlbumBase & {
  artists?: SimplifiedArtistObject[]
  tracks?: PagingSimplifiedTrackObject
  copyrights?: CopyrightObject[]
  external_ids?: ExternalIdObject
  genres?: string[]
  label?: string
  popularity?: number
}

export interface ContextObject {
  type?: string
  href?: string
  external_urls?: ExternalUrlObject
  uri?: string
}

export interface CopyrightObject {
  text?: string
  type?: string
}

export interface AuthorObject {
  name?: string
}

export interface NarratorObject {
  name?: string
}

export interface ExternalIdObject {
  isrc?: string
  ean?: string
  upc?: string
}

export interface ExternalUrlObject {
  spotify?: string
}

export interface FollowersObject {
  href?: string | null
  total?: number
}

export interface ImageObject {
  url: string
  height: number | null
  width: number | null
}

export interface ExplicitContentSettingsObject {
  filter_enabled?: boolean
  filter_locked?: boolean
}

export interface CurrentlyPlayingObject {
  context?: ContextObject
  timestamp?: number /* int64, precision limited to 2^53-1 */
  progress_ms?: number
  is_playing?: boolean
  item?: TrackObject | EpisodeObject
  currently_playing_type?: string
  actions?: DisallowsObject
}

export interface SavedAudiobookObject {
  added_at?: string /* date-time */
  audiobook?: AudiobookObject
}

export type PagingSavedAudiobookObject = PagingObject & {
  items?: SavedAudiobookObject[]
}
