// This file is auto-generated by @codewithagents/openapi-gen - do not edit

export interface HourlyResponse {
  time: string[]
  temperature_2m?: number[]
  relative_humidity_2m?: number[]
  dew_point_2m?: number[]
  apparent_temperature?: number[]
  pressure_msl?: number[]
  cloud_cover?: number[]
  cloud_cover_low?: number[]
  cloud_cover_mid?: number[]
  cloud_cover_high?: number[]
  wind_speed_10m?: number[]
  wind_speed_80m?: number[]
  wind_speed_120m?: number[]
  wind_speed_180m?: number[]
  wind_direction_10m?: number[]
  wind_direction_80m?: number[]
  wind_direction_120m?: number[]
  wind_direction_180m?: number[]
  wind_gusts_10m?: number[]
  shortwave_radiation?: number[]
  direct_radiation?: number[]
  direct_normal_irradiance?: number[]
  diffuse_radiation?: number[]
  vapour_pressure_deficit?: number[]
  evapotranspiration?: number[]
  precipitation?: number[]
  weather_code?: number[]
  snow_height?: number[]
  freezing_level_height?: number[]
  soil_temperature_0cm?: number[]
  soil_temperature_6cm?: number[]
  soil_temperature_18cm?: number[]
  soil_temperature_54cm?: number[]
  soil_moisture_0_1cm?: number[]
  soil_moisture_1_3cm?: number[]
  soil_moisture_3_9cm?: number[]
  soil_moisture_9_27cm?: number[]
  soil_moisture_27_81cm?: number[]
}

export interface DailyResponse {
  time: string[]
  temperature_2m_max?: number[]
  temperature_2m_min?: number[]
  apparent_temperature_max?: number[]
  apparent_temperature_min?: number[]
  precipitation_sum?: number[]
  precipitation_hours?: number[]
  weather_code?: number[]
  sunrise?: number[]
  sunset?: number[]
  wind_speed_10m_max?: number[]
  wind_gusts_10m_max?: number[]
  wind_direction_10m_dominant?: number[]
  shortwave_radiation_sum?: number[]
  uv_index_max?: number[]
  uv_index_clear_sky_max?: number[]
  et0_fao_evapotranspiration?: number[]
}

export interface CurrentWeather {
  time: string
  temperature: number
  windspeed?: number
  winddirection?: number
  weather_code: number
}
