// This file is auto-generated by @codewithagents/openapi-react-query — do not edit

import {
  queryOptions,
  useQuery,
  type UseQueryOptions,
  useMutation,
  type UseMutationOptions,
} from '@tanstack/react-query'
import {
  addOrDeleteRules,
  createBatchComplianceJob,
  createTweet,
  deleteTweetById,
  dmConversationByIdEventIdCreate,
  dmConversationIdCreate,
  dmConversationWithUserEventIdCreate,
  findMyUser,
  findSpaceById,
  findSpacesByCreatorIds,
  findSpacesByIds,
  findTweetById,
  findTweetsById,
  findTweetsThatQuoteATweet,
  findUserById,
  findUserByUsername,
  findUsersById,
  findUsersByUsername,
  getBatchComplianceJob,
  getDmConversationsIdDmEvents,
  getDmConversationsWithParticipantIdDmEvents,
  getDmEvents,
  getOpenApiSpec,
  getRules,
  getTweetsComplianceStream,
  getTweetsFirehoseStream,
  getTweetsLabelStream,
  getTweetsSample10Stream,
  getUserListMemberships,
  getUsersComplianceStream,
  getUsersIdBookmarks,
  hideReplyById,
  listAddMember,
  listBatchComplianceJobs,
  listGetFollowers,
  listGetMembers,
  listIdCreate,
  listIdDelete,
  listIdGet,
  listIdUpdate,
  listRemoveMember,
  listUserFollow,
  listUserOwnedLists,
  listUserPin,
  listUserPinnedLists,
  listUserUnfollow,
  listUserUnpin,
  listsIdTweets,
  postUsersIdBookmarks,
  sampleStream,
  searchSpaces,
  searchStream,
  spaceBuyers,
  spaceTweets,
  tweetCountsFullArchiveSearch,
  tweetCountsRecentSearch,
  tweetsFullarchiveSearch,
  tweetsIdLikingUsers,
  tweetsIdRetweetingUsers,
  tweetsRecentSearch,
  userFollowedLists,
  usersIdBlock,
  usersIdBlocking,
  usersIdBookmarksDelete,
  usersIdFollow,
  usersIdFollowers,
  usersIdFollowing,
  usersIdLike,
  usersIdLikedTweets,
  usersIdMentions,
  usersIdMute,
  usersIdMuting,
  usersIdRetweets,
  usersIdTimeline,
  usersIdTweets,
  usersIdUnblock,
  usersIdUnfollow,
  usersIdUnlike,
  usersIdUnmute,
  usersIdUnretweets,
  type ApiError,
} from './client.js'

// ── Query key factories ──────────────────────────────────────

export const _2Keys = {
  all: () => ['2'] as const,
  listBatchComplianceJobs: (params: Parameters<typeof listBatchComplianceJobs>[0]) =>
    ['2', 'listBatchComplianceJobs', params] as const,
  getDmEvents: (params?: Parameters<typeof getDmEvents>[0]) =>
    ['2', 'getDmEvents', params] as const,
  getOpenApiSpec: () => ['2', 'getOpenApiSpec'] as const,
  findSpacesByIds: (params: Parameters<typeof findSpacesByIds>[0]) =>
    ['2', 'findSpacesByIds', params] as const,
  findSpacesByCreatorIds: (params: Parameters<typeof findSpacesByCreatorIds>[0]) =>
    ['2', 'findSpacesByCreatorIds', params] as const,
  searchSpaces: (params: Parameters<typeof searchSpaces>[0]) =>
    ['2', 'searchSpaces', params] as const,
  findTweetsById: (params: Parameters<typeof findTweetsById>[0]) =>
    ['2', 'findTweetsById', params] as const,
  getTweetsComplianceStream: (params: Parameters<typeof getTweetsComplianceStream>[0]) =>
    ['2', 'getTweetsComplianceStream', params] as const,
  tweetCountsFullArchiveSearch: (params: Parameters<typeof tweetCountsFullArchiveSearch>[0]) =>
    ['2', 'tweetCountsFullArchiveSearch', params] as const,
  tweetCountsRecentSearch: (params: Parameters<typeof tweetCountsRecentSearch>[0]) =>
    ['2', 'tweetCountsRecentSearch', params] as const,
  getTweetsFirehoseStream: (params: Parameters<typeof getTweetsFirehoseStream>[0]) =>
    ['2', 'getTweetsFirehoseStream', params] as const,
  getTweetsLabelStream: (params?: Parameters<typeof getTweetsLabelStream>[0]) =>
    ['2', 'getTweetsLabelStream', params] as const,
  sampleStream: (params?: Parameters<typeof sampleStream>[0]) =>
    ['2', 'sampleStream', params] as const,
  getTweetsSample10Stream: (params: Parameters<typeof getTweetsSample10Stream>[0]) =>
    ['2', 'getTweetsSample10Stream', params] as const,
  tweetsFullarchiveSearch: (params: Parameters<typeof tweetsFullarchiveSearch>[0]) =>
    ['2', 'tweetsFullarchiveSearch', params] as const,
  tweetsRecentSearch: (params: Parameters<typeof tweetsRecentSearch>[0]) =>
    ['2', 'tweetsRecentSearch', params] as const,
  searchStream: (params?: Parameters<typeof searchStream>[0]) =>
    ['2', 'searchStream', params] as const,
  getRules: (params?: Parameters<typeof getRules>[0]) => ['2', 'getRules', params] as const,
  findUsersById: (params: Parameters<typeof findUsersById>[0]) =>
    ['2', 'findUsersById', params] as const,
  findUsersByUsername: (params: Parameters<typeof findUsersByUsername>[0]) =>
    ['2', 'findUsersByUsername', params] as const,
  getUsersComplianceStream: (params: Parameters<typeof getUsersComplianceStream>[0]) =>
    ['2', 'getUsersComplianceStream', params] as const,
  findMyUser: (params?: Parameters<typeof findMyUser>[0]) => ['2', 'findMyUser', params] as const,
  getBatchComplianceJob: (
    id: Parameters<typeof getBatchComplianceJob>[0],
    params?: Parameters<typeof getBatchComplianceJob>[1]
  ) => ['2', 'getBatchComplianceJob', id, params] as const,
  getDmConversationsWithParticipantIdDmEvents: (
    participantId: Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[0],
    params?: Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[1]
  ) => ['2', 'getDmConversationsWithParticipantIdDmEvents', participantId, params] as const,
  getDmConversationsIdDmEvents: (
    id: Parameters<typeof getDmConversationsIdDmEvents>[0],
    params?: Parameters<typeof getDmConversationsIdDmEvents>[1]
  ) => ['2', 'getDmConversationsIdDmEvents', id, params] as const,
  listIdGet: (id: Parameters<typeof listIdGet>[0], params?: Parameters<typeof listIdGet>[1]) =>
    ['2', 'listIdGet', id, params] as const,
  listGetFollowers: (
    id: Parameters<typeof listGetFollowers>[0],
    params?: Parameters<typeof listGetFollowers>[1]
  ) => ['2', 'listGetFollowers', id, params] as const,
  listGetMembers: (
    id: Parameters<typeof listGetMembers>[0],
    params?: Parameters<typeof listGetMembers>[1]
  ) => ['2', 'listGetMembers', id, params] as const,
  listsIdTweets: (
    id: Parameters<typeof listsIdTweets>[0],
    params?: Parameters<typeof listsIdTweets>[1]
  ) => ['2', 'listsIdTweets', id, params] as const,
  findSpaceById: (
    id: Parameters<typeof findSpaceById>[0],
    params?: Parameters<typeof findSpaceById>[1]
  ) => ['2', 'findSpaceById', id, params] as const,
  spaceBuyers: (
    id: Parameters<typeof spaceBuyers>[0],
    params?: Parameters<typeof spaceBuyers>[1]
  ) => ['2', 'spaceBuyers', id, params] as const,
  spaceTweets: (
    id: Parameters<typeof spaceTweets>[0],
    params?: Parameters<typeof spaceTweets>[1]
  ) => ['2', 'spaceTweets', id, params] as const,
  findTweetById: (
    id: Parameters<typeof findTweetById>[0],
    params?: Parameters<typeof findTweetById>[1]
  ) => ['2', 'findTweetById', id, params] as const,
  tweetsIdLikingUsers: (
    id: Parameters<typeof tweetsIdLikingUsers>[0],
    params?: Parameters<typeof tweetsIdLikingUsers>[1]
  ) => ['2', 'tweetsIdLikingUsers', id, params] as const,
  findTweetsThatQuoteATweet: (
    id: Parameters<typeof findTweetsThatQuoteATweet>[0],
    params?: Parameters<typeof findTweetsThatQuoteATweet>[1]
  ) => ['2', 'findTweetsThatQuoteATweet', id, params] as const,
  tweetsIdRetweetingUsers: (
    id: Parameters<typeof tweetsIdRetweetingUsers>[0],
    params?: Parameters<typeof tweetsIdRetweetingUsers>[1]
  ) => ['2', 'tweetsIdRetweetingUsers', id, params] as const,
  findUserByUsername: (
    username: Parameters<typeof findUserByUsername>[0],
    params?: Parameters<typeof findUserByUsername>[1]
  ) => ['2', 'findUserByUsername', username, params] as const,
  findUserById: (
    id: Parameters<typeof findUserById>[0],
    params?: Parameters<typeof findUserById>[1]
  ) => ['2', 'findUserById', id, params] as const,
  usersIdBlocking: (
    id: Parameters<typeof usersIdBlocking>[0],
    params?: Parameters<typeof usersIdBlocking>[1]
  ) => ['2', 'usersIdBlocking', id, params] as const,
  getUsersIdBookmarks: (
    id: Parameters<typeof getUsersIdBookmarks>[0],
    params?: Parameters<typeof getUsersIdBookmarks>[1]
  ) => ['2', 'getUsersIdBookmarks', id, params] as const,
  userFollowedLists: (
    id: Parameters<typeof userFollowedLists>[0],
    params?: Parameters<typeof userFollowedLists>[1]
  ) => ['2', 'userFollowedLists', id, params] as const,
  usersIdFollowers: (
    id: Parameters<typeof usersIdFollowers>[0],
    params?: Parameters<typeof usersIdFollowers>[1]
  ) => ['2', 'usersIdFollowers', id, params] as const,
  usersIdFollowing: (
    id: Parameters<typeof usersIdFollowing>[0],
    params?: Parameters<typeof usersIdFollowing>[1]
  ) => ['2', 'usersIdFollowing', id, params] as const,
  usersIdLikedTweets: (
    id: Parameters<typeof usersIdLikedTweets>[0],
    params?: Parameters<typeof usersIdLikedTweets>[1]
  ) => ['2', 'usersIdLikedTweets', id, params] as const,
  getUserListMemberships: (
    id: Parameters<typeof getUserListMemberships>[0],
    params?: Parameters<typeof getUserListMemberships>[1]
  ) => ['2', 'getUserListMemberships', id, params] as const,
  usersIdMentions: (
    id: Parameters<typeof usersIdMentions>[0],
    params?: Parameters<typeof usersIdMentions>[1]
  ) => ['2', 'usersIdMentions', id, params] as const,
  usersIdMuting: (
    id: Parameters<typeof usersIdMuting>[0],
    params?: Parameters<typeof usersIdMuting>[1]
  ) => ['2', 'usersIdMuting', id, params] as const,
  listUserOwnedLists: (
    id: Parameters<typeof listUserOwnedLists>[0],
    params?: Parameters<typeof listUserOwnedLists>[1]
  ) => ['2', 'listUserOwnedLists', id, params] as const,
  listUserPinnedLists: (
    id: Parameters<typeof listUserPinnedLists>[0],
    params?: Parameters<typeof listUserPinnedLists>[1]
  ) => ['2', 'listUserPinnedLists', id, params] as const,
  usersIdTimeline: (
    id: Parameters<typeof usersIdTimeline>[0],
    params?: Parameters<typeof usersIdTimeline>[1]
  ) => ['2', 'usersIdTimeline', id, params] as const,
  usersIdTweets: (
    id: Parameters<typeof usersIdTweets>[0],
    params?: Parameters<typeof usersIdTweets>[1]
  ) => ['2', 'usersIdTweets', id, params] as const,
}

// ── Query options factories ──────────────────────────────────

export function listBatchComplianceJobsQueryOptions(
  params: Parameters<typeof listBatchComplianceJobs>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listBatchComplianceJobs>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listBatchComplianceJobs>>, ApiError>({
    queryKey: _2Keys.listBatchComplianceJobs(params),
    queryFn: () => listBatchComplianceJobs(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getBatchComplianceJobQueryOptions(
  id: Parameters<typeof getBatchComplianceJob>[0],
  params?: Parameters<typeof getBatchComplianceJob>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBatchComplianceJob>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getBatchComplianceJob>>, ApiError>({
    queryKey: _2Keys.getBatchComplianceJob(id, params),
    queryFn: () => getBatchComplianceJob(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDmConversationsWithParticipantIdDmEventsQueryOptions(
  participantId: Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[0],
  params?: Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[1],
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDmConversationsWithParticipantIdDmEvents>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<
    Awaited<ReturnType<typeof getDmConversationsWithParticipantIdDmEvents>>,
    ApiError
  >({
    queryKey: _2Keys.getDmConversationsWithParticipantIdDmEvents(participantId, params),
    queryFn: () => getDmConversationsWithParticipantIdDmEvents(participantId, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDmConversationsIdDmEventsQueryOptions(
  id: Parameters<typeof getDmConversationsIdDmEvents>[0],
  params?: Parameters<typeof getDmConversationsIdDmEvents>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDmConversationsIdDmEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDmConversationsIdDmEvents>>, ApiError>({
    queryKey: _2Keys.getDmConversationsIdDmEvents(id, params),
    queryFn: () => getDmConversationsIdDmEvents(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getDmEventsQueryOptions(
  params?: Parameters<typeof getDmEvents>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDmEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getDmEvents>>, ApiError>({
    queryKey: _2Keys.getDmEvents(params),
    queryFn: () => getDmEvents(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listIdGetQueryOptions(
  id: Parameters<typeof listIdGet>[0],
  params?: Parameters<typeof listIdGet>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listIdGet>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listIdGet>>, ApiError>({
    queryKey: _2Keys.listIdGet(id, params),
    queryFn: () => listIdGet(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listGetFollowersQueryOptions(
  id: Parameters<typeof listGetFollowers>[0],
  params?: Parameters<typeof listGetFollowers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listGetFollowers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listGetFollowers>>, ApiError>({
    queryKey: _2Keys.listGetFollowers(id, params),
    queryFn: () => listGetFollowers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listGetMembersQueryOptions(
  id: Parameters<typeof listGetMembers>[0],
  params?: Parameters<typeof listGetMembers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listGetMembers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listGetMembers>>, ApiError>({
    queryKey: _2Keys.listGetMembers(id, params),
    queryFn: () => listGetMembers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listsIdTweetsQueryOptions(
  id: Parameters<typeof listsIdTweets>[0],
  params?: Parameters<typeof listsIdTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listsIdTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listsIdTweets>>, ApiError>({
    queryKey: _2Keys.listsIdTweets(id, params),
    queryFn: () => listsIdTweets(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getOpenApiSpecQueryOptions(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getOpenApiSpec>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getOpenApiSpec>>, ApiError>({
    queryKey: _2Keys.getOpenApiSpec(),
    queryFn: () => getOpenApiSpec(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findSpacesByIdsQueryOptions(
  params: Parameters<typeof findSpacesByIds>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpacesByIds>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findSpacesByIds>>, ApiError>({
    queryKey: _2Keys.findSpacesByIds(params),
    queryFn: () => findSpacesByIds(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findSpacesByCreatorIdsQueryOptions(
  params: Parameters<typeof findSpacesByCreatorIds>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpacesByCreatorIds>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findSpacesByCreatorIds>>, ApiError>({
    queryKey: _2Keys.findSpacesByCreatorIds(params),
    queryFn: () => findSpacesByCreatorIds(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function searchSpacesQueryOptions(
  params: Parameters<typeof searchSpaces>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof searchSpaces>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof searchSpaces>>, ApiError>({
    queryKey: _2Keys.searchSpaces(params),
    queryFn: () => searchSpaces(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findSpaceByIdQueryOptions(
  id: Parameters<typeof findSpaceById>[0],
  params?: Parameters<typeof findSpaceById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpaceById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findSpaceById>>, ApiError>({
    queryKey: _2Keys.findSpaceById(id, params),
    queryFn: () => findSpaceById(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function spaceBuyersQueryOptions(
  id: Parameters<typeof spaceBuyers>[0],
  params?: Parameters<typeof spaceBuyers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof spaceBuyers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof spaceBuyers>>, ApiError>({
    queryKey: _2Keys.spaceBuyers(id, params),
    queryFn: () => spaceBuyers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function spaceTweetsQueryOptions(
  id: Parameters<typeof spaceTweets>[0],
  params?: Parameters<typeof spaceTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof spaceTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof spaceTweets>>, ApiError>({
    queryKey: _2Keys.spaceTweets(id, params),
    queryFn: () => spaceTweets(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findTweetsByIdQueryOptions(
  params: Parameters<typeof findTweetsById>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findTweetsById>>, ApiError>({
    queryKey: _2Keys.findTweetsById(params),
    queryFn: () => findTweetsById(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTweetsComplianceStreamQueryOptions(
  params: Parameters<typeof getTweetsComplianceStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsComplianceStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTweetsComplianceStream>>, ApiError>({
    queryKey: _2Keys.getTweetsComplianceStream(params),
    queryFn: () => getTweetsComplianceStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetCountsFullArchiveSearchQueryOptions(
  params: Parameters<typeof tweetCountsFullArchiveSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetCountsFullArchiveSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetCountsFullArchiveSearch>>, ApiError>({
    queryKey: _2Keys.tweetCountsFullArchiveSearch(params),
    queryFn: () => tweetCountsFullArchiveSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetCountsRecentSearchQueryOptions(
  params: Parameters<typeof tweetCountsRecentSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetCountsRecentSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetCountsRecentSearch>>, ApiError>({
    queryKey: _2Keys.tweetCountsRecentSearch(params),
    queryFn: () => tweetCountsRecentSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTweetsFirehoseStreamQueryOptions(
  params: Parameters<typeof getTweetsFirehoseStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsFirehoseStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTweetsFirehoseStream>>, ApiError>({
    queryKey: _2Keys.getTweetsFirehoseStream(params),
    queryFn: () => getTweetsFirehoseStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTweetsLabelStreamQueryOptions(
  params?: Parameters<typeof getTweetsLabelStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsLabelStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTweetsLabelStream>>, ApiError>({
    queryKey: _2Keys.getTweetsLabelStream(params),
    queryFn: () => getTweetsLabelStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function sampleStreamQueryOptions(
  params?: Parameters<typeof sampleStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof sampleStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof sampleStream>>, ApiError>({
    queryKey: _2Keys.sampleStream(params),
    queryFn: () => sampleStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getTweetsSample10StreamQueryOptions(
  params: Parameters<typeof getTweetsSample10Stream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsSample10Stream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getTweetsSample10Stream>>, ApiError>({
    queryKey: _2Keys.getTweetsSample10Stream(params),
    queryFn: () => getTweetsSample10Stream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetsFullarchiveSearchQueryOptions(
  params: Parameters<typeof tweetsFullarchiveSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsFullarchiveSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetsFullarchiveSearch>>, ApiError>({
    queryKey: _2Keys.tweetsFullarchiveSearch(params),
    queryFn: () => tweetsFullarchiveSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetsRecentSearchQueryOptions(
  params: Parameters<typeof tweetsRecentSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsRecentSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetsRecentSearch>>, ApiError>({
    queryKey: _2Keys.tweetsRecentSearch(params),
    queryFn: () => tweetsRecentSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function searchStreamQueryOptions(
  params?: Parameters<typeof searchStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof searchStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof searchStream>>, ApiError>({
    queryKey: _2Keys.searchStream(params),
    queryFn: () => searchStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getRulesQueryOptions(
  params?: Parameters<typeof getRules>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getRules>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getRules>>, ApiError>({
    queryKey: _2Keys.getRules(params),
    queryFn: () => getRules(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findTweetByIdQueryOptions(
  id: Parameters<typeof findTweetById>[0],
  params?: Parameters<typeof findTweetById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findTweetById>>, ApiError>({
    queryKey: _2Keys.findTweetById(id, params),
    queryFn: () => findTweetById(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetsIdLikingUsersQueryOptions(
  id: Parameters<typeof tweetsIdLikingUsers>[0],
  params?: Parameters<typeof tweetsIdLikingUsers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsIdLikingUsers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetsIdLikingUsers>>, ApiError>({
    queryKey: _2Keys.tweetsIdLikingUsers(id, params),
    queryFn: () => tweetsIdLikingUsers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findTweetsThatQuoteATweetQueryOptions(
  id: Parameters<typeof findTweetsThatQuoteATweet>[0],
  params?: Parameters<typeof findTweetsThatQuoteATweet>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetsThatQuoteATweet>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findTweetsThatQuoteATweet>>, ApiError>({
    queryKey: _2Keys.findTweetsThatQuoteATweet(id, params),
    queryFn: () => findTweetsThatQuoteATweet(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function tweetsIdRetweetingUsersQueryOptions(
  id: Parameters<typeof tweetsIdRetweetingUsers>[0],
  params?: Parameters<typeof tweetsIdRetweetingUsers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsIdRetweetingUsers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof tweetsIdRetweetingUsers>>, ApiError>({
    queryKey: _2Keys.tweetsIdRetweetingUsers(id, params),
    queryFn: () => tweetsIdRetweetingUsers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findUsersByIdQueryOptions(
  params: Parameters<typeof findUsersById>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUsersById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findUsersById>>, ApiError>({
    queryKey: _2Keys.findUsersById(params),
    queryFn: () => findUsersById(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findUsersByUsernameQueryOptions(
  params: Parameters<typeof findUsersByUsername>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUsersByUsername>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findUsersByUsername>>, ApiError>({
    queryKey: _2Keys.findUsersByUsername(params),
    queryFn: () => findUsersByUsername(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findUserByUsernameQueryOptions(
  username: Parameters<typeof findUserByUsername>[0],
  params?: Parameters<typeof findUserByUsername>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUserByUsername>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findUserByUsername>>, ApiError>({
    queryKey: _2Keys.findUserByUsername(username, params),
    queryFn: () => findUserByUsername(username, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getUsersComplianceStreamQueryOptions(
  params: Parameters<typeof getUsersComplianceStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersComplianceStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getUsersComplianceStream>>, ApiError>({
    queryKey: _2Keys.getUsersComplianceStream(params),
    queryFn: () => getUsersComplianceStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findMyUserQueryOptions(
  params?: Parameters<typeof findMyUser>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findMyUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findMyUser>>, ApiError>({
    queryKey: _2Keys.findMyUser(params),
    queryFn: () => findMyUser(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function findUserByIdQueryOptions(
  id: Parameters<typeof findUserById>[0],
  params?: Parameters<typeof findUserById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUserById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof findUserById>>, ApiError>({
    queryKey: _2Keys.findUserById(id, params),
    queryFn: () => findUserById(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdBlockingQueryOptions(
  id: Parameters<typeof usersIdBlocking>[0],
  params?: Parameters<typeof usersIdBlocking>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdBlocking>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdBlocking>>, ApiError>({
    queryKey: _2Keys.usersIdBlocking(id, params),
    queryFn: () => usersIdBlocking(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getUsersIdBookmarksQueryOptions(
  id: Parameters<typeof getUsersIdBookmarks>[0],
  params?: Parameters<typeof getUsersIdBookmarks>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersIdBookmarks>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getUsersIdBookmarks>>, ApiError>({
    queryKey: _2Keys.getUsersIdBookmarks(id, params),
    queryFn: () => getUsersIdBookmarks(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function userFollowedListsQueryOptions(
  id: Parameters<typeof userFollowedLists>[0],
  params?: Parameters<typeof userFollowedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof userFollowedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof userFollowedLists>>, ApiError>({
    queryKey: _2Keys.userFollowedLists(id, params),
    queryFn: () => userFollowedLists(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdFollowersQueryOptions(
  id: Parameters<typeof usersIdFollowers>[0],
  params?: Parameters<typeof usersIdFollowers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdFollowers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdFollowers>>, ApiError>({
    queryKey: _2Keys.usersIdFollowers(id, params),
    queryFn: () => usersIdFollowers(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdFollowingQueryOptions(
  id: Parameters<typeof usersIdFollowing>[0],
  params?: Parameters<typeof usersIdFollowing>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdFollowing>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdFollowing>>, ApiError>({
    queryKey: _2Keys.usersIdFollowing(id, params),
    queryFn: () => usersIdFollowing(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdLikedTweetsQueryOptions(
  id: Parameters<typeof usersIdLikedTweets>[0],
  params?: Parameters<typeof usersIdLikedTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdLikedTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdLikedTweets>>, ApiError>({
    queryKey: _2Keys.usersIdLikedTweets(id, params),
    queryFn: () => usersIdLikedTweets(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function getUserListMembershipsQueryOptions(
  id: Parameters<typeof getUserListMemberships>[0],
  params?: Parameters<typeof getUserListMemberships>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUserListMemberships>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof getUserListMemberships>>, ApiError>({
    queryKey: _2Keys.getUserListMemberships(id, params),
    queryFn: () => getUserListMemberships(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdMentionsQueryOptions(
  id: Parameters<typeof usersIdMentions>[0],
  params?: Parameters<typeof usersIdMentions>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdMentions>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdMentions>>, ApiError>({
    queryKey: _2Keys.usersIdMentions(id, params),
    queryFn: () => usersIdMentions(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdMutingQueryOptions(
  id: Parameters<typeof usersIdMuting>[0],
  params?: Parameters<typeof usersIdMuting>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdMuting>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdMuting>>, ApiError>({
    queryKey: _2Keys.usersIdMuting(id, params),
    queryFn: () => usersIdMuting(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listUserOwnedListsQueryOptions(
  id: Parameters<typeof listUserOwnedLists>[0],
  params?: Parameters<typeof listUserOwnedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listUserOwnedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listUserOwnedLists>>, ApiError>({
    queryKey: _2Keys.listUserOwnedLists(id, params),
    queryFn: () => listUserOwnedLists(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function listUserPinnedListsQueryOptions(
  id: Parameters<typeof listUserPinnedLists>[0],
  params?: Parameters<typeof listUserPinnedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listUserPinnedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof listUserPinnedLists>>, ApiError>({
    queryKey: _2Keys.listUserPinnedLists(id, params),
    queryFn: () => listUserPinnedLists(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdTimelineQueryOptions(
  id: Parameters<typeof usersIdTimeline>[0],
  params?: Parameters<typeof usersIdTimeline>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdTimeline>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdTimeline>>, ApiError>({
    queryKey: _2Keys.usersIdTimeline(id, params),
    queryFn: () => usersIdTimeline(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function usersIdTweetsQueryOptions(
  id: Parameters<typeof usersIdTweets>[0],
  params?: Parameters<typeof usersIdTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions<Awaited<ReturnType<typeof usersIdTweets>>, ApiError>({
    queryKey: _2Keys.usersIdTweets(id, params),
    queryFn: () => usersIdTweets(id, params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

// ── Queries ──────────────────────────────────────────────────

export function useListBatchComplianceJobs(
  params: Parameters<typeof listBatchComplianceJobs>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listBatchComplianceJobs>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listBatchComplianceJobs>>, ApiError>({
    queryKey: _2Keys.listBatchComplianceJobs(params),
    queryFn: () => listBatchComplianceJobs(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetBatchComplianceJob(
  id: Parameters<typeof getBatchComplianceJob>[0] | undefined | null,
  params?: Parameters<typeof getBatchComplianceJob>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getBatchComplianceJob>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getBatchComplianceJob>>, ApiError>({
    queryKey: _2Keys.getBatchComplianceJob(id!, params),
    queryFn: () => getBatchComplianceJob(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDmConversationsWithParticipantIdDmEvents(
  participantId:
    Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[0] | undefined | null,
  params?: Parameters<typeof getDmConversationsWithParticipantIdDmEvents>[1],
  options?: Omit<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDmConversationsWithParticipantIdDmEvents>>,
      ApiError
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<
    Awaited<ReturnType<typeof getDmConversationsWithParticipantIdDmEvents>>,
    ApiError
  >({
    queryKey: _2Keys.getDmConversationsWithParticipantIdDmEvents(participantId!, params),
    queryFn: () => getDmConversationsWithParticipantIdDmEvents(participantId!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: participantId != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDmConversationsIdDmEvents(
  id: Parameters<typeof getDmConversationsIdDmEvents>[0] | undefined | null,
  params?: Parameters<typeof getDmConversationsIdDmEvents>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDmConversationsIdDmEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDmConversationsIdDmEvents>>, ApiError>({
    queryKey: _2Keys.getDmConversationsIdDmEvents(id!, params),
    queryFn: () => getDmConversationsIdDmEvents(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetDmEvents(
  params?: Parameters<typeof getDmEvents>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getDmEvents>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getDmEvents>>, ApiError>({
    queryKey: _2Keys.getDmEvents(params),
    queryFn: () => getDmEvents(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useListIdGet(
  id: Parameters<typeof listIdGet>[0] | undefined | null,
  params?: Parameters<typeof listIdGet>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listIdGet>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listIdGet>>, ApiError>({
    queryKey: _2Keys.listIdGet(id!, params),
    queryFn: () => listIdGet(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useListGetFollowers(
  id: Parameters<typeof listGetFollowers>[0] | undefined | null,
  params?: Parameters<typeof listGetFollowers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listGetFollowers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listGetFollowers>>, ApiError>({
    queryKey: _2Keys.listGetFollowers(id!, params),
    queryFn: () => listGetFollowers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useListGetMembers(
  id: Parameters<typeof listGetMembers>[0] | undefined | null,
  params?: Parameters<typeof listGetMembers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listGetMembers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listGetMembers>>, ApiError>({
    queryKey: _2Keys.listGetMembers(id!, params),
    queryFn: () => listGetMembers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useListsIdTweets(
  id: Parameters<typeof listsIdTweets>[0] | undefined | null,
  params?: Parameters<typeof listsIdTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listsIdTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listsIdTweets>>, ApiError>({
    queryKey: _2Keys.listsIdTweets(id!, params),
    queryFn: () => listsIdTweets(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetOpenApiSpec(
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getOpenApiSpec>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getOpenApiSpec>>, ApiError>({
    queryKey: _2Keys.getOpenApiSpec(),
    queryFn: () => getOpenApiSpec(),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindSpacesByIds(
  params: Parameters<typeof findSpacesByIds>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpacesByIds>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findSpacesByIds>>, ApiError>({
    queryKey: _2Keys.findSpacesByIds(params),
    queryFn: () => findSpacesByIds(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindSpacesByCreatorIds(
  params: Parameters<typeof findSpacesByCreatorIds>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpacesByCreatorIds>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findSpacesByCreatorIds>>, ApiError>({
    queryKey: _2Keys.findSpacesByCreatorIds(params),
    queryFn: () => findSpacesByCreatorIds(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useSearchSpaces(
  params: Parameters<typeof searchSpaces>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof searchSpaces>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof searchSpaces>>, ApiError>({
    queryKey: _2Keys.searchSpaces(params),
    queryFn: () => searchSpaces(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindSpaceById(
  id: Parameters<typeof findSpaceById>[0] | undefined | null,
  params?: Parameters<typeof findSpaceById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findSpaceById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findSpaceById>>, ApiError>({
    queryKey: _2Keys.findSpaceById(id!, params),
    queryFn: () => findSpaceById(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useSpaceBuyers(
  id: Parameters<typeof spaceBuyers>[0] | undefined | null,
  params?: Parameters<typeof spaceBuyers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof spaceBuyers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof spaceBuyers>>, ApiError>({
    queryKey: _2Keys.spaceBuyers(id!, params),
    queryFn: () => spaceBuyers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useSpaceTweets(
  id: Parameters<typeof spaceTweets>[0] | undefined | null,
  params?: Parameters<typeof spaceTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof spaceTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof spaceTweets>>, ApiError>({
    queryKey: _2Keys.spaceTweets(id!, params),
    queryFn: () => spaceTweets(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useFindTweetsById(
  params: Parameters<typeof findTweetsById>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetsById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findTweetsById>>, ApiError>({
    queryKey: _2Keys.findTweetsById(params),
    queryFn: () => findTweetsById(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTweetsComplianceStream(
  params: Parameters<typeof getTweetsComplianceStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsComplianceStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTweetsComplianceStream>>, ApiError>({
    queryKey: _2Keys.getTweetsComplianceStream(params),
    queryFn: () => getTweetsComplianceStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useTweetCountsFullArchiveSearch(
  params: Parameters<typeof tweetCountsFullArchiveSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetCountsFullArchiveSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetCountsFullArchiveSearch>>, ApiError>({
    queryKey: _2Keys.tweetCountsFullArchiveSearch(params),
    queryFn: () => tweetCountsFullArchiveSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useTweetCountsRecentSearch(
  params: Parameters<typeof tweetCountsRecentSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetCountsRecentSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetCountsRecentSearch>>, ApiError>({
    queryKey: _2Keys.tweetCountsRecentSearch(params),
    queryFn: () => tweetCountsRecentSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTweetsFirehoseStream(
  params: Parameters<typeof getTweetsFirehoseStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsFirehoseStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTweetsFirehoseStream>>, ApiError>({
    queryKey: _2Keys.getTweetsFirehoseStream(params),
    queryFn: () => getTweetsFirehoseStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTweetsLabelStream(
  params?: Parameters<typeof getTweetsLabelStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsLabelStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTweetsLabelStream>>, ApiError>({
    queryKey: _2Keys.getTweetsLabelStream(params),
    queryFn: () => getTweetsLabelStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useSampleStream(
  params?: Parameters<typeof sampleStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof sampleStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof sampleStream>>, ApiError>({
    queryKey: _2Keys.sampleStream(params),
    queryFn: () => sampleStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetTweetsSample10Stream(
  params: Parameters<typeof getTweetsSample10Stream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getTweetsSample10Stream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getTweetsSample10Stream>>, ApiError>({
    queryKey: _2Keys.getTweetsSample10Stream(params),
    queryFn: () => getTweetsSample10Stream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useTweetsFullarchiveSearch(
  params: Parameters<typeof tweetsFullarchiveSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsFullarchiveSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetsFullarchiveSearch>>, ApiError>({
    queryKey: _2Keys.tweetsFullarchiveSearch(params),
    queryFn: () => tweetsFullarchiveSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useTweetsRecentSearch(
  params: Parameters<typeof tweetsRecentSearch>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsRecentSearch>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetsRecentSearch>>, ApiError>({
    queryKey: _2Keys.tweetsRecentSearch(params),
    queryFn: () => tweetsRecentSearch(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useSearchStream(
  params?: Parameters<typeof searchStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof searchStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof searchStream>>, ApiError>({
    queryKey: _2Keys.searchStream(params),
    queryFn: () => searchStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useGetRules(
  params?: Parameters<typeof getRules>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getRules>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getRules>>, ApiError>({
    queryKey: _2Keys.getRules(params),
    queryFn: () => getRules(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindTweetById(
  id: Parameters<typeof findTweetById>[0] | undefined | null,
  params?: Parameters<typeof findTweetById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findTweetById>>, ApiError>({
    queryKey: _2Keys.findTweetById(id!, params),
    queryFn: () => findTweetById(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useTweetsIdLikingUsers(
  id: Parameters<typeof tweetsIdLikingUsers>[0] | undefined | null,
  params?: Parameters<typeof tweetsIdLikingUsers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsIdLikingUsers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetsIdLikingUsers>>, ApiError>({
    queryKey: _2Keys.tweetsIdLikingUsers(id!, params),
    queryFn: () => tweetsIdLikingUsers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useFindTweetsThatQuoteATweet(
  id: Parameters<typeof findTweetsThatQuoteATweet>[0] | undefined | null,
  params?: Parameters<typeof findTweetsThatQuoteATweet>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findTweetsThatQuoteATweet>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findTweetsThatQuoteATweet>>, ApiError>({
    queryKey: _2Keys.findTweetsThatQuoteATweet(id!, params),
    queryFn: () => findTweetsThatQuoteATweet(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useTweetsIdRetweetingUsers(
  id: Parameters<typeof tweetsIdRetweetingUsers>[0] | undefined | null,
  params?: Parameters<typeof tweetsIdRetweetingUsers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof tweetsIdRetweetingUsers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof tweetsIdRetweetingUsers>>, ApiError>({
    queryKey: _2Keys.tweetsIdRetweetingUsers(id!, params),
    queryFn: () => tweetsIdRetweetingUsers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useFindUsersById(
  params: Parameters<typeof findUsersById>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUsersById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findUsersById>>, ApiError>({
    queryKey: _2Keys.findUsersById(params),
    queryFn: () => findUsersById(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindUsersByUsername(
  params: Parameters<typeof findUsersByUsername>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUsersByUsername>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findUsersByUsername>>, ApiError>({
    queryKey: _2Keys.findUsersByUsername(params),
    queryFn: () => findUsersByUsername(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindUserByUsername(
  username: Parameters<typeof findUserByUsername>[0] | undefined | null,
  params?: Parameters<typeof findUserByUsername>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUserByUsername>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findUserByUsername>>, ApiError>({
    queryKey: _2Keys.findUserByUsername(username!, params),
    queryFn: () => findUserByUsername(username!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: username != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetUsersComplianceStream(
  params: Parameters<typeof getUsersComplianceStream>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersComplianceStream>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getUsersComplianceStream>>, ApiError>({
    queryKey: _2Keys.getUsersComplianceStream(params),
    queryFn: () => getUsersComplianceStream(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindMyUser(
  params?: Parameters<typeof findMyUser>[0],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findMyUser>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findMyUser>>, ApiError>({
    queryKey: _2Keys.findMyUser(params),
    queryFn: () => findMyUser(params),
    staleTime: 0,
    gcTime: 300000,
    ...options,
  })
}

export function useFindUserById(
  id: Parameters<typeof findUserById>[0] | undefined | null,
  params?: Parameters<typeof findUserById>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof findUserById>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof findUserById>>, ApiError>({
    queryKey: _2Keys.findUserById(id!, params),
    queryFn: () => findUserById(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdBlocking(
  id: Parameters<typeof usersIdBlocking>[0] | undefined | null,
  params?: Parameters<typeof usersIdBlocking>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdBlocking>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdBlocking>>, ApiError>({
    queryKey: _2Keys.usersIdBlocking(id!, params),
    queryFn: () => usersIdBlocking(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetUsersIdBookmarks(
  id: Parameters<typeof getUsersIdBookmarks>[0] | undefined | null,
  params?: Parameters<typeof getUsersIdBookmarks>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersIdBookmarks>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getUsersIdBookmarks>>, ApiError>({
    queryKey: _2Keys.getUsersIdBookmarks(id!, params),
    queryFn: () => getUsersIdBookmarks(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUserFollowedLists(
  id: Parameters<typeof userFollowedLists>[0] | undefined | null,
  params?: Parameters<typeof userFollowedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof userFollowedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof userFollowedLists>>, ApiError>({
    queryKey: _2Keys.userFollowedLists(id!, params),
    queryFn: () => userFollowedLists(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdFollowers(
  id: Parameters<typeof usersIdFollowers>[0] | undefined | null,
  params?: Parameters<typeof usersIdFollowers>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdFollowers>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdFollowers>>, ApiError>({
    queryKey: _2Keys.usersIdFollowers(id!, params),
    queryFn: () => usersIdFollowers(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdFollowing(
  id: Parameters<typeof usersIdFollowing>[0] | undefined | null,
  params?: Parameters<typeof usersIdFollowing>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdFollowing>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdFollowing>>, ApiError>({
    queryKey: _2Keys.usersIdFollowing(id!, params),
    queryFn: () => usersIdFollowing(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdLikedTweets(
  id: Parameters<typeof usersIdLikedTweets>[0] | undefined | null,
  params?: Parameters<typeof usersIdLikedTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdLikedTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdLikedTweets>>, ApiError>({
    queryKey: _2Keys.usersIdLikedTweets(id!, params),
    queryFn: () => usersIdLikedTweets(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useGetUserListMemberships(
  id: Parameters<typeof getUserListMemberships>[0] | undefined | null,
  params?: Parameters<typeof getUserListMemberships>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof getUserListMemberships>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof getUserListMemberships>>, ApiError>({
    queryKey: _2Keys.getUserListMemberships(id!, params),
    queryFn: () => getUserListMemberships(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdMentions(
  id: Parameters<typeof usersIdMentions>[0] | undefined | null,
  params?: Parameters<typeof usersIdMentions>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdMentions>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdMentions>>, ApiError>({
    queryKey: _2Keys.usersIdMentions(id!, params),
    queryFn: () => usersIdMentions(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdMuting(
  id: Parameters<typeof usersIdMuting>[0] | undefined | null,
  params?: Parameters<typeof usersIdMuting>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdMuting>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdMuting>>, ApiError>({
    queryKey: _2Keys.usersIdMuting(id!, params),
    queryFn: () => usersIdMuting(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useListUserOwnedLists(
  id: Parameters<typeof listUserOwnedLists>[0] | undefined | null,
  params?: Parameters<typeof listUserOwnedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listUserOwnedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listUserOwnedLists>>, ApiError>({
    queryKey: _2Keys.listUserOwnedLists(id!, params),
    queryFn: () => listUserOwnedLists(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useListUserPinnedLists(
  id: Parameters<typeof listUserPinnedLists>[0] | undefined | null,
  params?: Parameters<typeof listUserPinnedLists>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof listUserPinnedLists>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof listUserPinnedLists>>, ApiError>({
    queryKey: _2Keys.listUserPinnedLists(id!, params),
    queryFn: () => listUserPinnedLists(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdTimeline(
  id: Parameters<typeof usersIdTimeline>[0] | undefined | null,
  params?: Parameters<typeof usersIdTimeline>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdTimeline>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdTimeline>>, ApiError>({
    queryKey: _2Keys.usersIdTimeline(id!, params),
    queryFn: () => usersIdTimeline(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

export function useUsersIdTweets(
  id: Parameters<typeof usersIdTweets>[0] | undefined | null,
  params?: Parameters<typeof usersIdTweets>[1],
  options?: Omit<
    UseQueryOptions<Awaited<ReturnType<typeof usersIdTweets>>, ApiError>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<Awaited<ReturnType<typeof usersIdTweets>>, ApiError>({
    queryKey: _2Keys.usersIdTweets(id!, params),
    queryFn: () => usersIdTweets(id!, params),
    staleTime: 0,
    gcTime: 300000,
    enabled: id != null && (options?.enabled ?? true),
    ...options,
  })
}

// ── Mutations ────────────────────────────────────────────────

export function useCreateBatchComplianceJob(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createBatchComplianceJob>>,
      ApiError,
      Parameters<typeof createBatchComplianceJob>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createBatchComplianceJob>>,
    ApiError,
    Parameters<typeof createBatchComplianceJob>[0]
  >({
    mutationFn: (vars) => createBatchComplianceJob(vars),
    ...options,
  })
}

export function useDmConversationIdCreate(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof dmConversationIdCreate>>,
      ApiError,
      Parameters<typeof dmConversationIdCreate>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof dmConversationIdCreate>>,
    ApiError,
    Parameters<typeof dmConversationIdCreate>[0]
  >({
    mutationFn: (vars) => dmConversationIdCreate(vars),
    ...options,
  })
}

export function useDmConversationWithUserEventIdCreate(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof dmConversationWithUserEventIdCreate>>,
      ApiError,
      {
        participantId: Parameters<typeof dmConversationWithUserEventIdCreate>[0]
        body: Parameters<typeof dmConversationWithUserEventIdCreate>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof dmConversationWithUserEventIdCreate>>,
    ApiError,
    {
      participantId: Parameters<typeof dmConversationWithUserEventIdCreate>[0]
      body: Parameters<typeof dmConversationWithUserEventIdCreate>[1]
    }
  >({
    mutationFn: ({ participantId, body }) =>
      dmConversationWithUserEventIdCreate(participantId, body),
    ...options,
  })
}

export function useDmConversationByIdEventIdCreate(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof dmConversationByIdEventIdCreate>>,
      ApiError,
      {
        dmConversationId: Parameters<typeof dmConversationByIdEventIdCreate>[0]
        body: Parameters<typeof dmConversationByIdEventIdCreate>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof dmConversationByIdEventIdCreate>>,
    ApiError,
    {
      dmConversationId: Parameters<typeof dmConversationByIdEventIdCreate>[0]
      body: Parameters<typeof dmConversationByIdEventIdCreate>[1]
    }
  >({
    mutationFn: ({ dmConversationId, body }) =>
      dmConversationByIdEventIdCreate(dmConversationId, body),
    ...options,
  })
}

export function useListIdCreate(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listIdCreate>>,
      ApiError,
      Parameters<typeof listIdCreate>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listIdCreate>>,
    ApiError,
    Parameters<typeof listIdCreate>[0]
  >({
    mutationFn: (vars) => listIdCreate(vars),
    ...options,
  })
}

export function useListIdUpdate(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listIdUpdate>>,
      ApiError,
      { id: Parameters<typeof listIdUpdate>[0]; body: Parameters<typeof listIdUpdate>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listIdUpdate>>,
    ApiError,
    { id: Parameters<typeof listIdUpdate>[0]; body: Parameters<typeof listIdUpdate>[1] }
  >({
    mutationFn: ({ id, body }) => listIdUpdate(id, body),
    ...options,
  })
}

export function useListIdDelete(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listIdDelete>>,
      ApiError,
      Parameters<typeof listIdDelete>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listIdDelete>>,
    ApiError,
    Parameters<typeof listIdDelete>[0]
  >({
    mutationFn: (id) => listIdDelete(id),
    ...options,
  })
}

export function useListAddMember(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listAddMember>>,
      ApiError,
      { id: Parameters<typeof listAddMember>[0]; body: Parameters<typeof listAddMember>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listAddMember>>,
    ApiError,
    { id: Parameters<typeof listAddMember>[0]; body: Parameters<typeof listAddMember>[1] }
  >({
    mutationFn: ({ id, body }) => listAddMember(id, body),
    ...options,
  })
}

export function useListRemoveMember(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listRemoveMember>>,
      ApiError,
      { id: Parameters<typeof listRemoveMember>[0]; userId: Parameters<typeof listRemoveMember>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listRemoveMember>>,
    ApiError,
    { id: Parameters<typeof listRemoveMember>[0]; userId: Parameters<typeof listRemoveMember>[1] }
  >({
    mutationFn: ({ id, userId }) => listRemoveMember(id, userId),
    ...options,
  })
}

export function useCreateTweet(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof createTweet>>,
      ApiError,
      Parameters<typeof createTweet>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof createTweet>>,
    ApiError,
    Parameters<typeof createTweet>[0]
  >({
    mutationFn: (vars) => createTweet(vars),
    ...options,
  })
}

export function useAddOrDeleteRules(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof addOrDeleteRules>>,
      ApiError,
      {
        body: Parameters<typeof addOrDeleteRules>[0]
        params: Parameters<typeof addOrDeleteRules>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof addOrDeleteRules>>,
    ApiError,
    { body: Parameters<typeof addOrDeleteRules>[0]; params: Parameters<typeof addOrDeleteRules>[1] }
  >({
    mutationFn: ({ body, params }) => addOrDeleteRules(body, params),
    ...options,
  })
}

export function useDeleteTweetById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof deleteTweetById>>,
      ApiError,
      Parameters<typeof deleteTweetById>[0]
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof deleteTweetById>>,
    ApiError,
    Parameters<typeof deleteTweetById>[0]
  >({
    mutationFn: (id) => deleteTweetById(id),
    ...options,
  })
}

export function useHideReplyById(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof hideReplyById>>,
      ApiError,
      { tweetId: Parameters<typeof hideReplyById>[0]; body: Parameters<typeof hideReplyById>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof hideReplyById>>,
    ApiError,
    { tweetId: Parameters<typeof hideReplyById>[0]; body: Parameters<typeof hideReplyById>[1] }
  >({
    mutationFn: ({ tweetId, body }) => hideReplyById(tweetId, body),
    ...options,
  })
}

export function useUsersIdBlock(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdBlock>>,
      ApiError,
      { id: Parameters<typeof usersIdBlock>[0]; body: Parameters<typeof usersIdBlock>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdBlock>>,
    ApiError,
    { id: Parameters<typeof usersIdBlock>[0]; body: Parameters<typeof usersIdBlock>[1] }
  >({
    mutationFn: ({ id, body }) => usersIdBlock(id, body),
    ...options,
  })
}

export function usePostUsersIdBookmarks(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof postUsersIdBookmarks>>,
      ApiError,
      {
        id: Parameters<typeof postUsersIdBookmarks>[0]
        body: Parameters<typeof postUsersIdBookmarks>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof postUsersIdBookmarks>>,
    ApiError,
    {
      id: Parameters<typeof postUsersIdBookmarks>[0]
      body: Parameters<typeof postUsersIdBookmarks>[1]
    }
  >({
    mutationFn: ({ id, body }) => postUsersIdBookmarks(id, body),
    ...options,
  })
}

export function useUsersIdBookmarksDelete(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdBookmarksDelete>>,
      ApiError,
      {
        id: Parameters<typeof usersIdBookmarksDelete>[0]
        tweetId: Parameters<typeof usersIdBookmarksDelete>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdBookmarksDelete>>,
    ApiError,
    {
      id: Parameters<typeof usersIdBookmarksDelete>[0]
      tweetId: Parameters<typeof usersIdBookmarksDelete>[1]
    }
  >({
    mutationFn: ({ id, tweetId }) => usersIdBookmarksDelete(id, tweetId),
    ...options,
  })
}

export function useListUserFollow(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listUserFollow>>,
      ApiError,
      { id: Parameters<typeof listUserFollow>[0]; body: Parameters<typeof listUserFollow>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listUserFollow>>,
    ApiError,
    { id: Parameters<typeof listUserFollow>[0]; body: Parameters<typeof listUserFollow>[1] }
  >({
    mutationFn: ({ id, body }) => listUserFollow(id, body),
    ...options,
  })
}

export function useListUserUnfollow(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listUserUnfollow>>,
      ApiError,
      { id: Parameters<typeof listUserUnfollow>[0]; listId: Parameters<typeof listUserUnfollow>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listUserUnfollow>>,
    ApiError,
    { id: Parameters<typeof listUserUnfollow>[0]; listId: Parameters<typeof listUserUnfollow>[1] }
  >({
    mutationFn: ({ id, listId }) => listUserUnfollow(id, listId),
    ...options,
  })
}

export function useUsersIdFollow(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdFollow>>,
      ApiError,
      { id: Parameters<typeof usersIdFollow>[0]; body: Parameters<typeof usersIdFollow>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdFollow>>,
    ApiError,
    { id: Parameters<typeof usersIdFollow>[0]; body: Parameters<typeof usersIdFollow>[1] }
  >({
    mutationFn: ({ id, body }) => usersIdFollow(id, body),
    ...options,
  })
}

export function useUsersIdLike(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdLike>>,
      ApiError,
      { id: Parameters<typeof usersIdLike>[0]; body: Parameters<typeof usersIdLike>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdLike>>,
    ApiError,
    { id: Parameters<typeof usersIdLike>[0]; body: Parameters<typeof usersIdLike>[1] }
  >({
    mutationFn: ({ id, body }) => usersIdLike(id, body),
    ...options,
  })
}

export function useUsersIdUnlike(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdUnlike>>,
      ApiError,
      { id: Parameters<typeof usersIdUnlike>[0]; tweetId: Parameters<typeof usersIdUnlike>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdUnlike>>,
    ApiError,
    { id: Parameters<typeof usersIdUnlike>[0]; tweetId: Parameters<typeof usersIdUnlike>[1] }
  >({
    mutationFn: ({ id, tweetId }) => usersIdUnlike(id, tweetId),
    ...options,
  })
}

export function useUsersIdMute(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdMute>>,
      ApiError,
      { id: Parameters<typeof usersIdMute>[0]; body: Parameters<typeof usersIdMute>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdMute>>,
    ApiError,
    { id: Parameters<typeof usersIdMute>[0]; body: Parameters<typeof usersIdMute>[1] }
  >({
    mutationFn: ({ id, body }) => usersIdMute(id, body),
    ...options,
  })
}

export function useListUserPin(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listUserPin>>,
      ApiError,
      { id: Parameters<typeof listUserPin>[0]; body: Parameters<typeof listUserPin>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listUserPin>>,
    ApiError,
    { id: Parameters<typeof listUserPin>[0]; body: Parameters<typeof listUserPin>[1] }
  >({
    mutationFn: ({ id, body }) => listUserPin(id, body),
    ...options,
  })
}

export function useListUserUnpin(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof listUserUnpin>>,
      ApiError,
      { id: Parameters<typeof listUserUnpin>[0]; listId: Parameters<typeof listUserUnpin>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof listUserUnpin>>,
    ApiError,
    { id: Parameters<typeof listUserUnpin>[0]; listId: Parameters<typeof listUserUnpin>[1] }
  >({
    mutationFn: ({ id, listId }) => listUserUnpin(id, listId),
    ...options,
  })
}

export function useUsersIdRetweets(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdRetweets>>,
      ApiError,
      { id: Parameters<typeof usersIdRetweets>[0]; body: Parameters<typeof usersIdRetweets>[1] }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdRetweets>>,
    ApiError,
    { id: Parameters<typeof usersIdRetweets>[0]; body: Parameters<typeof usersIdRetweets>[1] }
  >({
    mutationFn: ({ id, body }) => usersIdRetweets(id, body),
    ...options,
  })
}

export function useUsersIdUnretweets(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdUnretweets>>,
      ApiError,
      {
        id: Parameters<typeof usersIdUnretweets>[0]
        sourceTweetId: Parameters<typeof usersIdUnretweets>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdUnretweets>>,
    ApiError,
    {
      id: Parameters<typeof usersIdUnretweets>[0]
      sourceTweetId: Parameters<typeof usersIdUnretweets>[1]
    }
  >({
    mutationFn: ({ id, sourceTweetId }) => usersIdUnretweets(id, sourceTweetId),
    ...options,
  })
}

export function useUsersIdUnblock(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdUnblock>>,
      ApiError,
      {
        sourceUserId: Parameters<typeof usersIdUnblock>[0]
        targetUserId: Parameters<typeof usersIdUnblock>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdUnblock>>,
    ApiError,
    {
      sourceUserId: Parameters<typeof usersIdUnblock>[0]
      targetUserId: Parameters<typeof usersIdUnblock>[1]
    }
  >({
    mutationFn: ({ sourceUserId, targetUserId }) => usersIdUnblock(sourceUserId, targetUserId),
    ...options,
  })
}

export function useUsersIdUnfollow(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdUnfollow>>,
      ApiError,
      {
        sourceUserId: Parameters<typeof usersIdUnfollow>[0]
        targetUserId: Parameters<typeof usersIdUnfollow>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdUnfollow>>,
    ApiError,
    {
      sourceUserId: Parameters<typeof usersIdUnfollow>[0]
      targetUserId: Parameters<typeof usersIdUnfollow>[1]
    }
  >({
    mutationFn: ({ sourceUserId, targetUserId }) => usersIdUnfollow(sourceUserId, targetUserId),
    ...options,
  })
}

export function useUsersIdUnmute(
  options?: Omit<
    UseMutationOptions<
      Awaited<ReturnType<typeof usersIdUnmute>>,
      ApiError,
      {
        sourceUserId: Parameters<typeof usersIdUnmute>[0]
        targetUserId: Parameters<typeof usersIdUnmute>[1]
      }
    >,
    'mutationFn'
  >
) {
  return useMutation<
    Awaited<ReturnType<typeof usersIdUnmute>>,
    ApiError,
    {
      sourceUserId: Parameters<typeof usersIdUnmute>[0]
      targetUserId: Parameters<typeof usersIdUnmute>[1]
    }
  >({
    mutationFn: ({ sourceUserId, targetUserId }) => usersIdUnmute(sourceUserId, targetUserId),
    ...options,
  })
}
