// This file is auto-generated by openapi-zod-ts - do not edit

export type AddOrDeleteRulesRequest = AddRulesRequest | DeleteRulesRequest

export interface AddOrDeleteRulesResponse {
  data?: Rule[]
  errors?: Problem[]
  meta: RulesResponseMetadata
}

export interface AddRulesRequest {
  add: RuleNoId[]
}

export type Aggregate = number

export type AnimatedGif = Media & {
  preview_image_url?: string
  variants?: Variants
}

export interface BlockUserMutationResponse {
  data?: {
    blocking?: boolean
  }
  errors?: Problem[]
}

export interface BlockUserRequest {
  target_user_id: UserId
}

export interface BookmarkAddRequest {
  tweet_id: TweetId
}

export interface BookmarkMutationResponse {
  data?: {
    bookmarked?: boolean
  }
  errors?: Problem[]
}

export type CashtagEntity = EntityIndicesInclusiveExclusive & CashtagFields

export interface CashtagFields {
  tag: string
}

export type ClientDisconnectedProblem = Problem

export type ClientForbiddenProblem = Problem & {
  reason?: 'official-client-forbidden' | 'client-not-enrolled'
  registration_url?: string
}

export interface ComplianceJob {
  created_at: CreatedAt
  download_expires_at: DownloadExpiration
  download_url: DownloadUrl
  id: JobId
  name?: ComplianceJobName
  status: ComplianceJobStatus
  type: ComplianceJobType
  upload_expires_at: UploadExpiration
  upload_url: UploadUrl
}

export type ComplianceJobName = string

export type ComplianceJobStatus = 'created' | 'in_progress' | 'failed' | 'complete' | 'expired'
export const ComplianceJobStatusValues = [
  'created',
  'in_progress',
  'failed',
  'complete',
  'expired',
] as const

export type ComplianceJobType = 'tweets' | 'users'
export const ComplianceJobTypeValues = ['tweets', 'users'] as const

export type ConflictProblem = Problem

export type ConnectionExceptionProblem = Problem & {
  connection_issue?:
    | 'TooManyConnections'
    | 'ProvisioningSubscription'
    | 'RuleConfigurationIssue'
    | 'RulesInvalidIssue'
}

export interface ContextAnnotation {
  domain: ContextAnnotationDomainFields
  entity: ContextAnnotationEntityFields
}

export interface ContextAnnotationDomainFields {
  description?: string
  id: string
  name?: string
}

export interface ContextAnnotationEntityFields {
  description?: string
  id: string
  name?: string
}

export type CountryCode = string

export interface CreateAttachmentsMessageRequest {
  attachments: DmAttachments
  text?: string
}

export interface CreateComplianceJobRequest {
  name?: ComplianceJobName
  resumable?: boolean
  type: 'tweets' | 'users'
}

export interface CreateComplianceJobResponse {
  data?: ComplianceJob
  errors?: Problem[]
}

export interface CreateDmConversationRequest {
  conversation_type: 'Group'
  message: CreateMessageRequest
  participant_ids: DmParticipants
}

export interface CreateDmEventResponse {
  data?: {
    dm_conversation_id: DmConversationId
    dm_event_id: DmEventId
  }
  errors?: Problem[]
}

export type CreateMessageRequest = CreateTextMessageRequest | CreateAttachmentsMessageRequest

export interface CreateTextMessageRequest {
  attachments?: DmAttachments
  text: string
}

export type CreatedAt = string

export interface DeleteRulesRequest {
  delete: {
    ids?: RuleId[]
    values?: RuleValue[]
  }
}

export type DisallowedResourceProblem = Problem & {
  resource_id: string
  resource_type: 'user' | 'tweet' | 'media' | 'list' | 'space'
  section: 'data' | 'includes'
}

export type DmAttachments = DmMediaAttachment[]

export type DmConversationId = string

export interface DmEvent {
  attachments?: {
    card_ids?: string[]
    media_keys?: MediaKey[]
  }
  created_at?: string /* date-time */
  dm_conversation_id?: DmConversationId
  event_type: string
  id: DmEventId
  participant_ids?: UserId[]
  referenced_tweets?: {
    id: TweetId
  }[]
  sender_id?: UserId
  text?: string
}

export type DmEventId = string

export interface DmMediaAttachment {
  media_id: MediaId
}

export type DmParticipants = UserId[]

export type DownloadExpiration = string

export type DownloadUrl = string

export type DuplicateRuleProblem = Problem & {
  id?: string
  value?: string
}

export type End = string

export interface EntityIndicesInclusiveExclusive {
  end: number
  start: number
}

export interface EntityIndicesInclusiveInclusive {
  end: number
  start: number
}

export interface Error {
  code: number
  message: string
}

export interface Expansions {
  media?: Media[]
  places?: Place[]
  polls?: Poll[]
  topics?: Topic[]
  tweets?: Tweet[]
  users?: User[]
}

export type FieldUnauthorizedProblem = Problem & {
  field: string
  resource_type: 'user' | 'tweet' | 'media' | 'list' | 'space'
  section: 'data' | 'includes'
}

export interface FilteredStreamingTweetResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
  matching_rules?: {
    id: RuleId
    tag?: RuleTag
  }[]
}

export interface FullTextEntities {
  annotations?: EntityIndicesInclusiveInclusive &
    {
      normalized_text?: string
      probability?: number
      type?: string
    }[]
  cashtags?: CashtagEntity[]
  hashtags?: HashtagEntity[]
  mentions?: MentionEntity[]
  urls?: UrlEntity[]
}

export type GenericProblem = Problem

export interface Geo {
  bbox: number[]
  geometry?: Point
  properties: Record<string, unknown>
  type: 'Feature'
}

export interface Get2ComplianceJobsIdResponse {
  data?: ComplianceJob
  errors?: Problem[]
}

export interface Get2ComplianceJobsResponse {
  data?: ComplianceJob[]
  errors?: Problem[]
  meta?: {
    result_count?: ResultCount
  }
}

export interface Get2DmConversationsIdDmEventsResponse {
  data?: DmEvent[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2DmConversationsWithParticipantIdDmEventsResponse {
  data?: DmEvent[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2DmEventsResponse {
  data?: DmEvent[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2ListsIdFollowersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2ListsIdMembersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2ListsIdResponse {
  data?: List
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2ListsIdTweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2SpacesByCreatorIdsResponse {
  data?: Space[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    result_count?: ResultCount
  }
}

export interface Get2SpacesIdBuyersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2SpacesIdResponse {
  data?: Space
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2SpacesIdTweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2SpacesResponse {
  data?: Space[]
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2SpacesSearchResponse {
  data?: Space[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    result_count?: ResultCount
  }
}

export interface Get2TweetsCountsAllResponse {
  data?: SearchCount[]
  errors?: Problem[]
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    total_tweet_count?: Aggregate
  }
}

export interface Get2TweetsCountsRecentResponse {
  data?: SearchCount[]
  errors?: Problem[]
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    total_tweet_count?: Aggregate
  }
}

export interface Get2TweetsFirehoseStreamResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2TweetsIdLikingUsersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2TweetsIdQuoteTweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    result_count?: ResultCount
  }
}

export interface Get2TweetsIdResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2TweetsIdRetweetedByResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2TweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2TweetsSample10StreamResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2TweetsSampleStreamResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2TweetsSearchAllResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    result_count?: ResultCount
  }
}

export interface Get2TweetsSearchRecentResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    result_count?: ResultCount
  }
}

export interface Get2TweetsSearchStreamResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2UsersByResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2UsersByUsernameUsernameResponse {
  data?: User
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2UsersIdBlockingResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdBookmarksResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdFollowedListsResponse {
  data?: List[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdFollowersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdFollowingResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdLikedTweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdListMembershipsResponse {
  data?: List[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdMentionsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdMutingResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdOwnedListsResponse {
  data?: List[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    next_token?: NextToken
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdPinnedListsResponse {
  data?: List[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    result_count?: ResultCount
  }
}

export interface Get2UsersIdResponse {
  data?: User
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2UsersIdTimelinesReverseChronologicalResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersIdTweetsResponse {
  data?: Tweet[]
  errors?: Problem[]
  includes?: Expansions
  meta?: {
    newest_id?: NewestId
    next_token?: NextToken
    oldest_id?: OldestId
    previous_token?: PreviousToken
    result_count?: ResultCount
  }
}

export interface Get2UsersMeResponse {
  data?: User
  errors?: Problem[]
  includes?: Expansions
}

export interface Get2UsersResponse {
  data?: User[]
  errors?: Problem[]
  includes?: Expansions
}

export type HashtagEntity = EntityIndicesInclusiveExclusive & HashtagFields

export interface HashtagFields {
  tag: string
}

export type HttpStatusCode = number

export type InvalidRequestProblem = Problem & {
  errors?: {
    message?: string
    parameters?: Record<string, string[]>
  }[]
}

export type InvalidRuleProblem = Problem

export type JobId = string

export interface List {
  created_at?: string /* date-time */
  description?: string
  follower_count?: number
  id: ListId
  member_count?: number
  name: string
  owner_id?: UserId
  private?: boolean
}

export interface ListAddUserRequest {
  user_id: UserId
}

export interface ListCreateRequest {
  description?: string
  name: string
  private?: boolean
}

export interface ListCreateResponse {
  data?: {
    id: ListId
    name: string
  }
  errors?: Problem[]
}

export interface ListDeleteResponse {
  data?: {
    deleted?: boolean
  }
  errors?: Problem[]
}

export interface ListFollowedRequest {
  list_id: ListId
}

export interface ListFollowedResponse {
  data?: {
    following?: boolean
  }
  errors?: Problem[]
}

export type ListId = string

export interface ListMutateResponse {
  data?: {
    is_member?: boolean
  }
  errors?: Problem[]
}

export interface ListPinnedRequest {
  list_id: ListId
}

export interface ListPinnedResponse {
  data?: {
    pinned?: boolean
  }
  errors?: Problem[]
}

export interface ListUnpinResponse {
  data?: {
    pinned?: boolean
  }
  errors?: Problem[]
}

export interface ListUpdateRequest {
  description?: string
  name?: string
  private?: boolean
}

export interface ListUpdateResponse {
  data?: {
    updated?: boolean
  }
  errors?: Problem[]
}

export interface Media {
  height?: MediaHeight
  media_key?: MediaKey
  type: string
  width?: MediaWidth
}

export type MediaHeight = number

export type MediaId = string

export type MediaKey = string

export type MediaWidth = number

export type MentionEntity = EntityIndicesInclusiveExclusive & MentionFields

export interface MentionFields {
  id?: UserId
  username: UserName
}

export interface MuteUserMutationResponse {
  data?: {
    muting?: boolean
  }
  errors?: Problem[]
}

export interface MuteUserRequest {
  target_user_id: UserId
}

export type NewestId = string

export type NextToken = string

export type NonCompliantRulesProblem = Problem

export type Oauth1PermissionsProblem = Problem

export type OldestId = string

export type OperationalDisconnectProblem = Problem & {
  disconnect_type?:
    | 'OperationalDisconnect'
    | 'UpstreamOperationalDisconnect'
    | 'ForceDisconnect'
    | 'UpstreamUncleanDisconnect'
    | 'SlowReader'
    | 'InternalError'
    | 'ClientApplicationStateDegraded'
    | 'InvalidRules'
}

export type PaginationToken32 = string

export type PaginationToken36 = string

export type PaginationTokenLong = string

export type Photo = Media & {
  alt_text?: string
  url?: string
}

export interface Place {
  contained_within?: PlaceId[]
  country?: string
  country_code?: CountryCode
  full_name: string
  geo?: Geo
  id: PlaceId
  name?: string
  place_type?: PlaceType
}

export type PlaceId = string

export type PlaceType = 'poi' | 'neighborhood' | 'city' | 'admin' | 'country' | 'unknown'
export const PlaceTypeValues = [
  'poi',
  'neighborhood',
  'city',
  'admin',
  'country',
  'unknown',
] as const

export interface Point {
  coordinates: Position
  type: 'Point'
}

export interface Poll {
  duration_minutes?: number
  end_datetime?: string /* date-time */
  id: PollId
  options: PollOption[]
  voting_status?: 'open' | 'closed'
}

export type PollId = string

export interface PollOption {
  label: PollOptionLabel
  position: number
  votes: number
}

export type PollOptionLabel = string

export type Position = number[]

export type PreviousToken = string

export interface Problem {
  detail?: string
  status?: number
  title: string
  type: string
}

export type ReplySettings = 'everyone' | 'mentionedUsers' | 'following' | 'other'
export const ReplySettingsValues = ['everyone', 'mentionedUsers', 'following', 'other'] as const

export type ResourceNotFoundProblem = Problem & {
  parameter: string
  resource_id: string
  resource_type: 'user' | 'tweet' | 'media' | 'list' | 'space'
  value: string
}

export type ResourceUnauthorizedProblem = Problem & {
  parameter: string
  resource_id: string
  resource_type: 'user' | 'tweet' | 'media' | 'list' | 'space'
  section: 'data' | 'includes'
  value: string
}

export type ResourceUnavailableProblem = Problem & {
  parameter: string
  resource_id: string
  resource_type: 'user' | 'tweet' | 'media' | 'list' | 'space'
}

export type ResultCount = number

export interface Rule {
  id?: RuleId
  tag?: RuleTag
  value: RuleValue
}

export type RuleId = string

export interface RuleNoId {
  tag?: RuleTag
  value: RuleValue
}

export type RuleTag = string

export type RuleValue = string

export type RulesCapProblem = Problem

export interface RulesLookupResponse {
  data?: Rule[]
  meta: RulesResponseMetadata
}

export type RulesRequestSummary =
  | {
      created: number
      invalid: number
      not_created: number
      valid: number
    }
  | {
      deleted: number
      not_deleted: number
    }

export interface RulesResponseMetadata {
  next_token?: NextToken
  result_count?: number
  sent: string
  summary?: RulesRequestSummary
}

export interface SearchCount {
  end: End
  start: Start
  tweet_count: TweetCount
}

export interface Space {
  created_at?: string /* date-time */
  creator_id?: UserId
  ended_at?: string /* date-time */
  host_ids?: UserId[]
  id: SpaceId
  invited_user_ids?: UserId[]
  is_ticketed?: boolean
  lang?: string
  participant_count?: number
  scheduled_start?: string /* date-time */
  speaker_ids?: UserId[]
  started_at?: string /* date-time */
  state: 'live' | 'scheduled' | 'ended'
  subscriber_count?: number
  title?: string
  topics?: {
    description?: string
    id: string
    name: string
  }[]
  updated_at?: string /* date-time */
}

export type SpaceId = string

export type Start = string

export interface StreamingTweetResponse {
  data?: Tweet
  errors?: Problem[]
  includes?: Expansions
}

export interface Topic {
  description?: string
  id: TopicId
  name: string
}

export type TopicId = string

export interface Tweet {
  attachments?: {
    media_keys?: MediaKey[]
    poll_ids?: PollId[]
  }
  author_id?: UserId
  context_annotations?: ContextAnnotation[]
  conversation_id?: TweetId
  created_at?: string /* date-time */
  edit_controls?: {
    editable_until: string /* date-time */
    edits_remaining: number
    is_edit_eligible: boolean
  }
  edit_history_tweet_ids: TweetId[]
  entities?: FullTextEntities
  geo?: {
    coordinates?: Point
    place_id?: PlaceId
  }
  id: TweetId
  in_reply_to_user_id?: UserId
  lang?: string
  non_public_metrics?: {
    impression_count?: number
  }
  organic_metrics?: {
    impression_count: number
    like_count: number
    reply_count: number
    retweet_count: number
  }
  possibly_sensitive?: boolean
  promoted_metrics?: {
    impression_count?: number
    like_count?: number
    reply_count?: number
    retweet_count?: number
  }
  public_metrics?: {
    impression_count: number
    like_count: number
    quote_count?: number
    reply_count: number
    retweet_count: number
  }
  referenced_tweets?: {
    id: TweetId
    type: 'retweeted' | 'quoted' | 'replied_to'
  }[]
  reply_settings?: ReplySettings
  source?: string
  text: TweetText
  withheld?: TweetWithheld
}

export type TweetComplianceData =
  | TweetDeleteComplianceSchema
  | TweetWithheldComplianceSchema
  | TweetDropComplianceSchema
  | TweetUndropComplianceSchema
  | TweetEditComplianceSchema

export interface TweetComplianceSchema {
  event_at: string /* date-time */
  quote_tweet_id?: TweetId
  tweet: {
    author_id: UserId
    id: TweetId
  }
}

export type TweetComplianceStreamResponse =
  | {
      data: TweetComplianceData
    }
  | {
      errors: Problem[]
    }

export type TweetCount = number

export interface TweetCreateRequest {
  card_uri?: string
  direct_message_deep_link?: string
  for_super_followers_only?: boolean
  geo?: {
    place_id?: string
  }
  media?: {
    media_ids: MediaId[]
    tagged_user_ids?: UserId[]
  }
  nullcast?: boolean
  poll?: {
    duration_minutes: number
    options: string[]
    reply_settings?: 'following' | 'mentionedUsers'
  }
  quote_tweet_id?: TweetId
  reply?: {
    exclude_reply_user_ids?: UserId[]
    in_reply_to_tweet_id: TweetId
  }
  reply_settings?: 'following' | 'mentionedUsers'
  text?: TweetText
}

export interface TweetCreateResponse {
  data?: {
    id: TweetId
    text: TweetText
  }
  errors?: Problem[]
}

export interface TweetDeleteComplianceSchema {
  delete: TweetComplianceSchema
}

export interface TweetDeleteResponse {
  data?: {
    deleted: boolean
  }
  errors?: Problem[]
}

export interface TweetDropComplianceSchema {
  drop: TweetComplianceSchema
}

export interface TweetEditComplianceObjectSchema {
  edit_tweet_ids: TweetId[]
  event_at: string /* date-time */
  initial_tweet_id: TweetId
  tweet: {
    id: TweetId
  }
}

export interface TweetEditComplianceSchema {
  tweet_edit: TweetEditComplianceObjectSchema
}

export interface TweetHideRequest {
  hidden: boolean
}

export interface TweetHideResponse {
  data?: {
    hidden?: boolean
  }
}

export type TweetId = string

export type TweetLabelData = TweetNoticeSchema | TweetUnviewableSchema

export type TweetLabelStreamResponse =
  | {
      data: TweetLabelData
    }
  | {
      errors: Problem[]
    }

export interface TweetNotice {
  application: string
  details?: string
  event_at: string /* date-time */
  event_type: string
  extended_details_url?: string
  label_title?: string
  tweet: {
    author_id: UserId
    id: TweetId
  }
}

export interface TweetNoticeSchema {
  public_tweet_notice: TweetNotice
}

export interface TweetTakedownComplianceSchema {
  event_at: string /* date-time */
  quote_tweet_id?: TweetId
  tweet: {
    author_id: UserId
    id: TweetId
  }
  withheld_in_countries: CountryCode[]
}

export type TweetText = string

export interface TweetUndropComplianceSchema {
  undrop: TweetComplianceSchema
}

export interface TweetUnviewable {
  application: string
  event_at: string /* date-time */
  tweet: {
    author_id: UserId
    id: TweetId
  }
}

export interface TweetUnviewableSchema {
  public_tweet_unviewable: TweetUnviewable
}

export interface TweetWithheld {
  copyright: boolean
  country_codes: CountryCode[]
  scope?: 'tweet' | 'user'
}

export interface TweetWithheldComplianceSchema {
  withheld: TweetTakedownComplianceSchema
}

export type UnsupportedAuthenticationProblem = Problem

export type UploadExpiration = string

export type UploadUrl = string

export type Url = string

export type UrlEntity = EntityIndicesInclusiveExclusive & UrlFields

export interface UrlFields {
  description?: string
  display_url?: string
  expanded_url?: Url
  images?: UrlImage[]
  media_key?: MediaKey
  status?: HttpStatusCode
  title?: string
  unwound_url?: string
  url: Url
}

export interface UrlImage {
  height?: MediaHeight
  url?: Url
  width?: MediaWidth
}

export type UsageCapExceededProblem = Problem & {
  period?: 'Daily' | 'Monthly'
  scope?: 'Account' | 'Product'
}

export interface User {
  created_at?: string /* date-time */
  description?: string
  entities?: {
    description?: FullTextEntities
    url?: {
      urls?: UrlEntity[]
    }
  }
  id: UserId
  location?: string
  name: string
  pinned_tweet_id?: TweetId
  profile_image_url?: string
  protected?: boolean
  public_metrics?: {
    followers_count: number
    following_count: number
    listed_count: number
    tweet_count: number
  }
  url?: string
  username: UserName
  verified?: boolean
  verified_type?: string
  withheld?: UserWithheld
}

export type UserComplianceData =
  | UserProtectComplianceSchema
  | UserUnprotectComplianceSchema
  | UserDeleteComplianceSchema
  | UserUndeleteComplianceSchema
  | UserSuspendComplianceSchema
  | UserUnsuspendComplianceSchema
  | UserWithheldComplianceSchema
  | UserScrubGeoSchema
  | UserProfileModificationComplianceSchema

export interface UserComplianceSchema {
  event_at: string /* date-time */
  user: {
    id: UserId
  }
}

export type UserComplianceStreamResponse =
  | {
      data: UserComplianceData
    }
  | {
      errors: Problem[]
    }

export interface UserDeleteComplianceSchema {
  user_delete: UserComplianceSchema
}

export type UserId = string

export type UserIdMatchesAuthenticatedUser = string

export type UserName = string

export interface UserProfileModificationComplianceSchema {
  user_profile_modification: UserProfileModificationObjectSchema
}

export interface UserProfileModificationObjectSchema {
  event_at: string /* date-time */
  new_value: string
  profile_field: string
  user: {
    id: UserId
  }
}

export interface UserProtectComplianceSchema {
  user_protect: UserComplianceSchema
}

export interface UserScrubGeoObjectSchema {
  event_at: string /* date-time */
  up_to_tweet_id: TweetId
  user: {
    id: UserId
  }
}

export interface UserScrubGeoSchema {
  scrub_geo: UserScrubGeoObjectSchema
}

export interface UserSuspendComplianceSchema {
  user_suspend: UserComplianceSchema
}

export interface UserTakedownComplianceSchema {
  event_at: string /* date-time */
  user: {
    id: UserId
  }
  withheld_in_countries: CountryCode[]
}

export interface UserUndeleteComplianceSchema {
  user_undelete: UserComplianceSchema
}

export interface UserUnprotectComplianceSchema {
  user_unprotect: UserComplianceSchema
}

export interface UserUnsuspendComplianceSchema {
  user_unsuspend: UserComplianceSchema
}

export interface UserWithheld {
  country_codes: CountryCode[]
  scope?: 'user'
}

export interface UserWithheldComplianceSchema {
  user_withheld: UserTakedownComplianceSchema
}

export interface UsersFollowingCreateRequest {
  target_user_id: UserId
}

export interface UsersFollowingCreateResponse {
  data?: {
    following?: boolean
    pending_follow?: boolean
  }
  errors?: Problem[]
}

export interface UsersFollowingDeleteResponse {
  data?: {
    following?: boolean
  }
  errors?: Problem[]
}

export interface UsersLikesCreateRequest {
  tweet_id: TweetId
}

export interface UsersLikesCreateResponse {
  data?: {
    liked?: boolean
  }
  errors?: Problem[]
}

export interface UsersLikesDeleteResponse {
  data?: {
    liked?: boolean
  }
  errors?: Problem[]
}

export interface UsersRetweetsCreateRequest {
  tweet_id: TweetId
}

export interface UsersRetweetsCreateResponse {
  data?: {
    retweeted?: boolean
  }
  errors?: Problem[]
}

export interface UsersRetweetsDeleteResponse {
  data?: {
    retweeted?: boolean
  }
  errors?: Problem[]
}

export interface Variant {
  bit_rate?: number
  content_type?: string
  url?: string
}

export type Variants = Variant[]

export type Video = Media & {
  duration_ms?: number
  non_public_metrics?: {
    playback_0_count?: number
    playback_100_count?: number
    playback_25_count?: number
    playback_50_count?: number
    playback_75_count?: number
  }
  organic_metrics?: {
    playback_0_count?: number
    playback_100_count?: number
    playback_25_count?: number
    playback_50_count?: number
    playback_75_count?: number
    view_count?: number
  }
  preview_image_url?: string
  promoted_metrics?: {
    playback_0_count?: number
    playback_100_count?: number
    playback_25_count?: number
    playback_50_count?: number
    playback_75_count?: number
    view_count?: number
  }
  public_metrics?: {
    view_count?: number
  }
  variants?: Variants
}
